// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/workspaces/[wsId]/users/indicators/groups/migrate/route';

export const PUT = legacyRoute.PUT;
