// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/time-tracking/requests/[id]/route';

export const PUT = legacyRoute.PUT;
export const PATCH = legacyRoute.PATCH;
