import type { Subprocessor } from './types';

export const SUBPROCESSORS: readonly Subprocessor[] = [
  {
    changedAt: '2026-07-27',
    dataCategories: ['account identifiers', 'customer content', 'service logs'],
    name: 'Supabase',
    privacyUrl: 'https://supabase.com/privacy',
    purpose: 'Authentication, databases, realtime services, and file storage',
    regions: ['Customer-selected or service-configured regions'],
  },
  {
    changedAt: '2026-07-27',
    dataCategories: ['request metadata', 'application content', 'diagnostics'],
    name: 'Vercel',
    privacyUrl: 'https://vercel.com/legal/privacy-policy',
    purpose: 'Application hosting, delivery, analytics, and observability',
    regions: ['Global edge network'],
  },
  {
    changedAt: '2026-07-27',
    dataCategories: ['IP addresses', 'request metadata', 'security signals'],
    name: 'Cloudflare',
    privacyUrl: 'https://www.cloudflare.com/privacypolicy/',
    purpose: 'Network delivery, DNS, abuse prevention, and security',
    regions: ['Global network'],
  },
  {
    changedAt: '2026-07-27',
    dataCategories: ['AI prompts and outputs when selected', 'usage metadata'],
    name: 'OpenAI',
    privacyUrl: 'https://openai.com/policies/privacy-policy/',
    purpose: 'Optional AI model inference',
    regions: ['Provider-operated regions'],
  },
  {
    changedAt: '2026-07-27',
    dataCategories: [
      'integration data',
      'calendar and file content',
      'AI inputs',
    ],
    name: 'Google Cloud',
    privacyUrl: 'https://policies.google.com/privacy',
    purpose: 'Cloud infrastructure, integrations, and optional AI inference',
    regions: ['Provider-operated and customer-selected regions'],
  },
  {
    changedAt: '2026-07-27',
    dataCategories: ['integration data', 'calendar, mail, and file content'],
    name: 'Microsoft',
    privacyUrl: 'https://privacy.microsoft.com/privacystatement',
    purpose: 'Optional Microsoft account and productivity integrations',
    regions: ['Provider-operated regions'],
  },
  {
    changedAt: '2026-07-27',
    dataCategories: ['billing contact details', 'transaction metadata'],
    name: 'Polar',
    privacyUrl: 'https://polar.sh/legal/privacy',
    purpose: 'Subscription billing and payment processing',
    regions: ['Provider-operated regions'],
  },
  {
    changedAt: '2026-07-27',
    dataCategories: ['email address', 'message content', 'delivery metadata'],
    name: 'Resend',
    privacyUrl: 'https://resend.com/legal/privacy-policy',
    purpose: 'Transactional email delivery',
    regions: ['Provider-operated regions'],
  },
  {
    changedAt: '2026-07-27',
    dataCategories: ['error diagnostics', 'device metadata', 'stack traces'],
    name: 'Sentry',
    privacyUrl: 'https://sentry.io/privacy/',
    purpose: 'Error monitoring and reliability diagnostics',
    regions: ['Provider-operated regions'],
  },
] as const;
