// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/tulearn/parent-links/[linkId]/route';

export const PATCH = legacyRoute.PATCH;
