export type CmsStrings = {
  activityTab: string;
  activityFeedTitle: string;
  archivedQueue: string;
  archiveAction: string;
  archiveBacklogHint: string;
  assetGalleryTitle: string;
  assetsLabel: string;
  attentionTitle: string;
  backToEpmAction: string;
  bodyMarkdownDescription: string;
  bodyMarkdownLabel: string;
  bulkActionsTitle: string;
  bulkRemoveMediaAction: string;
  bulkSelectionHint: string;
  bulkUploadMediaAction: string;
  cancelAction: string;
  categoryClearAction: string;
  categoryCreateAction: string;
  categoryCreateHint: string;
  categoryCreatePlaceholder: string;
  categoryDescription: string;
  categoryExistingDescription: string;
  categoryLibraryDescription: string;
  categoryLibraryEmpty: string;
  categoryLibraryLabel: string;
  categoryLabel: string;
  categoryActiveHint: string;
  categoryPickerPlaceholder: string;
  categoryPlaceholder: string;
  categorySearchPlaceholder: string;
  captionLabel: string;
  captionPlaceholder: string;
  carouselInteractionHint: string;
  closeFullscreenAction: string;
  collectionFallbackLabel: string;
  collectionHealthTitle: string;
  collectionsLabel: string;
  collectionsMetricLabel: string;
  contentTab: string;
  coverBadge: string;
  coverImageDescription: string;
  coverImageTitle: string;
  coverSaveSuccessToast: string;
  coverUploadSuccessToast: string;
  createCollectionAction: string;
  createEntryAction: string;
  deleteCollectionAction: string;
  deleteAssetAction: string;
  deleteAssetConfirmDescription: string;
  deleteAssetConfirmTitle: string;
  deleteEntryAction: string;
  deleteEntryConfirmDescription: string;
  deleteEntryConfirmTitle: string;
  descriptionEditorDescription: string;
  descriptionLabel: string;
  dashboardModeLabel: string;
  dashboardPreferencesTitle: string;
  densityCompact: string;
  densityComfortable: string;
  densityLabel: string;
  detailsDescription: string;
  detailsTitle: string;
  draftQueue: string;
  duplicateAction: string;
  editCollectionAction: string;
  editCollectionDescription: string;
  editEntriesDescription: string;
  editEntryAction: string;
  editEntryDescription: string;
  editEntryTitle: string;
  editModeDescription: string;
  editModeLabel: string;
  editSettingsDescription: string;
  emptyCollection: string;
  emptyEntries: string;
  enabledLabel: string;
  entriesMetricLabel: string;
  entryDeckTitle: string;
  entrySummaryTitle: string;
  featuredEntryTitle: string;
  featuredEntriesEmpty: string;
  featuredGalleryEntriesDescription: string;
  featuredGalleryEntriesLabel: string;
  featuredPlacementActiveDescription: string;
  featuredPlacementActiveLabel: string;
  featuredPlacementAddAction: string;
  featuredPlacementArtworkDescription: string;
  featuredPlacementCreateAction: string;
  featuredPlacementCreateSuccessToast: string;
  featuredPlacementGalleryLabel: string;
  featuredPlacementInactiveDescription: string;
  featuredPlacementInactiveLabel: string;
  featuredPlacementPositionLabel: string;
  featuredPlacementRemoveAction: string;
  featuredPlacementSectionMissing: string;
  featuredPlacementTitle: string;
  featuredPlacementWritingDescription: string;
  featuredPlacementWritingLabel: string;
  featuredWritingEntriesDescription: string;
  featuredWritingEntriesLabel: string;
  filterAll: string;
  focusOperator: string;
  focusVisual: string;
  focusWorkflow: string;
  fullscreenAction: string;
  importAction: string;
  importHint: string;
  loadingPreviewLabel: string;
  metadataLabel: string;
  missingLeadImageLabel: string;
  noAdapterLabel: string;
  noCanonicalIdLabel: string;
  noCoverDescription: string;
  noCoverTitle: string;
  nextAction: string;
  noneLabel: string;
  notScheduledLabel: string;
  openDetailsAction: string;
  openCollectionAction: string;
  openPreviewAction: string;
  overviewTab: string;
  payloadLabel: string;
  previewCollectionTitle: string;
  previewDescription: string;
  previewEmptyDescription: string;
  previewEmptyTitle: string;
  previewEntriesTitle: string;
  previewModeDescription: string;
  previewModeLabel: string;
  previewProjectLabel: string;
  previewTitle: string;
  previousAction: string;
  profileDataLabel: string;
  quickTaxonomyAction: string;
  quickTaxonomyDescription: string;
  manageCollectionAction: string;
  manageCollectionDescription: string;
  markdownPreviewLabel: string;
  markdownWriteLabel: string;
  mediaProcessingLabel: string;
  navigationTitleDescription: string;
  navigationTitleLabel: string;
  publishAction: string;
  publishedQueue: string;
  quickCreateHint: string;
  recentUnpublishedHint: string;
  recoveryHint: string;
  refreshAction: string;
  resetZoomAction: string;
  renderedLabel: string;
  replaceCoverAction: string;
  removeMediaAction: string;
  saveAction: string;
  saveCoverAction: string;
  saveMediaDetailsAction: string;
  scheduleAction: string;
  scheduledForLabel: string;
  scheduledQueue: string;
  searchPlaceholder: string;
  selectAllMediaAction: string;
  setAsCoverAction: string;
  settingsTab: string;
  showActivityLabel: string;
  showCollectionsLabel: string;
  showVisualsLabel: string;
  slugLabel: string;
  statusArchived: string;
  statusDraft: string;
  statusLabel: string;
  statusPublished: string;
  statusScheduled: string;
  subtitleLabel: string;
  summaryLabel: string;
  taxonomyDescription: string;
  taxonomyPendingSave: string;
  taxonomySaveHint: string;
  taxonomyTitle: string;
  tagsClearAction: string;
  tagsCreateAction: string;
  tagsCreateHint: string;
  tagsCreatePlaceholder: string;
  tagsDescription: string;
  tagsEmpty: string;
  tagsExistingDescription: string;
  tagLibraryDescription: string;
  tagLibraryEmpty: string;
  tagLibraryLabel: string;
  tagsLabel: string;
  tagsPickerPlaceholder: string;
  tagsPlaceholder: string;
  tagsRemoveAction: string;
  tagsSearchPlaceholder: string;
  tabsDescription: string;
  title: string;
  titleLabel: string;
  unboundLabel: string;
  unknownCollectionLabel: string;
  unpublishAction: string;
  uploadCoverAction: string;
  visualBoardTitle: string;
  workflowTab: string;
  workspaceBindingLabel: string;
  workspaceStatusTitle: string;
  zoomInAction: string;
  zoomOutAction: string;
};

export function buildCmsStrings(t: (key: any) => string): CmsStrings {
  return {
    activityFeedTitle: t('epm.activity_feed_title'),
    activityTab: t('epm.activity_tab'),
    archivedQueue: t('epm.archived_queue'),
    archiveAction: t('epm.archive_action'),
    archiveBacklogHint: t('epm.archive_backlog_hint'),
    assetGalleryTitle: t('epm.asset_gallery_title'),
    assetsLabel: t('epm.assets_label'),
    attentionTitle: t('epm.attention_title'),
    backToEpmAction: t('epm.back_to_epm_action'),
    bodyMarkdownDescription: t('epm.body_markdown_description'),
    bodyMarkdownLabel: t('epm.body_markdown_label'),
    bulkActionsTitle: t('epm.bulk_actions_title'),
    bulkRemoveMediaAction: t('epm.bulk_remove_media_action'),
    bulkSelectionHint: t('epm.bulk_selection_hint'),
    bulkUploadMediaAction: t('epm.bulk_upload_media_action'),
    cancelAction: t('epm.cancel_action'),
    categoryActiveHint: t('epm.category_active_hint'),
    categoryClearAction: t('epm.category_clear_action'),
    categoryCreateAction: t('epm.category_create_action'),
    categoryCreateHint: t('epm.category_create_hint'),
    categoryCreatePlaceholder: t('epm.category_create_placeholder'),
    categoryDescription: t('epm.category_description'),
    categoryExistingDescription: t('epm.category_existing_description'),
    categoryLibraryDescription: t('epm.category_library_description'),
    categoryLibraryEmpty: t('epm.category_library_empty'),
    categoryLibraryLabel: t('epm.category_library_label'),
    categoryLabel: t('epm.category_label'),
    categoryPickerPlaceholder: t('epm.category_picker_placeholder'),
    categoryPlaceholder: t('epm.category_placeholder'),
    categorySearchPlaceholder: t('epm.category_search_placeholder'),
    captionLabel: t('epm.caption_label'),
    captionPlaceholder: t('epm.caption_placeholder'),
    carouselInteractionHint: t('epm.carousel_interaction_hint'),
    closeFullscreenAction: t('epm.close_fullscreen_action'),
    collectionFallbackLabel: t('epm.collection_fallback_label'),
    collectionHealthTitle: t('epm.collection_health_title'),
    collectionsLabel: t('epm.collections_label'),
    collectionsMetricLabel: t('epm.collections_metric_label'),
    contentTab: t('epm.content_tab'),
    coverBadge: t('epm.cover_badge'),
    coverImageDescription: t('epm.cover_image_description'),
    coverImageTitle: t('epm.cover_image_title'),
    coverSaveSuccessToast: t('epm.cover_save_success_toast'),
    coverUploadSuccessToast: t('epm.cover_upload_success_toast'),
    createCollectionAction: t('epm.create_collection_action'),
    createEntryAction: t('epm.create_entry_action'),
    deleteCollectionAction: t('epm.delete_collection_action'),
    deleteAssetAction: t('epm.delete_asset_action'),
    deleteAssetConfirmDescription: t('epm.delete_asset_confirm_description'),
    deleteAssetConfirmTitle: t('epm.delete_asset_confirm_title'),
    deleteEntryAction: t('epm.delete_entry_action'),
    deleteEntryConfirmDescription: t('epm.delete_entry_confirm_description'),
    deleteEntryConfirmTitle: t('epm.delete_entry_confirm_title'),
    descriptionEditorDescription: t('epm.description_editor_description'),
    descriptionLabel: t('epm.description_label'),
    dashboardModeLabel: t('epm.dashboard_mode_label'),
    dashboardPreferencesTitle: t('epm.dashboard_preferences_title'),
    densityCompact: t('epm.density_compact'),
    densityComfortable: t('epm.density_comfortable'),
    densityLabel: t('epm.density_label'),
    detailsDescription: t('epm.details_description'),
    detailsTitle: t('epm.details_title'),
    draftQueue: t('epm.draft_queue'),
    duplicateAction: t('epm.duplicate_action'),
    editCollectionAction: t('epm.edit_collection_action'),
    editCollectionDescription: t('epm.edit_collection_description'),
    editEntriesDescription: t('epm.edit_entries_description'),
    editEntryAction: t('epm.edit_entry_action'),
    editEntryDescription: t('epm.edit_entry_description'),
    editEntryTitle: t('epm.edit_entry_title'),
    editModeDescription: t('epm.edit_mode_description'),
    editModeLabel: t('epm.edit_mode_label'),
    editSettingsDescription: t('epm.edit_settings_description'),
    emptyCollection: t('epm.empty_collection'),
    emptyEntries: t('epm.empty_entries'),
    enabledLabel: t('epm.enabled_label'),
    entriesMetricLabel: t('epm.entries_metric_label'),
    entryDeckTitle: t('epm.entry_deck_title'),
    entrySummaryTitle: t('epm.entry_summary_title'),
    featuredEntryTitle: t('epm.featured_entry_title'),
    featuredEntriesEmpty: t('epm.featured_entries_empty'),
    featuredGalleryEntriesDescription: t(
      'epm.featured_gallery_entries_description'
    ),
    featuredGalleryEntriesLabel: t('epm.featured_gallery_entries_label'),
    featuredPlacementActiveDescription: t(
      'epm.featured_placement_active_description'
    ),
    featuredPlacementActiveLabel: t('epm.featured_placement_active_label'),
    featuredPlacementAddAction: t('epm.featured_placement_add_action'),
    featuredPlacementArtworkDescription: t(
      'epm.featured_placement_artwork_description'
    ),
    featuredPlacementCreateAction: t('epm.featured_placement_create_action'),
    featuredPlacementCreateSuccessToast: t(
      'epm.featured_placement_create_success_toast'
    ),
    featuredPlacementGalleryLabel: t('epm.featured_placement_gallery_label'),
    featuredPlacementInactiveDescription: t(
      'epm.featured_placement_inactive_description'
    ),
    featuredPlacementInactiveLabel: t('epm.featured_placement_inactive_label'),
    featuredPlacementPositionLabel: t('epm.featured_placement_position_label'),
    featuredPlacementRemoveAction: t('epm.featured_placement_remove_action'),
    featuredPlacementSectionMissing: t(
      'epm.featured_placement_section_missing'
    ),
    featuredPlacementTitle: t('epm.featured_placement_title'),
    featuredPlacementWritingDescription: t(
      'epm.featured_placement_writing_description'
    ),
    featuredPlacementWritingLabel: t('epm.featured_placement_writing_label'),
    featuredWritingEntriesDescription: t(
      'epm.featured_writing_entries_description'
    ),
    featuredWritingEntriesLabel: t('epm.featured_writing_entries_label'),
    filterAll: t('epm.filter_all'),
    focusOperator: t('epm.focus_operator'),
    focusVisual: t('epm.focus_visual'),
    focusWorkflow: t('epm.focus_workflow'),
    fullscreenAction: t('epm.fullscreen_action'),
    importAction: t('epm.import_action'),
    importHint: t('epm.import_hint'),
    loadingPreviewLabel: t('epm.loading_preview_label'),
    metadataLabel: t('epm.metadata_label'),
    mediaProcessingLabel: t('epm.media_processing_label'),
    navigationTitleDescription: t('epm.navigation_title_description'),
    navigationTitleLabel: t('epm.navigation_title_label'),
    missingLeadImageLabel: t('epm.missing_lead_image_label'),
    noAdapterLabel: t('epm.no_adapter_label'),
    noCanonicalIdLabel: t('epm.no_canonical_id_label'),
    noCoverDescription: t('epm.no_cover_description'),
    noCoverTitle: t('epm.no_cover_title'),
    nextAction: t('epm.next_action'),
    noneLabel: t('epm.none_label'),
    notScheduledLabel: t('epm.not_scheduled_label'),
    openDetailsAction: t('epm.open_details_action'),
    openCollectionAction: t('epm.open_collection_action'),
    openPreviewAction: t('epm.open_preview_action'),
    overviewTab: t('epm.overview_tab'),
    payloadLabel: t('epm.payload_label'),
    previewCollectionTitle: t('epm.preview_collection_title'),
    previewDescription: t('epm.preview_description'),
    previewEmptyDescription: t('epm.preview_empty_description'),
    previewEmptyTitle: t('epm.preview_empty_title'),
    previewEntriesTitle: t('epm.preview_entries_title'),
    previewModeDescription: t('epm.preview_mode_description'),
    previewModeLabel: t('epm.preview_mode_label'),
    previewProjectLabel: t('epm.preview_project_label'),
    previewTitle: t('epm.preview_title'),
    previousAction: t('epm.previous_action'),
    profileDataLabel: t('epm.profile_data_label'),
    quickTaxonomyAction: t('epm.quick_taxonomy_action'),
    quickTaxonomyDescription: t('epm.quick_taxonomy_description'),
    manageCollectionAction: t('epm.manage_collection_action'),
    manageCollectionDescription: t('epm.manage_collection_description'),
    markdownPreviewLabel: t('epm.markdown_preview_label'),
    markdownWriteLabel: t('epm.markdown_write_label'),
    publishAction: t('epm.publish_action'),
    publishedQueue: t('epm.published_queue'),
    quickCreateHint: t('epm.quick_create_hint'),
    recentUnpublishedHint: t('epm.recent_unpublished_hint'),
    recoveryHint: t('epm.recovery_hint'),
    refreshAction: t('epm.refresh_action'),
    resetZoomAction: t('epm.reset_zoom_action'),
    renderedLabel: t('epm.rendered_label'),
    replaceCoverAction: t('epm.replace_cover_action'),
    removeMediaAction: t('epm.remove_media_action'),
    saveAction: t('epm.save_action'),
    saveCoverAction: t('epm.save_cover_action'),
    saveMediaDetailsAction: t('epm.save_media_details_action'),
    scheduleAction: t('epm.schedule_action'),
    scheduledForLabel: t('epm.scheduled_for_label'),
    scheduledQueue: t('epm.scheduled_queue'),
    searchPlaceholder: t('epm.search_placeholder'),
    selectAllMediaAction: t('epm.select_all_media_action'),
    setAsCoverAction: t('epm.set_as_cover_action'),
    settingsTab: t('epm.settings_tab'),
    showActivityLabel: t('epm.show_activity_label'),
    showCollectionsLabel: t('epm.show_collections_label'),
    showVisualsLabel: t('epm.show_visuals_label'),
    slugLabel: t('epm.slug_label'),
    statusArchived: t('epm.status_archived'),
    statusDraft: t('epm.status_draft'),
    statusLabel: t('epm.status_label'),
    statusPublished: t('epm.status_published'),
    statusScheduled: t('epm.status_scheduled'),
    subtitleLabel: t('epm.subtitle_label'),
    summaryLabel: t('epm.summary_label'),
    taxonomyDescription: t('epm.taxonomy_description'),
    taxonomyPendingSave: t('epm.taxonomy_pending_save'),
    taxonomySaveHint: t('epm.taxonomy_save_hint'),
    taxonomyTitle: t('epm.taxonomy_title'),
    tagsClearAction: t('epm.tags_clear_action'),
    tagsCreateAction: t('epm.tags_create_action'),
    tagsCreateHint: t('epm.tags_create_hint'),
    tagsCreatePlaceholder: t('epm.tags_create_placeholder'),
    tagsDescription: t('epm.tags_description'),
    tagsEmpty: t('epm.tags_empty'),
    tagsExistingDescription: t('epm.tags_existing_description'),
    tagLibraryDescription: t('epm.tag_library_description'),
    tagLibraryEmpty: t('epm.tag_library_empty'),
    tagLibraryLabel: t('epm.tag_library_label'),
    tagsLabel: t('epm.tags_label'),
    tagsPickerPlaceholder: t('epm.tags_picker_placeholder'),
    tagsPlaceholder: t('epm.tags_placeholder'),
    tagsRemoveAction: t('epm.tags_remove_action'),
    tagsSearchPlaceholder: t('epm.tags_search_placeholder'),
    tabsDescription: t('epm.tabs_description'),
    title: t('epm.title'),
    titleLabel: t('epm.title_label'),
    unboundLabel: t('epm.unbound_label'),
    unknownCollectionLabel: t('epm.unknown_collection_label'),
    unpublishAction: t('epm.unpublish_action'),
    uploadCoverAction: t('epm.upload_cover_action'),
    visualBoardTitle: t('epm.visual_board_title'),
    workflowTab: t('epm.workflow_tab'),
    workspaceBindingLabel: t('epm.workspace_binding_label'),
    workspaceStatusTitle: t('epm.workspace_status_title'),
    zoomInAction: t('epm.zoom_in_action'),
    zoomOutAction: t('epm.zoom_out_action'),
  };
}
