import type { ExternalProjectAdapterKind } from '@tuturuuu/types';

export const EXTERNAL_PROJECT_ENABLED_SECRET = 'EXTERNAL_PROJECT_ENABLED';
export const EXTERNAL_PROJECT_CANONICAL_ID_SECRET =
  'EXTERNAL_PROJECT_CANONICAL_ID';

export const EXTERNAL_PROJECT_PREVIEW_QUERY_PARAM = 'preview';

export const EXTERNAL_PROJECT_ADAPTER_OPTIONS: ExternalProjectAdapterKind[] = [
  'junly',
  'yoola',
  'theguyser',
  'exocorpse',
  'shu',
  'yashie',
  'shiraoki',
  'kendra',
  'richfield',
];

export const EXOCORPSE_EXTERNAL_PROJECT_COLLECTIONS = [
  'about',
  'about-content',
  'about-faqs',
  'stories',
  'worlds',
  'characters',
  'relationship-types',
  'outfit-types',
  'event-types',
  'factions',
  'locations',
  'location-gallery',
  'character-outfits',
  'character-gallery',
  'character-relationships',
  'character-factions',
  'character-locations',
  'character-worlds',
  'portfolio-art',
  'portfolio-writing',
  'portfolio-games',
  'commission-services',
  'commission-addons',
  'commission-styles',
  'commission-pictures',
  'commission-service-addons',
  'commission-blacklist',
  'blog-posts',
  'heaven-space-passages',
  'heaven-space-assets',
  'heaven-space-scenes',
  'heaven-space-scene-choices',
  'timelines',
  'events',
  'event-participants',
  'event-factions',
  'tags',
  'entity-tags',
  'moodboards',
  'media-assets',
  'cofi-samples',
] as const;

export const DEFAULT_EXTERNAL_PROJECT_COLLECTIONS = {
  exocorpse: [...EXOCORPSE_EXTERNAL_PROJECT_COLLECTIONS],
  kendra: ['profile', 'voice-reels', 'credits', 'studio', 'contact'],
  richfield: [
    'brands',
    'leadership',
    'milestones',
    'contact-page',
    'contact-channels',
    'contact-form',
    'contact-submissions',
    'articles',
    'jobs',
    'image-library',
  ],
  junly: [
    'research-projects',
    'game-projects',
    'artworks',
    'feed-posts',
    'music-tracks',
    'singleton-sections',
  ],
  theguyser: [
    'site-config',
    'navigation',
    'quick-launch',
    'panel-content',
    'awards',
    'experience',
    'contact-social',
    'showreel',
  ],
  shu: [
    'profile',
    'projects',
    'games',
    'contact',
    'town-stops',
    'asset-library',
  ],
  yashie: [
    'profile',
    'writing-worlds',
    'gallery',
    'blog-posts',
    'shop-products',
    'social-links',
  ],
  shiraoki: [
    'site-config',
    'launch-gate',
    'navigation',
    'editorial-sections',
    'shopify-settings',
  ],
  yoola: ['artworks', 'lore-capsules', 'singleton-sections'],
} satisfies Record<ExternalProjectAdapterKind, string[]>;

export const EXTERNAL_PROJECT_DISPLAY_NAMES = {
  exocorpse: 'Exocorpse',
  junly: 'Junly',
  kendra: 'Kendra',
  richfield: 'Richfield',
  shu: 'Shu',
  theguyser: 'TheGuyser',
  yashie: 'Yashie',
  shiraoki: 'Shiraoki',
  yoola: 'Yoola',
} satisfies Record<ExternalProjectAdapterKind, string>;
