import '@tuturuuu/ui/globals.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col gap-4 p-4 md:p-8">
          <div className="flex gap-4 font-semibold">
            <Link href="/" className="hover:underline">
              Home
            </Link>
            <Link href="/tool-calling" className="hover:underline">
              Tool Calling
            </Link>
          </div>
          <h1 className="text-2xl font-bold">Playground</h1>
          {children}
        </div>
      </body>
    </html>
  );
}
