// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/public/user-profile-links/[code]/submit/route';

export const POST = legacyRoute.POST;
