// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/link-shortener/[linkId]/password/route';

export const PATCH = legacyRoute.PATCH;
export const DELETE = legacyRoute.DELETE;
