export const DATABASE_DEFAULT_EXCLUDED_GROUPS_CONFIG_ID =
  'DATABASE_DEFAULT_EXCLUDED_GROUPS';
export const DATABASE_DEFAULT_INCLUDED_GROUPS_CONFIG_ID =
  'DATABASE_DEFAULT_INCLUDED_GROUPS';
export const DATABASE_FEATURED_GROUPS_CONFIG_ID = 'DATABASE_FEATURED_GROUPS';
export const DATABASE_AUTO_ADD_NEW_GROUPS_TO_DEFAULT_INCLUDED_GROUPS_CONFIG_ID =
  'DATABASE_AUTO_ADD_NEW_GROUPS_TO_DEFAULT_INCLUDED_GROUPS';
export const ENABLE_GUEST_SELF_JOIN_FROM_WORKSPACE_USER_EMAIL_CONFIG_ID =
  'ENABLE_GUEST_SELF_JOIN_FROM_WORKSPACE_USER_EMAIL';
export const ENABLE_CMS_GAMES_CONFIG_ID = 'ENABLE_CMS_GAMES';
export const ATTENDANCE_COUNT_MANAGERS_CONFIG_ID = 'ATTENDANCE_COUNT_MANAGERS';
export const ATTENDANCE_SHOW_MANAGERS_CONFIG_ID = 'ATTENDANCE_SHOW_MANAGERS';
