begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(37);
create function public.im_id(n integer) returns uuid language sql immutable as $$select ('00009000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into auth.users(id) values(im_id(1));
insert into public.users(id) values(im_id(1)) on conflict do nothing;
insert into public.workspaces(id,name,personal,creator_id) values(im_id(10),'Synthetic merge',false,im_id(1)),(im_id(11),'Other workspace',false,im_id(1));
insert into public.workspace_members(ws_id,user_id,type) values(im_id(10),im_id(1),'MEMBER') on conflict do nothing;
insert into public.workspace_users(id,ws_id,full_name) values(im_id(90),im_id(10),'Synthetic merge actor');
insert into private.inventory_owners(id,ws_id,name) values(im_id(20),im_id(10),'Owner');
insert into private.inventory_units(id,ws_id,name) values(im_id(21),im_id(10),'Each'),(im_id(22),im_id(10),'Box');
insert into private.inventory_warehouses(id,ws_id,name) values(im_id(30),im_id(10),'Source warehouse'),(im_id(31),im_id(10),'Target warehouse'),(im_id(32),im_id(11),'Other');
insert into public.product_categories(id,ws_id,name) values(im_id(40),im_id(10),'Category');
insert into public.workspace_products(id,ws_id,name,owner_id,category_id) values
 (im_id(50),im_id(10),'Source product',im_id(20),im_id(40)),(im_id(51),im_id(10),'Target product',im_id(20),im_id(40)),
 (im_id(52),im_id(10),'Third product',im_id(20),im_id(40));
insert into private.inventory_products(product_id,warehouse_id,unit_id,amount,price,min_amount) values
 (im_id(50),im_id(30),im_id(21),3,100,1),(im_id(51),im_id(30),im_id(21),7,200,2),
 (im_id(50),im_id(30),im_id(22),2,500,0);
insert into public.product_stock_changes(id,product_id,warehouse_id,unit_id,amount,creator_id) values(im_id(60),im_id(50),im_id(30),im_id(21),3,im_id(90));
create temporary table merge_preview as select private.preview_inventory_merge(im_id(10),'product',im_id(50),im_id(51)) as data;
select is(jsonb_array_length((select data->'stock' from merge_preview)),2,'Distinct unit structures are retained');
select ok((select data->'stock' @> '[{"conflict":true}]'::jsonb from merge_preview),'Different prices require explicit policy choice');
select is(jsonb_array_length((select data->'blockers' from merge_preview)),0,'Different unit structures are mergeable without conversion');
select throws_ok($$select private.preview_inventory_merge(im_id(10),'warehouse',im_id(30),im_id(32))$$,'23503',null,'Cross-workspace merge rejected');
select throws_ok($$select private.apply_inventory_merge(im_id(10),'product',im_id(50),im_id(51),'stale','target','target',im_id(1))$$,'23P01',null,'Stale preview cannot mutate stock');
select is((select amount from private.inventory_products where product_id=im_id(50) and unit_id=im_id(21)),3::bigint,'Stale merge rolled back');
update private.inventory_products set price=101 where product_id=im_id(50) and unit_id=im_id(21);
select throws_ok($$select private.apply_inventory_merge(im_id(10),'product',im_id(50),im_id(51),(select data->>'version' from merge_preview),'source','target',im_id(1))$$,'23P01',null,'Actual intervening stock change invalidates original preview');
select is((select amount from private.inventory_products where product_id=im_id(51) and unit_id=im_id(21)),7::bigint,'Concurrent change rejection leaves destination intact');
update private.inventory_products set price=100 where product_id=im_id(50) and unit_id=im_id(21);
select lives_ok($$select private.apply_inventory_merge(im_id(10),'product',im_id(50),im_id(51),(select data->>'version' from merge_preview),'source','target',im_id(1))$$,'Atomic product merge succeeds');
select is((select amount from private.inventory_products where product_id=im_id(51) and unit_id=im_id(21)),10::bigint,'Finite quantities add exactly');
select is((select price from private.inventory_products where product_id=im_id(51) and unit_id=im_id(21)),200::numeric,'Explicit target price policy honored');
select is((select amount from private.inventory_products where product_id=im_id(51) and unit_id=im_id(22)),2::bigint,'Different unit kept independently');
select is((select name from public.workspace_products where id=im_id(51)),'Source product','Explicit source metadata policy honored');
select ok((select archived from public.workspace_products where id=im_id(50)),'Durable source product archived');
select is((select product_id from public.product_stock_changes where id=im_id(60)),im_id(50),'Movement history retains original source identity');
select is((private.apply_inventory_merge(im_id(10),'product',im_id(50),im_id(51),(select data->>'version' from merge_preview),'source','target',im_id(1))->>'replayed')::boolean,true,'Same merge decision replay is idempotent');
select is((select amount from private.inventory_products where product_id=im_id(51) and unit_id=im_id(21)),10::bigint,'Replay does not double quantity');
select throws_ok($$insert into private.inventory_products(product_id,warehouse_id,unit_id,amount) values(im_id(50),im_id(31),im_id(21),1)$$,'23514',null,'Stale offline stock identity cannot reappear');
select throws_ok($$update public.workspace_products set archived=false where id=im_id(50)$$,'23514',null,'Stale source metadata update cannot unarchive alias');
select throws_ok($$delete from public.workspace_products where id=im_id(50)$$,'23514',null,'Durable source history cannot be cascaded away');
insert into private.inventory_products(product_id,warehouse_id,unit_id,amount,price) values(im_id(51),im_id(31),im_id(21),5,200);
create temporary table warehouse_preview as select private.preview_inventory_merge(im_id(10),'warehouse',im_id(30),im_id(31)) as data;
select lives_ok($$select private.apply_inventory_merge(im_id(10),'warehouse',im_id(30),im_id(31),(select data->>'version' from warehouse_preview),'target','target',im_id(1))$$,'Warehouse merge succeeds');
select is((select amount from private.inventory_products where product_id=im_id(51) and warehouse_id=im_id(31) and unit_id=im_id(21)),15::bigint,'Warehouse stock combines');
select is((select warehouse_id from public.product_stock_changes where id=im_id(60)),im_id(30),'Warehouse history keeps source identity');
select ok(not(private.get_inventory_product_form_options(im_id(10))->'warehouses' @> jsonb_build_array(jsonb_build_object('id',im_id(30)))),'Warehouse alias hidden from new choices');
select throws_ok($$insert into private.inventory_products(product_id,warehouse_id,unit_id,amount) values(im_id(52),im_id(30),im_id(21),1)$$,'23514',null,'Stale warehouse writes reject atomically');
insert into private.inventory_products(product_id,warehouse_id,unit_id,amount,price) values(im_id(52),im_id(31),im_id(21),null,200);
select ok(private.preview_inventory_merge(im_id(10),'product',im_id(52),im_id(51))->'blockers' ? 'mixed_unlimited_stock','Mixed finite/unlimited quantity requires resolution');
select throws_ok($$select private.apply_inventory_merge(im_id(10),'product',im_id(52),im_id(51),(private.preview_inventory_merge(im_id(10),'product',im_id(52),im_id(51))->>'version'),'target','target',im_id(1))$$,'23514',null,'Blocked quantity merge preserves all data');
update private.inventory_products set amount=1 where product_id=im_id(52);
insert into private.inventory_storefronts(id,ws_id,slug,name) values(im_id(80),im_id(10),'synthetic-merge','Synthetic');
insert into private.inventory_checkout_sessions(id,ws_id,storefront_id,customer_name,customer_email,expires_at) values(im_id(81),im_id(10),im_id(80),'Synthetic','synthetic@example.invalid',now()+interval '1 hour');
insert into private.inventory_checkout_lines(id,checkout_session_id,product_id,warehouse_id,unit_id,title,quantity) values(im_id(82),im_id(81),im_id(52),im_id(31),im_id(21),'Synthetic',1);
select ok(private.preview_inventory_merge(im_id(10),'product',im_id(52),im_id(51))->'blockers' ? 'active_reservations','Pending checkout prevents stranding a payable cart');
update private.inventory_checkout_sessions set status='cancelled' where id=im_id(81);
select ok(not(private.preview_inventory_merge(im_id(10),'product',im_id(52),im_id(51))->'blockers' ? 'active_reservations'),'Terminal checkout snapshot retained without blocking new merge');
create table public.inventory_merge_provider_fixture(id uuid primary key,product_id uuid not null references public.workspace_products(id),unit_id uuid not null,unique(product_id,unit_id));
create trigger inventory_identity_writer before insert or update or delete on public.inventory_merge_provider_fixture for each row execute function private.coordinate_inventory_identity_writer();
create trigger inventory_merged_reference_guard before insert or update on public.inventory_merge_provider_fixture for each row execute function private.reject_merged_inventory_reference();
insert into public.inventory_merge_provider_fixture values(im_id(70),im_id(52),im_id(21)),(im_id(71),im_id(51),im_id(21));
select ok(private.preview_inventory_merge(im_id(10),'product',im_id(52),im_id(51))->'blockers' ? 'duplicate_reference:inventory_merge_provider_fixture','Duplicate live identities are named in preview');
select throws_ok($$select private.apply_inventory_merge(im_id(10),'product',im_id(52),im_id(51),(private.preview_inventory_merge(im_id(10),'product',im_id(52),im_id(51))->>'version'),'target','target',im_id(1))$$,'23514',null,'Provider identity conflict cannot discard mappings');
select is((select count(*) from public.inventory_merge_provider_fixture),2::bigint,'All conflicting provider records retained');
select ok(not has_function_privilege('authenticated','private.apply_inventory_merge(uuid,text,uuid,uuid,text,text,text,uuid)','EXECUTE'),'Direct authenticated RPC execution forbidden');
select ok(not has_function_privilege('anon','private.preview_inventory_merge(uuid,text,uuid,uuid)','EXECUTE'),'Anonymous preview execution forbidden');
select throws_ok($$delete from private.inventory_warehouses where id=im_id(31)$$,'23514',null,'Destination with durable merge identity cannot be deleted');
select is((select count(*) from private.inventory_audit_logs where summary='Merged inventory identity into destination'),2::bigint,'Successful merges each record one transactional audit event');
drop table public.inventory_merge_provider_fixture;
delete from private.inventory_checkout_sessions where id=im_id(81);
select lives_ok($$delete from public.workspaces where id=im_id(10)$$,'Owning workspace deletion can remove its merge aliases');
select * from finish();
rollback;
