begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(8);
select is((select file_size_limit from storage.buckets where id='avatars'),2097152::bigint,'avatar uploads are capped at two MiB by Storage');
select is((select file_size_limit from storage.buckets where id='banners'),5242880::bigint,'banner uploads are capped at five MiB by Storage');
select ok((select allowed_mime_types=ARRAY['image/png','image/jpeg','image/webp','image/gif'] from storage.buckets where id='avatars'),'avatars exclude executable SVG');
select ok((select allowed_mime_types=ARRAY['image/png','image/jpeg','image/webp','image/gif'] from storage.buckets where id='banners'),'banners exclude executable SVG');
select ok((select public from storage.buckets where id='banners'),'canonical banners use public identity semantics');
select is((select permissive from pg_policies where schemaname='storage' and tablename='objects' and policyname='profile_media_require_budgeted_insert'),'RESTRICTIVE','raw upload restriction composes with broad legacy insert policies');
set local role authenticated;
select throws_ok($$insert into storage.objects(bucket_id,name) values('avatars','synthetic-bypass.png')$$,'42501',null,'authenticated clients cannot bypass avatar ticket quotas');
select throws_ok($$insert into storage.objects(bucket_id,name) values('banners','synthetic-bypass.png')$$,'42501',null,'authenticated clients cannot bypass banner ticket quotas');
reset role;
select * from finish();
rollback;
