begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(8);
select is((select file_size_limit from storage.buckets where id='avatars'),1000000::bigint,'avatar uploads are capped at one MB after optimization by Storage');
select is((select file_size_limit from storage.buckets where id='banners'),2000000::bigint,'banner uploads are capped at two MB after optimization by Storage');
select ok((select allowed_mime_types=ARRAY['image/webp'] from storage.buckets where id='avatars'),'avatars accept optimized WebP only');
select ok((select allowed_mime_types=ARRAY['image/webp'] from storage.buckets where id='banners'),'banners accept optimized WebP only');
select ok((select public from storage.buckets where id='banners'),'canonical banners use public identity semantics');
select is((select permissive from pg_policies where schemaname='storage' and tablename='objects' and policyname='profile_media_require_budgeted_insert'),'RESTRICTIVE','raw upload restriction composes with broad legacy insert policies');
set local role authenticated;
select throws_ok($$insert into storage.objects(bucket_id,name) values('avatars','synthetic-bypass.png')$$,'42501',null,'authenticated clients cannot bypass avatar ticket quotas');
select throws_ok($$insert into storage.objects(bucket_id,name) values('banners','synthetic-bypass.png')$$,'42501',null,'authenticated clients cannot bypass banner ticket quotas');
reset role;
select * from finish();
rollback;
