import type { ComparisonFeature } from './commercial-comparison-types';
export const features2: ComparisonFeature[] = [
  {
    id: 'lettin_0',
    app: 'lettin',
    category: 'learning',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'colab_0',
    app: 'colab',
    category: 'learning',
    values: ['included', 'included', 'included', 'included'],
    detail: 'ai',
  },
  {
    id: 'colab_1',
    app: 'colab',
    category: 'learning',
    values: ['included', 'included', 'included', 'included'],
    detail: 'ai',
  },
  {
    id: 'colab_2',
    app: 'colab',
    category: 'learning',
    values: ['included', 'included', 'included', 'included'],
    detail: 'ai',
  },
  {
    id: 'colab_3',
    app: 'colab',
    category: 'learning',
    values: ['included', 'included', 'included', 'included'],
    detail: 'ai',
  },
  {
    id: 'learn_0',
    app: 'learn',
    category: 'learning',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'teach_0',
    app: 'teach',
    category: 'learning',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'rewise_0',
    app: 'rewise',
    category: 'learning',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'nova_0',
    app: 'nova',
    category: 'learning',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'git_0',
    app: 'git',
    category: 'developer',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'git_1',
    app: 'git',
    category: 'developer',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'git_2',
    app: 'git',
    category: 'developer',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'external_0',
    app: 'external',
    category: 'developer',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'external_1',
    app: 'external',
    category: 'developer',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'mobile_0',
    app: 'mobile',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'mobile_1',
    app: 'mobile',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'pay_0',
    app: 'pay',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'pay_1',
    app: 'pay',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'pay_2',
    app: 'pay',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'apps_0',
    app: 'apps',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'tools_0',
    app: 'tools',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'shortener_0',
    app: 'shortener',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'storefront_0',
    app: 'storefront',
    category: 'operations',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'playground_0',
    app: 'playground',
    category: 'developer',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'discord_0',
    app: 'discord',
    category: 'developer',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'docs_0',
    app: 'docs',
    category: 'developer',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'backend_0',
    app: 'backend',
    category: 'internal',
    values: ['internal', 'internal', 'internal', 'internal'],
    detail: 'standard',
  },
  {
    id: 'database_0',
    app: 'database',
    category: 'internal',
    values: ['internal', 'internal', 'internal', 'internal'],
    detail: 'standard',
  },
  {
    id: 'redis_0',
    app: 'redis',
    category: 'internal',
    values: ['internal', 'internal', 'internal', 'internal'],
    detail: 'standard',
  },
  {
    id: 'supermemory_0',
    app: 'supermemory',
    category: 'internal',
    values: ['internal', 'internal', 'internal', 'internal'],
    detail: 'standard',
  },
  {
    id: 'storage-unzip-proxy_0',
    app: 'storage-unzip-proxy',
    category: 'internal',
    values: ['internal', 'internal', 'internal', 'internal'],
    detail: 'standard',
  },
  {
    id: 'chat-realtime_0',
    app: 'chat-realtime',
    category: 'internal',
    values: ['internal', 'internal', 'internal', 'internal'],
    detail: 'standard',
  },
  {
    id: 'meet-realtime_0',
    app: 'meet-realtime',
    category: 'internal',
    values: ['internal', 'internal', 'internal', 'internal'],
    detail: 'standard',
  },
  {
    id: 'hive-realtime_0',
    app: 'hive-realtime',
    category: 'internal',
    values: ['internal', 'internal', 'internal', 'internal'],
    detail: 'standard',
  },
  {
    id: 'tanstack-web_0',
    app: 'tanstack-web',
    category: 'internal',
    values: ['internal', 'internal', 'internal', 'internal'],
    detail: 'standard',
  },
  {
    id: 'infrastructure_0',
    app: 'infrastructure',
    category: 'internal',
    values: ['internal', 'internal', 'internal', 'internal'],
    detail: 'standard',
  },
];
