import type { ComparisonFeature } from './commercial-comparison-types';
export const features1: ComparisonFeature[] = [
  {
    id: 'meet_4',
    app: 'meet',
    category: 'work',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'contacts_0',
    app: 'contacts',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'contacts_1',
    app: 'contacts',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'contacts_2',
    app: 'contacts',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'contacts_3',
    app: 'contacts',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'contacts_4',
    app: 'contacts',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'contacts_5',
    app: 'contacts',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'contacts_6',
    app: 'contacts',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'finance_0',
    app: 'finance',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'finance_1',
    app: 'finance',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'finance_2',
    app: 'finance',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'finance_3',
    app: 'finance',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'finance_4',
    app: 'finance',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'finance_5',
    app: 'finance',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'finance_6',
    app: 'finance',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'inventory_0',
    app: 'inventory',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'inventory_1',
    app: 'inventory',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'forms_0',
    app: 'forms',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'forms_1',
    app: 'forms',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'forms_2',
    app: 'forms',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'forms_3',
    app: 'forms',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'cms_0',
    app: 'cms',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'cms_1',
    app: 'cms',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'cms_2',
    app: 'cms',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'cms_3',
    app: 'cms',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'cms_4',
    app: 'cms',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'cms_5',
    app: 'cms',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'cms_6',
    app: 'cms',
    category: 'operations',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'mail_0',
    app: 'mail',
    category: 'operations',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'mail_1',
    app: 'mail',
    category: 'operations',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'mail_2',
    app: 'mail',
    category: 'operations',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'ai_0',
    app: 'ai',
    category: 'ai',
    values: ['included', 'included', 'included', 'included'],
    detail: 'ai',
  },
  {
    id: 'ai_1',
    app: 'ai',
    category: 'ai',
    values: ['included', 'included', 'included', 'included'],
    detail: 'ai',
  },
  {
    id: 'ai_2',
    app: 'ai',
    category: 'ai',
    values: ['included', 'included', 'included', 'included'],
    detail: 'ai',
  },
  {
    id: 'ai_3',
    app: 'ai',
    category: 'ai',
    values: ['included', 'included', 'included', 'included'],
    detail: 'ai',
  },
  {
    id: 'ai_4',
    app: 'ai',
    category: 'ai',
    values: ['included', 'included', 'included', 'included'],
    detail: 'ai',
  },
  {
    id: 'ai_5',
    app: 'ai',
    category: 'ai',
    values: ['included', 'included', 'included', 'included'],
    detail: 'ai',
  },
  {
    id: 'mind_0',
    app: 'mind',
    category: 'ai',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'ai',
  },
  {
    id: 'hive_0',
    app: 'hive',
    category: 'ai',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'ai',
  },
  {
    id: 'hive_1',
    app: 'hive',
    category: 'ai',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'ai',
  },
];
