import type { ComparisonFeature } from './commercial-comparison-types';
export const features0: ComparisonFeature[] = [
  {
    id: 'attachments',
    app: 'capacity',
    category: 'capacity',
    values: ['10', '10', '10', '10'],
    detail: 'attachment',
    pending: false,
  },
  {
    id: 'publishers',
    app: 'capacity',
    category: 'capacity',
    values: ['8 / 96', '8 / 96', '8 / 96', '8 / 96'],
    detail: 'meetSafety',
    pending: false,
  },
  {
    id: 'duration',
    app: 'capacity',
    category: 'capacity',
    values: ['2 h', '2 h', '2 h', '2 h'],
    detail: 'meetSafety',
    pending: false,
  },
  {
    id: 'workspaces',
    app: 'capacity',
    category: 'capacity',
    values: ['10', '10', '10', '10'],
    detail: 'account',
    pending: false,
  },
  {
    id: 'board',
    app: 'capacity',
    category: 'capacity',
    values: ['10', '50', '50', 'contract'],
    detail: 'board',
    pending: false,
  },
  {
    id: 'responses',
    app: 'capacity',
    category: 'capacity',
    values: ['100', '1,000', '5,000', 'contract'],
    detail: 'monthlyAllowance',
    pending: true,
  },
  {
    id: 'automation',
    app: 'capacity',
    category: 'capacity',
    values: ['100', '1,000', '5,000', 'contract'],
    detail: 'monthlyAllowance',
    pending: true,
  },
  {
    id: 'aiCredits',
    app: 'capacity',
    category: 'capacity',
    values: ['1,000', '10,000', '30,000', 'contract'],
    detail: 'aiAllowance',
    pending: true,
  },
  {
    id: 'storage',
    app: 'capacity',
    category: 'capacity',
    values: ['1 GiB', '20 GiB', '100 GiB', 'contract'],
    detail: 'storageAllowance',
    pending: true,
  },
  {
    id: 'guests',
    app: 'capacity',
    category: 'capacity',
    values: ['10', '50', '250', 'contract'],
    detail: 'guests',
    pending: true,
  },
  {
    id: 'members',
    app: 'capacity',
    category: 'capacity',
    values: ['5', 'seats', 'seats', 'contract'],
    detail: 'members',
    pending: true,
  },
  {
    id: 'platform_0',
    app: 'platform',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'platform_1',
    app: 'platform',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'platform_2',
    app: 'platform',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'platform_3',
    app: 'platform',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'platform_4',
    app: 'platform',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'platform_5',
    app: 'platform',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'tasks_0',
    app: 'tasks',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'tasks_1',
    app: 'tasks',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'tasks_2',
    app: 'tasks',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'tasks_3',
    app: 'tasks',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'tasks_4',
    app: 'tasks',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'calendar_0',
    app: 'calendar',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'calendar_1',
    app: 'calendar',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'calendar_2',
    app: 'calendar',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'track_0',
    app: 'track',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'track_1',
    app: 'track',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'track_2',
    app: 'track',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'track_3',
    app: 'track',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'standard',
  },
  {
    id: 'drive_0',
    app: 'drive',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'drive_1',
    app: 'drive',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'drive_2',
    app: 'drive',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'drive_3',
    app: 'drive',
    category: 'work',
    values: ['included', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'chat_0',
    app: 'chat',
    category: 'work',
    values: ['excluded', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'chat_1',
    app: 'chat',
    category: 'work',
    values: ['excluded', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'chat_2',
    app: 'chat',
    category: 'work',
    values: ['excluded', 'included', 'included', 'included'],
    detail: 'storage',
  },
  {
    id: 'meet_0',
    app: 'meet',
    category: 'work',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'meet_1',
    app: 'meet',
    category: 'work',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'meet_2',
    app: 'meet',
    category: 'work',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
  {
    id: 'meet_3',
    app: 'meet',
    category: 'work',
    values: ['preview', 'preview', 'preview', 'preview'],
    detail: 'standard',
  },
];
