// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import {
  createLegacyGetHandler,
  createLegacyHeadHandler,
} from '@/legacy-api-routes/head';
import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/time-tracking/sessions/[sessionId]/route';

export const GET = createLegacyGetHandler(legacyRoute.GET);
export const HEAD = createLegacyHeadHandler(GET);
export const PATCH = legacyRoute.PATCH;
export const DELETE = legacyRoute.DELETE;
