/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 76467ed442704f7bc54e35e45644d8c1)
interface __BaseEnv_CloudflareEnv {
  NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
  IMAGES: ImagesBinding;
  ASSETS: Fetcher;
  NEXT_PUBLIC_APP_URL: 'https://meet.tuturuuu.com';
  NEXT_PUBLIC_WEB_APP_URL: 'https://tuturuuu.com';
  MEET_REALTIME_URL: 'wss://meet-realtime.tuturuuu.com/realtime';
  MEET_REALTIME_TOKEN_SECRET: string;
  NEXT_PUBLIC_SUPABASE_URL: string;
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
  SUPABASE_SECRET_KEY: string;
  WORKER_SELF_REFERENCE: Service<typeof import('./.open-next/worker').default>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./.open-next/worker');
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | 'NEXT_PUBLIC_APP_URL'
        | 'NEXT_PUBLIC_WEB_APP_URL'
        | 'MEET_REALTIME_URL'
        | 'MEET_REALTIME_TOKEN_SECRET'
        | 'NEXT_PUBLIC_SUPABASE_URL'
        | 'NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY'
        | 'SUPABASE_SECRET_KEY'
      >
    > {}
}
