// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/auth/mfa/totp/factors/[factorId]/verify/route';

export const POST = legacyRoute.POST;
