// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/external-projects/webgl-packages/finalize/route';

export const POST = legacyRoute.POST;
