// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/auth/cross-app-return/route';

export const POST = legacyRoute.POST;
