/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char126offlineRouteImport } from './routes/~offline'
import { Route as QrGeneratorRouteImport } from './routes/qr-generator'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as ProductsMeetTogetherRouteImport } from './routes/products/meet-together'
import { Route as LocaleWomenInTechRouteImport } from './routes/$locale/women-in-tech'
import { Route as LocaleVerifyTokenRouteImport } from './routes/$locale/verify-token'
import { Route as LocaleTermsRouteImport } from './routes/$locale/terms'
import { Route as LocaleSecurityRouteImport } from './routes/$locale/security'
import { Route as LocaleQrGeneratorRouteImport } from './routes/$locale/qr-generator'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocalePricingRouteImport } from './routes/$locale/pricing'
import { Route as LocalePartnersRouteImport } from './routes/$locale/partners'
import { Route as LocaleMeetTogetherRouteImport } from './routes/$locale/meet-together'
import { Route as LocaleFacebookMockupRouteImport } from './routes/$locale/facebook-mockup'
import { Route as LocaleDocsRouteImport } from './routes/$locale/docs'
import { Route as LocaleContributorsRouteImport } from './routes/$locale/contributors'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocaleCommunityGuidelinesRouteImport } from './routes/$locale/community-guidelines'
import { Route as LocaleCareersRouteImport } from './routes/$locale/careers'
import { Route as LocaleBrandingRouteImport } from './routes/$locale/branding'
import { Route as LocaleBlogRouteImport } from './routes/$locale/blog'
import { Route as LocaleAcceptableUseRouteImport } from './routes/$locale/acceptable-use'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleUiIndexRouteImport } from './routes/$locale/ui/index'
import { Route as LocaleVisualizationsHorseRacingRouteImport } from './routes/$locale/visualizations/horse-racing'
import { Route as LocaleUiSetupRouteImport } from './routes/$locale/ui/setup'
import { Route as LocaleUiContributingRouteImport } from './routes/$locale/ui/contributing'
import { Route as LocaleSolutionsRetailRouteImport } from './routes/$locale/solutions/retail'
import { Route as LocaleSolutionsRestaurantsRouteImport } from './routes/$locale/solutions/restaurants'
import { Route as LocaleSolutionsRealestateRouteImport } from './routes/$locale/solutions/realestate'
import { Route as LocaleSolutionsPharmaciesRouteImport } from './routes/$locale/solutions/pharmacies'
import { Route as LocaleSolutionsManufacturingRouteImport } from './routes/$locale/solutions/manufacturing'
import { Route as LocaleSolutionsHospitalityRouteImport } from './routes/$locale/solutions/hospitality'
import { Route as LocaleSolutionsHealthcareRouteImport } from './routes/$locale/solutions/healthcare'
import { Route as LocaleSolutionsEducationRouteImport } from './routes/$locale/solutions/education'
import { Route as LocaleSolutionsConstructionRouteImport } from './routes/$locale/solutions/construction'
import { Route as LocaleSecurityPolicyRouteImport } from './routes/$locale/security/policy'
import { Route as LocaleSecurityBugBountyRouteImport } from './routes/$locale/security/bug-bounty'
import { Route as LocaleProductsWorkflowsRouteImport } from './routes/$locale/products/workflows'
import { Route as LocaleProductsTasksRouteImport } from './routes/$locale/products/tasks'
import { Route as LocaleProductsMeetTogetherRouteImport } from './routes/$locale/products/meet-together'
import { Route as LocaleProductsMailRouteImport } from './routes/$locale/products/mail'
import { Route as LocaleProductsLmsRouteImport } from './routes/$locale/products/lms'
import { Route as LocaleProductsInventoryRouteImport } from './routes/$locale/products/inventory'
import { Route as LocaleProductsFinanceRouteImport } from './routes/$locale/products/finance'
import { Route as LocaleProductsDriveRouteImport } from './routes/$locale/products/drive'
import { Route as LocaleProductsDocumentsRouteImport } from './routes/$locale/products/documents'
import { Route as LocaleProductsCrmRouteImport } from './routes/$locale/products/crm'
import { Route as LocaleProductsCalendarRouteImport } from './routes/$locale/products/calendar'
import { Route as LocaleProductsAiRouteImport } from './routes/$locale/products/ai'
import { Route as LocaleCalendarMeetTogetherRouteImport } from './routes/$locale/calendar/meet-together'
import { Route as LocaleWsIdWorkoutsRouteImport } from './routes/$locale/$wsId/workouts'
import { Route as LocaleWsIdWorkforceRouteImport } from './routes/$locale/$wsId/workforce'
import { Route as LocaleWsIdRolesRouteImport } from './routes/$locale/$wsId/roles'
import { Route as LocaleWsIdReadingsRouteImport } from './routes/$locale/$wsId/readings'
import { Route as LocaleWsIdQrGeneratorRouteImport } from './routes/$locale/$wsId/qr-generator'
import { Route as LocaleWsIdProgressRouteImport } from './routes/$locale/$wsId/progress'
import { Route as LocaleWsIdPollsRouteImport } from './routes/$locale/$wsId/polls'
import { Route as LocaleWsIdMetricsRouteImport } from './routes/$locale/$wsId/metrics'
import { Route as LocaleWsIdMeetRouteImport } from './routes/$locale/$wsId/meet'
import { Route as LocaleWsIdIntegrationsRouteImport } from './routes/$locale/$wsId/integrations'
import { Route as LocaleWsIdExternalProjectsRouteImport } from './routes/$locale/$wsId/external-projects'
import { Route as LocaleWsIdEpmRouteImport } from './routes/$locale/$wsId/epm'
import { Route as LocaleWsIdDietRouteImport } from './routes/$locale/$wsId/diet'
import { Route as LocaleUiComponentsIndexRouteImport } from './routes/$locale/ui/components/index'
import { Route as LocaleWsIdMailIndexRouteImport } from './routes/$locale/$wsId/mail/index'
import { Route as LocaleUiComponentsComponentIdRouteImport } from './routes/$locale/ui/components/$componentId'
import { Route as LocaleCalendarMeetTogetherSplatRouteImport } from './routes/$locale/calendar/meet-together/$'
import { Route as LocaleWsIdUsersTopicAnnouncementsRouteImport } from './routes/$locale/$wsId/users/topic-announcements'
import { Route as LocaleWsIdTasksHabitsRouteImport } from './routes/$locale/$wsId/tasks/habits'
import { Route as LocaleWsIdPlatformExternalProjectsRouteImport } from './routes/$locale/$wsId/platform/external-projects'
import { Route as LocaleWsIdMailSentRouteImport } from './routes/$locale/$wsId/mail/sent'
import { Route as LocaleWsIdEducationQuizzesRouteImport } from './routes/$locale/$wsId/education/quizzes'
import { Route as LocaleWsIdEducationQuizSetsRouteImport } from './routes/$locale/$wsId/education/quiz-sets'
import { Route as LocaleWsIdEducationLibraryRouteImport } from './routes/$locale/$wsId/education/library'
import { Route as LocaleWsIdEducationFlashcardsRouteImport } from './routes/$locale/$wsId/education/flashcards'
import { Route as LocaleWsIdAiChatNewRouteImport } from './routes/$locale/$wsId/ai-chat/new'
import { Route as LocaleWsIdUsersReportsReportIdRouteImport } from './routes/$locale/$wsId/users/reports/$reportId'
import { Route as LocaleWsIdUsersGroupsGroupIdRouteImport } from './routes/$locale/$wsId/users/groups/$groupId'
import { Route as LocaleWsIdTasksBoardsBoardIdRouteImport } from './routes/$locale/$wsId/tasks/boards/$boardId'
import { Route as LocaleWsIdSettingsInfrastructureAppCoordinationRouteImport } from './routes/$locale/$wsId/settings/infrastructure/app-coordination'
import { Route as LocaleWsIdFinanceTransactionsCategoriesRouteImport } from './routes/$locale/$wsId/finance/transactions/categories'
import { Route as LocaleWsIdEpmEntriesEntryIdRouteImport } from './routes/$locale/$wsId/epm/entries/$entryId'
import { Route as LocaleWsIdEpmCollectionsCollectionIdRouteImport } from './routes/$locale/$wsId/epm/collections/$collectionId'
import { Route as LocaleWsIdEducationCoursesCourseIdRouteImport } from './routes/$locale/$wsId/education/courses/$courseId'
import { Route as LocaleWsIdAiChatMyChatbotsNewRouteImport } from './routes/$locale/$wsId/ai-chat/my-chatbots/new'

const Char126offlineRoute = Char126offlineRouteImport.update({
  id: '/~offline',
  path: '/~offline',
  getParentRoute: () => rootRouteImport,
} as any)
const QrGeneratorRoute = QrGeneratorRouteImport.update({
  id: '/qr-generator',
  path: '/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsMeetTogetherRoute = ProductsMeetTogetherRouteImport.update({
  id: '/products/meet-together',
  path: '/products/meet-together',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWomenInTechRoute = LocaleWomenInTechRouteImport.update({
  id: '/$locale/women-in-tech',
  path: '/$locale/women-in-tech',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleVerifyTokenRoute = LocaleVerifyTokenRouteImport.update({
  id: '/$locale/verify-token',
  path: '/$locale/verify-token',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/$locale/terms',
  path: '/$locale/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSecurityRoute = LocaleSecurityRouteImport.update({
  id: '/$locale/security',
  path: '/$locale/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleQrGeneratorRoute = LocaleQrGeneratorRouteImport.update({
  id: '/$locale/qr-generator',
  path: '/$locale/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/$locale/privacy',
  path: '/$locale/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePricingRoute = LocalePricingRouteImport.update({
  id: '/$locale/pricing',
  path: '/$locale/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePartnersRoute = LocalePartnersRouteImport.update({
  id: '/$locale/partners',
  path: '/$locale/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleMeetTogetherRoute = LocaleMeetTogetherRouteImport.update({
  id: '/$locale/meet-together',
  path: '/$locale/meet-together',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleFacebookMockupRoute = LocaleFacebookMockupRouteImport.update({
  id: '/$locale/facebook-mockup',
  path: '/$locale/facebook-mockup',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleDocsRoute = LocaleDocsRouteImport.update({
  id: '/$locale/docs',
  path: '/$locale/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleContributorsRoute = LocaleContributorsRouteImport.update({
  id: '/$locale/contributors',
  path: '/$locale/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/$locale/contact',
  path: '/$locale/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCommunityGuidelinesRoute =
  LocaleCommunityGuidelinesRouteImport.update({
    id: '/$locale/community-guidelines',
    path: '/$locale/community-guidelines',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleCareersRoute = LocaleCareersRouteImport.update({
  id: '/$locale/careers',
  path: '/$locale/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBrandingRoute = LocaleBrandingRouteImport.update({
  id: '/$locale/branding',
  path: '/$locale/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogRoute = LocaleBlogRouteImport.update({
  id: '/$locale/blog',
  path: '/$locale/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAcceptableUseRoute = LocaleAcceptableUseRouteImport.update({
  id: '/$locale/acceptable-use',
  path: '/$locale/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/$locale/about',
  path: '/$locale/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleUiIndexRoute = LocaleUiIndexRouteImport.update({
  id: '/$locale/ui/',
  path: '/$locale/ui/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleVisualizationsHorseRacingRoute =
  LocaleVisualizationsHorseRacingRouteImport.update({
    id: '/$locale/visualizations/horse-racing',
    path: '/$locale/visualizations/horse-racing',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleUiSetupRoute = LocaleUiSetupRouteImport.update({
  id: '/$locale/ui/setup',
  path: '/$locale/ui/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleUiContributingRoute = LocaleUiContributingRouteImport.update({
  id: '/$locale/ui/contributing',
  path: '/$locale/ui/contributing',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSolutionsRetailRoute = LocaleSolutionsRetailRouteImport.update({
  id: '/$locale/solutions/retail',
  path: '/$locale/solutions/retail',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSolutionsRestaurantsRoute =
  LocaleSolutionsRestaurantsRouteImport.update({
    id: '/$locale/solutions/restaurants',
    path: '/$locale/solutions/restaurants',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSolutionsRealestateRoute =
  LocaleSolutionsRealestateRouteImport.update({
    id: '/$locale/solutions/realestate',
    path: '/$locale/solutions/realestate',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSolutionsPharmaciesRoute =
  LocaleSolutionsPharmaciesRouteImport.update({
    id: '/$locale/solutions/pharmacies',
    path: '/$locale/solutions/pharmacies',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSolutionsManufacturingRoute =
  LocaleSolutionsManufacturingRouteImport.update({
    id: '/$locale/solutions/manufacturing',
    path: '/$locale/solutions/manufacturing',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSolutionsHospitalityRoute =
  LocaleSolutionsHospitalityRouteImport.update({
    id: '/$locale/solutions/hospitality',
    path: '/$locale/solutions/hospitality',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSolutionsHealthcareRoute =
  LocaleSolutionsHealthcareRouteImport.update({
    id: '/$locale/solutions/healthcare',
    path: '/$locale/solutions/healthcare',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSolutionsEducationRoute =
  LocaleSolutionsEducationRouteImport.update({
    id: '/$locale/solutions/education',
    path: '/$locale/solutions/education',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSolutionsConstructionRoute =
  LocaleSolutionsConstructionRouteImport.update({
    id: '/$locale/solutions/construction',
    path: '/$locale/solutions/construction',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSecurityPolicyRoute = LocaleSecurityPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => LocaleSecurityRoute,
} as any)
const LocaleSecurityBugBountyRoute = LocaleSecurityBugBountyRouteImport.update({
  id: '/bug-bounty',
  path: '/bug-bounty',
  getParentRoute: () => LocaleSecurityRoute,
} as any)
const LocaleProductsWorkflowsRoute = LocaleProductsWorkflowsRouteImport.update({
  id: '/$locale/products/workflows',
  path: '/$locale/products/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProductsTasksRoute = LocaleProductsTasksRouteImport.update({
  id: '/$locale/products/tasks',
  path: '/$locale/products/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProductsMeetTogetherRoute =
  LocaleProductsMeetTogetherRouteImport.update({
    id: '/$locale/products/meet-together',
    path: '/$locale/products/meet-together',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleProductsMailRoute = LocaleProductsMailRouteImport.update({
  id: '/$locale/products/mail',
  path: '/$locale/products/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProductsLmsRoute = LocaleProductsLmsRouteImport.update({
  id: '/$locale/products/lms',
  path: '/$locale/products/lms',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProductsInventoryRoute = LocaleProductsInventoryRouteImport.update({
  id: '/$locale/products/inventory',
  path: '/$locale/products/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProductsFinanceRoute = LocaleProductsFinanceRouteImport.update({
  id: '/$locale/products/finance',
  path: '/$locale/products/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProductsDriveRoute = LocaleProductsDriveRouteImport.update({
  id: '/$locale/products/drive',
  path: '/$locale/products/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProductsDocumentsRoute = LocaleProductsDocumentsRouteImport.update({
  id: '/$locale/products/documents',
  path: '/$locale/products/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProductsCrmRoute = LocaleProductsCrmRouteImport.update({
  id: '/$locale/products/crm',
  path: '/$locale/products/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProductsCalendarRoute = LocaleProductsCalendarRouteImport.update({
  id: '/$locale/products/calendar',
  path: '/$locale/products/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProductsAiRoute = LocaleProductsAiRouteImport.update({
  id: '/$locale/products/ai',
  path: '/$locale/products/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCalendarMeetTogetherRoute =
  LocaleCalendarMeetTogetherRouteImport.update({
    id: '/$locale/calendar/meet-together',
    path: '/$locale/calendar/meet-together',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWsIdWorkoutsRoute = LocaleWsIdWorkoutsRouteImport.update({
  id: '/$locale/$wsId/workouts',
  path: '/$locale/$wsId/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdWorkforceRoute = LocaleWsIdWorkforceRouteImport.update({
  id: '/$locale/$wsId/workforce',
  path: '/$locale/$wsId/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdRolesRoute = LocaleWsIdRolesRouteImport.update({
  id: '/$locale/$wsId/roles',
  path: '/$locale/$wsId/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdReadingsRoute = LocaleWsIdReadingsRouteImport.update({
  id: '/$locale/$wsId/readings',
  path: '/$locale/$wsId/readings',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdQrGeneratorRoute = LocaleWsIdQrGeneratorRouteImport.update({
  id: '/$locale/$wsId/qr-generator',
  path: '/$locale/$wsId/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdProgressRoute = LocaleWsIdProgressRouteImport.update({
  id: '/$locale/$wsId/progress',
  path: '/$locale/$wsId/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdPollsRoute = LocaleWsIdPollsRouteImport.update({
  id: '/$locale/$wsId/polls',
  path: '/$locale/$wsId/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdMetricsRoute = LocaleWsIdMetricsRouteImport.update({
  id: '/$locale/$wsId/metrics',
  path: '/$locale/$wsId/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdMeetRoute = LocaleWsIdMeetRouteImport.update({
  id: '/$locale/$wsId/meet',
  path: '/$locale/$wsId/meet',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdIntegrationsRoute = LocaleWsIdIntegrationsRouteImport.update({
  id: '/$locale/$wsId/integrations',
  path: '/$locale/$wsId/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdExternalProjectsRoute =
  LocaleWsIdExternalProjectsRouteImport.update({
    id: '/$locale/$wsId/external-projects',
    path: '/$locale/$wsId/external-projects',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWsIdEpmRoute = LocaleWsIdEpmRouteImport.update({
  id: '/$locale/$wsId/epm',
  path: '/$locale/$wsId/epm',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdDietRoute = LocaleWsIdDietRouteImport.update({
  id: '/$locale/$wsId/diet',
  path: '/$locale/$wsId/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleUiComponentsIndexRoute = LocaleUiComponentsIndexRouteImport.update({
  id: '/$locale/ui/components/',
  path: '/$locale/ui/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdMailIndexRoute = LocaleWsIdMailIndexRouteImport.update({
  id: '/$locale/$wsId/mail/',
  path: '/$locale/$wsId/mail/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleUiComponentsComponentIdRoute =
  LocaleUiComponentsComponentIdRouteImport.update({
    id: '/$locale/ui/components/$componentId',
    path: '/$locale/ui/components/$componentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleCalendarMeetTogetherSplatRoute =
  LocaleCalendarMeetTogetherSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => LocaleCalendarMeetTogetherRoute,
  } as any)
const LocaleWsIdUsersTopicAnnouncementsRoute =
  LocaleWsIdUsersTopicAnnouncementsRouteImport.update({
    id: '/$locale/$wsId/users/topic-announcements',
    path: '/$locale/$wsId/users/topic-announcements',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWsIdTasksHabitsRoute = LocaleWsIdTasksHabitsRouteImport.update({
  id: '/$locale/$wsId/tasks/habits',
  path: '/$locale/$wsId/tasks/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdPlatformExternalProjectsRoute =
  LocaleWsIdPlatformExternalProjectsRouteImport.update({
    id: '/$locale/$wsId/platform/external-projects',
    path: '/$locale/$wsId/platform/external-projects',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWsIdMailSentRoute = LocaleWsIdMailSentRouteImport.update({
  id: '/$locale/$wsId/mail/sent',
  path: '/$locale/$wsId/mail/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdEducationQuizzesRoute =
  LocaleWsIdEducationQuizzesRouteImport.update({
    id: '/$locale/$wsId/education/quizzes',
    path: '/$locale/$wsId/education/quizzes',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWsIdEducationQuizSetsRoute =
  LocaleWsIdEducationQuizSetsRouteImport.update({
    id: '/$locale/$wsId/education/quiz-sets',
    path: '/$locale/$wsId/education/quiz-sets',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWsIdEducationLibraryRoute =
  LocaleWsIdEducationLibraryRouteImport.update({
    id: '/$locale/$wsId/education/library',
    path: '/$locale/$wsId/education/library',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWsIdEducationFlashcardsRoute =
  LocaleWsIdEducationFlashcardsRouteImport.update({
    id: '/$locale/$wsId/education/flashcards',
    path: '/$locale/$wsId/education/flashcards',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWsIdAiChatNewRoute = LocaleWsIdAiChatNewRouteImport.update({
  id: '/$locale/$wsId/ai-chat/new',
  path: '/$locale/$wsId/ai-chat/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWsIdUsersReportsReportIdRoute =
  LocaleWsIdUsersReportsReportIdRouteImport.update({
    id: '/$locale/$wsId/users/reports/$reportId',
    path: '/$locale/$wsId/users/reports/$reportId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWsIdUsersGroupsGroupIdRoute =
  LocaleWsIdUsersGroupsGroupIdRouteImport.update({
    id: '/$locale/$wsId/users/groups/$groupId',
    path: '/$locale/$wsId/users/groups/$groupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWsIdTasksBoardsBoardIdRoute =
  LocaleWsIdTasksBoardsBoardIdRouteImport.update({
    id: '/$locale/$wsId/tasks/boards/$boardId',
    path: '/$locale/$wsId/tasks/boards/$boardId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWsIdSettingsInfrastructureAppCoordinationRoute =
  LocaleWsIdSettingsInfrastructureAppCoordinationRouteImport.update({
    id: '/$locale/$wsId/settings/infrastructure/app-coordination',
    path: '/$locale/$wsId/settings/infrastructure/app-coordination',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWsIdFinanceTransactionsCategoriesRoute =
  LocaleWsIdFinanceTransactionsCategoriesRouteImport.update({
    id: '/$locale/$wsId/finance/transactions/categories',
    path: '/$locale/$wsId/finance/transactions/categories',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWsIdEpmEntriesEntryIdRoute =
  LocaleWsIdEpmEntriesEntryIdRouteImport.update({
    id: '/entries/$entryId',
    path: '/entries/$entryId',
    getParentRoute: () => LocaleWsIdEpmRoute,
  } as any)
const LocaleWsIdEpmCollectionsCollectionIdRoute =
  LocaleWsIdEpmCollectionsCollectionIdRouteImport.update({
    id: '/collections/$collectionId',
    path: '/collections/$collectionId',
    getParentRoute: () => LocaleWsIdEpmRoute,
  } as any)
const LocaleWsIdEducationCoursesCourseIdRoute =
  LocaleWsIdEducationCoursesCourseIdRouteImport.update({
    id: '/$locale/$wsId/education/courses/$courseId',
    path: '/$locale/$wsId/education/courses/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleWsIdAiChatMyChatbotsNewRoute =
  LocaleWsIdAiChatMyChatbotsNewRouteImport.update({
    id: '/$locale/$wsId/ai-chat/my-chatbots/new',
    path: '/$locale/$wsId/ai-chat/my-chatbots/new',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/~offline': typeof Char126offlineRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/acceptable-use': typeof LocaleAcceptableUseRoute
  '/$locale/blog': typeof LocaleBlogRoute
  '/$locale/branding': typeof LocaleBrandingRoute
  '/$locale/careers': typeof LocaleCareersRoute
  '/$locale/community-guidelines': typeof LocaleCommunityGuidelinesRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/contributors': typeof LocaleContributorsRoute
  '/$locale/docs': typeof LocaleDocsRoute
  '/$locale/facebook-mockup': typeof LocaleFacebookMockupRoute
  '/$locale/meet-together': typeof LocaleMeetTogetherRoute
  '/$locale/partners': typeof LocalePartnersRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/qr-generator': typeof LocaleQrGeneratorRoute
  '/$locale/security': typeof LocaleSecurityRouteWithChildren
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/verify-token': typeof LocaleVerifyTokenRoute
  '/$locale/women-in-tech': typeof LocaleWomenInTechRoute
  '/products/meet-together': typeof ProductsMeetTogetherRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$wsId/diet': typeof LocaleWsIdDietRoute
  '/$locale/$wsId/epm': typeof LocaleWsIdEpmRouteWithChildren
  '/$locale/$wsId/external-projects': typeof LocaleWsIdExternalProjectsRoute
  '/$locale/$wsId/integrations': typeof LocaleWsIdIntegrationsRoute
  '/$locale/$wsId/meet': typeof LocaleWsIdMeetRoute
  '/$locale/$wsId/metrics': typeof LocaleWsIdMetricsRoute
  '/$locale/$wsId/polls': typeof LocaleWsIdPollsRoute
  '/$locale/$wsId/progress': typeof LocaleWsIdProgressRoute
  '/$locale/$wsId/qr-generator': typeof LocaleWsIdQrGeneratorRoute
  '/$locale/$wsId/readings': typeof LocaleWsIdReadingsRoute
  '/$locale/$wsId/roles': typeof LocaleWsIdRolesRoute
  '/$locale/$wsId/workforce': typeof LocaleWsIdWorkforceRoute
  '/$locale/$wsId/workouts': typeof LocaleWsIdWorkoutsRoute
  '/$locale/calendar/meet-together': typeof LocaleCalendarMeetTogetherRouteWithChildren
  '/$locale/products/ai': typeof LocaleProductsAiRoute
  '/$locale/products/calendar': typeof LocaleProductsCalendarRoute
  '/$locale/products/crm': typeof LocaleProductsCrmRoute
  '/$locale/products/documents': typeof LocaleProductsDocumentsRoute
  '/$locale/products/drive': typeof LocaleProductsDriveRoute
  '/$locale/products/finance': typeof LocaleProductsFinanceRoute
  '/$locale/products/inventory': typeof LocaleProductsInventoryRoute
  '/$locale/products/lms': typeof LocaleProductsLmsRoute
  '/$locale/products/mail': typeof LocaleProductsMailRoute
  '/$locale/products/meet-together': typeof LocaleProductsMeetTogetherRoute
  '/$locale/products/tasks': typeof LocaleProductsTasksRoute
  '/$locale/products/workflows': typeof LocaleProductsWorkflowsRoute
  '/$locale/security/bug-bounty': typeof LocaleSecurityBugBountyRoute
  '/$locale/security/policy': typeof LocaleSecurityPolicyRoute
  '/$locale/solutions/construction': typeof LocaleSolutionsConstructionRoute
  '/$locale/solutions/education': typeof LocaleSolutionsEducationRoute
  '/$locale/solutions/healthcare': typeof LocaleSolutionsHealthcareRoute
  '/$locale/solutions/hospitality': typeof LocaleSolutionsHospitalityRoute
  '/$locale/solutions/manufacturing': typeof LocaleSolutionsManufacturingRoute
  '/$locale/solutions/pharmacies': typeof LocaleSolutionsPharmaciesRoute
  '/$locale/solutions/realestate': typeof LocaleSolutionsRealestateRoute
  '/$locale/solutions/restaurants': typeof LocaleSolutionsRestaurantsRoute
  '/$locale/solutions/retail': typeof LocaleSolutionsRetailRoute
  '/$locale/ui/contributing': typeof LocaleUiContributingRoute
  '/$locale/ui/setup': typeof LocaleUiSetupRoute
  '/$locale/visualizations/horse-racing': typeof LocaleVisualizationsHorseRacingRoute
  '/$locale/ui/': typeof LocaleUiIndexRoute
  '/$locale/$wsId/ai-chat/new': typeof LocaleWsIdAiChatNewRoute
  '/$locale/$wsId/education/flashcards': typeof LocaleWsIdEducationFlashcardsRoute
  '/$locale/$wsId/education/library': typeof LocaleWsIdEducationLibraryRoute
  '/$locale/$wsId/education/quiz-sets': typeof LocaleWsIdEducationQuizSetsRoute
  '/$locale/$wsId/education/quizzes': typeof LocaleWsIdEducationQuizzesRoute
  '/$locale/$wsId/mail/sent': typeof LocaleWsIdMailSentRoute
  '/$locale/$wsId/platform/external-projects': typeof LocaleWsIdPlatformExternalProjectsRoute
  '/$locale/$wsId/tasks/habits': typeof LocaleWsIdTasksHabitsRoute
  '/$locale/$wsId/users/topic-announcements': typeof LocaleWsIdUsersTopicAnnouncementsRoute
  '/$locale/calendar/meet-together/$': typeof LocaleCalendarMeetTogetherSplatRoute
  '/$locale/ui/components/$componentId': typeof LocaleUiComponentsComponentIdRoute
  '/$locale/$wsId/mail/': typeof LocaleWsIdMailIndexRoute
  '/$locale/ui/components/': typeof LocaleUiComponentsIndexRoute
  '/$locale/$wsId/ai-chat/my-chatbots/new': typeof LocaleWsIdAiChatMyChatbotsNewRoute
  '/$locale/$wsId/education/courses/$courseId': typeof LocaleWsIdEducationCoursesCourseIdRoute
  '/$locale/$wsId/epm/collections/$collectionId': typeof LocaleWsIdEpmCollectionsCollectionIdRoute
  '/$locale/$wsId/epm/entries/$entryId': typeof LocaleWsIdEpmEntriesEntryIdRoute
  '/$locale/$wsId/finance/transactions/categories': typeof LocaleWsIdFinanceTransactionsCategoriesRoute
  '/$locale/$wsId/settings/infrastructure/app-coordination': typeof LocaleWsIdSettingsInfrastructureAppCoordinationRoute
  '/$locale/$wsId/tasks/boards/$boardId': typeof LocaleWsIdTasksBoardsBoardIdRoute
  '/$locale/$wsId/users/groups/$groupId': typeof LocaleWsIdUsersGroupsGroupIdRoute
  '/$locale/$wsId/users/reports/$reportId': typeof LocaleWsIdUsersReportsReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/~offline': typeof Char126offlineRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/acceptable-use': typeof LocaleAcceptableUseRoute
  '/$locale/blog': typeof LocaleBlogRoute
  '/$locale/branding': typeof LocaleBrandingRoute
  '/$locale/careers': typeof LocaleCareersRoute
  '/$locale/community-guidelines': typeof LocaleCommunityGuidelinesRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/contributors': typeof LocaleContributorsRoute
  '/$locale/docs': typeof LocaleDocsRoute
  '/$locale/facebook-mockup': typeof LocaleFacebookMockupRoute
  '/$locale/meet-together': typeof LocaleMeetTogetherRoute
  '/$locale/partners': typeof LocalePartnersRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/qr-generator': typeof LocaleQrGeneratorRoute
  '/$locale/security': typeof LocaleSecurityRouteWithChildren
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/verify-token': typeof LocaleVerifyTokenRoute
  '/$locale/women-in-tech': typeof LocaleWomenInTechRoute
  '/products/meet-together': typeof ProductsMeetTogetherRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/$wsId/diet': typeof LocaleWsIdDietRoute
  '/$locale/$wsId/epm': typeof LocaleWsIdEpmRouteWithChildren
  '/$locale/$wsId/external-projects': typeof LocaleWsIdExternalProjectsRoute
  '/$locale/$wsId/integrations': typeof LocaleWsIdIntegrationsRoute
  '/$locale/$wsId/meet': typeof LocaleWsIdMeetRoute
  '/$locale/$wsId/metrics': typeof LocaleWsIdMetricsRoute
  '/$locale/$wsId/polls': typeof LocaleWsIdPollsRoute
  '/$locale/$wsId/progress': typeof LocaleWsIdProgressRoute
  '/$locale/$wsId/qr-generator': typeof LocaleWsIdQrGeneratorRoute
  '/$locale/$wsId/readings': typeof LocaleWsIdReadingsRoute
  '/$locale/$wsId/roles': typeof LocaleWsIdRolesRoute
  '/$locale/$wsId/workforce': typeof LocaleWsIdWorkforceRoute
  '/$locale/$wsId/workouts': typeof LocaleWsIdWorkoutsRoute
  '/$locale/calendar/meet-together': typeof LocaleCalendarMeetTogetherRouteWithChildren
  '/$locale/products/ai': typeof LocaleProductsAiRoute
  '/$locale/products/calendar': typeof LocaleProductsCalendarRoute
  '/$locale/products/crm': typeof LocaleProductsCrmRoute
  '/$locale/products/documents': typeof LocaleProductsDocumentsRoute
  '/$locale/products/drive': typeof LocaleProductsDriveRoute
  '/$locale/products/finance': typeof LocaleProductsFinanceRoute
  '/$locale/products/inventory': typeof LocaleProductsInventoryRoute
  '/$locale/products/lms': typeof LocaleProductsLmsRoute
  '/$locale/products/mail': typeof LocaleProductsMailRoute
  '/$locale/products/meet-together': typeof LocaleProductsMeetTogetherRoute
  '/$locale/products/tasks': typeof LocaleProductsTasksRoute
  '/$locale/products/workflows': typeof LocaleProductsWorkflowsRoute
  '/$locale/security/bug-bounty': typeof LocaleSecurityBugBountyRoute
  '/$locale/security/policy': typeof LocaleSecurityPolicyRoute
  '/$locale/solutions/construction': typeof LocaleSolutionsConstructionRoute
  '/$locale/solutions/education': typeof LocaleSolutionsEducationRoute
  '/$locale/solutions/healthcare': typeof LocaleSolutionsHealthcareRoute
  '/$locale/solutions/hospitality': typeof LocaleSolutionsHospitalityRoute
  '/$locale/solutions/manufacturing': typeof LocaleSolutionsManufacturingRoute
  '/$locale/solutions/pharmacies': typeof LocaleSolutionsPharmaciesRoute
  '/$locale/solutions/realestate': typeof LocaleSolutionsRealestateRoute
  '/$locale/solutions/restaurants': typeof LocaleSolutionsRestaurantsRoute
  '/$locale/solutions/retail': typeof LocaleSolutionsRetailRoute
  '/$locale/ui/contributing': typeof LocaleUiContributingRoute
  '/$locale/ui/setup': typeof LocaleUiSetupRoute
  '/$locale/visualizations/horse-racing': typeof LocaleVisualizationsHorseRacingRoute
  '/$locale/ui': typeof LocaleUiIndexRoute
  '/$locale/$wsId/ai-chat/new': typeof LocaleWsIdAiChatNewRoute
  '/$locale/$wsId/education/flashcards': typeof LocaleWsIdEducationFlashcardsRoute
  '/$locale/$wsId/education/library': typeof LocaleWsIdEducationLibraryRoute
  '/$locale/$wsId/education/quiz-sets': typeof LocaleWsIdEducationQuizSetsRoute
  '/$locale/$wsId/education/quizzes': typeof LocaleWsIdEducationQuizzesRoute
  '/$locale/$wsId/mail/sent': typeof LocaleWsIdMailSentRoute
  '/$locale/$wsId/platform/external-projects': typeof LocaleWsIdPlatformExternalProjectsRoute
  '/$locale/$wsId/tasks/habits': typeof LocaleWsIdTasksHabitsRoute
  '/$locale/$wsId/users/topic-announcements': typeof LocaleWsIdUsersTopicAnnouncementsRoute
  '/$locale/calendar/meet-together/$': typeof LocaleCalendarMeetTogetherSplatRoute
  '/$locale/ui/components/$componentId': typeof LocaleUiComponentsComponentIdRoute
  '/$locale/$wsId/mail': typeof LocaleWsIdMailIndexRoute
  '/$locale/ui/components': typeof LocaleUiComponentsIndexRoute
  '/$locale/$wsId/ai-chat/my-chatbots/new': typeof LocaleWsIdAiChatMyChatbotsNewRoute
  '/$locale/$wsId/education/courses/$courseId': typeof LocaleWsIdEducationCoursesCourseIdRoute
  '/$locale/$wsId/epm/collections/$collectionId': typeof LocaleWsIdEpmCollectionsCollectionIdRoute
  '/$locale/$wsId/epm/entries/$entryId': typeof LocaleWsIdEpmEntriesEntryIdRoute
  '/$locale/$wsId/finance/transactions/categories': typeof LocaleWsIdFinanceTransactionsCategoriesRoute
  '/$locale/$wsId/settings/infrastructure/app-coordination': typeof LocaleWsIdSettingsInfrastructureAppCoordinationRoute
  '/$locale/$wsId/tasks/boards/$boardId': typeof LocaleWsIdTasksBoardsBoardIdRoute
  '/$locale/$wsId/users/groups/$groupId': typeof LocaleWsIdUsersGroupsGroupIdRoute
  '/$locale/$wsId/users/reports/$reportId': typeof LocaleWsIdUsersReportsReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/~offline': typeof Char126offlineRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/acceptable-use': typeof LocaleAcceptableUseRoute
  '/$locale/blog': typeof LocaleBlogRoute
  '/$locale/branding': typeof LocaleBrandingRoute
  '/$locale/careers': typeof LocaleCareersRoute
  '/$locale/community-guidelines': typeof LocaleCommunityGuidelinesRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/contributors': typeof LocaleContributorsRoute
  '/$locale/docs': typeof LocaleDocsRoute
  '/$locale/facebook-mockup': typeof LocaleFacebookMockupRoute
  '/$locale/meet-together': typeof LocaleMeetTogetherRoute
  '/$locale/partners': typeof LocalePartnersRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/qr-generator': typeof LocaleQrGeneratorRoute
  '/$locale/security': typeof LocaleSecurityRouteWithChildren
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/verify-token': typeof LocaleVerifyTokenRoute
  '/$locale/women-in-tech': typeof LocaleWomenInTechRoute
  '/products/meet-together': typeof ProductsMeetTogetherRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$wsId/diet': typeof LocaleWsIdDietRoute
  '/$locale/$wsId/epm': typeof LocaleWsIdEpmRouteWithChildren
  '/$locale/$wsId/external-projects': typeof LocaleWsIdExternalProjectsRoute
  '/$locale/$wsId/integrations': typeof LocaleWsIdIntegrationsRoute
  '/$locale/$wsId/meet': typeof LocaleWsIdMeetRoute
  '/$locale/$wsId/metrics': typeof LocaleWsIdMetricsRoute
  '/$locale/$wsId/polls': typeof LocaleWsIdPollsRoute
  '/$locale/$wsId/progress': typeof LocaleWsIdProgressRoute
  '/$locale/$wsId/qr-generator': typeof LocaleWsIdQrGeneratorRoute
  '/$locale/$wsId/readings': typeof LocaleWsIdReadingsRoute
  '/$locale/$wsId/roles': typeof LocaleWsIdRolesRoute
  '/$locale/$wsId/workforce': typeof LocaleWsIdWorkforceRoute
  '/$locale/$wsId/workouts': typeof LocaleWsIdWorkoutsRoute
  '/$locale/calendar/meet-together': typeof LocaleCalendarMeetTogetherRouteWithChildren
  '/$locale/products/ai': typeof LocaleProductsAiRoute
  '/$locale/products/calendar': typeof LocaleProductsCalendarRoute
  '/$locale/products/crm': typeof LocaleProductsCrmRoute
  '/$locale/products/documents': typeof LocaleProductsDocumentsRoute
  '/$locale/products/drive': typeof LocaleProductsDriveRoute
  '/$locale/products/finance': typeof LocaleProductsFinanceRoute
  '/$locale/products/inventory': typeof LocaleProductsInventoryRoute
  '/$locale/products/lms': typeof LocaleProductsLmsRoute
  '/$locale/products/mail': typeof LocaleProductsMailRoute
  '/$locale/products/meet-together': typeof LocaleProductsMeetTogetherRoute
  '/$locale/products/tasks': typeof LocaleProductsTasksRoute
  '/$locale/products/workflows': typeof LocaleProductsWorkflowsRoute
  '/$locale/security/bug-bounty': typeof LocaleSecurityBugBountyRoute
  '/$locale/security/policy': typeof LocaleSecurityPolicyRoute
  '/$locale/solutions/construction': typeof LocaleSolutionsConstructionRoute
  '/$locale/solutions/education': typeof LocaleSolutionsEducationRoute
  '/$locale/solutions/healthcare': typeof LocaleSolutionsHealthcareRoute
  '/$locale/solutions/hospitality': typeof LocaleSolutionsHospitalityRoute
  '/$locale/solutions/manufacturing': typeof LocaleSolutionsManufacturingRoute
  '/$locale/solutions/pharmacies': typeof LocaleSolutionsPharmaciesRoute
  '/$locale/solutions/realestate': typeof LocaleSolutionsRealestateRoute
  '/$locale/solutions/restaurants': typeof LocaleSolutionsRestaurantsRoute
  '/$locale/solutions/retail': typeof LocaleSolutionsRetailRoute
  '/$locale/ui/contributing': typeof LocaleUiContributingRoute
  '/$locale/ui/setup': typeof LocaleUiSetupRoute
  '/$locale/visualizations/horse-racing': typeof LocaleVisualizationsHorseRacingRoute
  '/$locale/ui/': typeof LocaleUiIndexRoute
  '/$locale/$wsId/ai-chat/new': typeof LocaleWsIdAiChatNewRoute
  '/$locale/$wsId/education/flashcards': typeof LocaleWsIdEducationFlashcardsRoute
  '/$locale/$wsId/education/library': typeof LocaleWsIdEducationLibraryRoute
  '/$locale/$wsId/education/quiz-sets': typeof LocaleWsIdEducationQuizSetsRoute
  '/$locale/$wsId/education/quizzes': typeof LocaleWsIdEducationQuizzesRoute
  '/$locale/$wsId/mail/sent': typeof LocaleWsIdMailSentRoute
  '/$locale/$wsId/platform/external-projects': typeof LocaleWsIdPlatformExternalProjectsRoute
  '/$locale/$wsId/tasks/habits': typeof LocaleWsIdTasksHabitsRoute
  '/$locale/$wsId/users/topic-announcements': typeof LocaleWsIdUsersTopicAnnouncementsRoute
  '/$locale/calendar/meet-together/$': typeof LocaleCalendarMeetTogetherSplatRoute
  '/$locale/ui/components/$componentId': typeof LocaleUiComponentsComponentIdRoute
  '/$locale/$wsId/mail/': typeof LocaleWsIdMailIndexRoute
  '/$locale/ui/components/': typeof LocaleUiComponentsIndexRoute
  '/$locale/$wsId/ai-chat/my-chatbots/new': typeof LocaleWsIdAiChatMyChatbotsNewRoute
  '/$locale/$wsId/education/courses/$courseId': typeof LocaleWsIdEducationCoursesCourseIdRoute
  '/$locale/$wsId/epm/collections/$collectionId': typeof LocaleWsIdEpmCollectionsCollectionIdRoute
  '/$locale/$wsId/epm/entries/$entryId': typeof LocaleWsIdEpmEntriesEntryIdRoute
  '/$locale/$wsId/finance/transactions/categories': typeof LocaleWsIdFinanceTransactionsCategoriesRoute
  '/$locale/$wsId/settings/infrastructure/app-coordination': typeof LocaleWsIdSettingsInfrastructureAppCoordinationRoute
  '/$locale/$wsId/tasks/boards/$boardId': typeof LocaleWsIdTasksBoardsBoardIdRoute
  '/$locale/$wsId/users/groups/$groupId': typeof LocaleWsIdUsersGroupsGroupIdRoute
  '/$locale/$wsId/users/reports/$reportId': typeof LocaleWsIdUsersReportsReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/qr-generator'
    | '/~offline'
    | '/$locale/about'
    | '/$locale/acceptable-use'
    | '/$locale/blog'
    | '/$locale/branding'
    | '/$locale/careers'
    | '/$locale/community-guidelines'
    | '/$locale/contact'
    | '/$locale/contributors'
    | '/$locale/docs'
    | '/$locale/facebook-mockup'
    | '/$locale/meet-together'
    | '/$locale/partners'
    | '/$locale/pricing'
    | '/$locale/privacy'
    | '/$locale/qr-generator'
    | '/$locale/security'
    | '/$locale/terms'
    | '/$locale/verify-token'
    | '/$locale/women-in-tech'
    | '/products/meet-together'
    | '/$locale/'
    | '/$locale/$wsId/diet'
    | '/$locale/$wsId/epm'
    | '/$locale/$wsId/external-projects'
    | '/$locale/$wsId/integrations'
    | '/$locale/$wsId/meet'
    | '/$locale/$wsId/metrics'
    | '/$locale/$wsId/polls'
    | '/$locale/$wsId/progress'
    | '/$locale/$wsId/qr-generator'
    | '/$locale/$wsId/readings'
    | '/$locale/$wsId/roles'
    | '/$locale/$wsId/workforce'
    | '/$locale/$wsId/workouts'
    | '/$locale/calendar/meet-together'
    | '/$locale/products/ai'
    | '/$locale/products/calendar'
    | '/$locale/products/crm'
    | '/$locale/products/documents'
    | '/$locale/products/drive'
    | '/$locale/products/finance'
    | '/$locale/products/inventory'
    | '/$locale/products/lms'
    | '/$locale/products/mail'
    | '/$locale/products/meet-together'
    | '/$locale/products/tasks'
    | '/$locale/products/workflows'
    | '/$locale/security/bug-bounty'
    | '/$locale/security/policy'
    | '/$locale/solutions/construction'
    | '/$locale/solutions/education'
    | '/$locale/solutions/healthcare'
    | '/$locale/solutions/hospitality'
    | '/$locale/solutions/manufacturing'
    | '/$locale/solutions/pharmacies'
    | '/$locale/solutions/realestate'
    | '/$locale/solutions/restaurants'
    | '/$locale/solutions/retail'
    | '/$locale/ui/contributing'
    | '/$locale/ui/setup'
    | '/$locale/visualizations/horse-racing'
    | '/$locale/ui/'
    | '/$locale/$wsId/ai-chat/new'
    | '/$locale/$wsId/education/flashcards'
    | '/$locale/$wsId/education/library'
    | '/$locale/$wsId/education/quiz-sets'
    | '/$locale/$wsId/education/quizzes'
    | '/$locale/$wsId/mail/sent'
    | '/$locale/$wsId/platform/external-projects'
    | '/$locale/$wsId/tasks/habits'
    | '/$locale/$wsId/users/topic-announcements'
    | '/$locale/calendar/meet-together/$'
    | '/$locale/ui/components/$componentId'
    | '/$locale/$wsId/mail/'
    | '/$locale/ui/components/'
    | '/$locale/$wsId/ai-chat/my-chatbots/new'
    | '/$locale/$wsId/education/courses/$courseId'
    | '/$locale/$wsId/epm/collections/$collectionId'
    | '/$locale/$wsId/epm/entries/$entryId'
    | '/$locale/$wsId/finance/transactions/categories'
    | '/$locale/$wsId/settings/infrastructure/app-coordination'
    | '/$locale/$wsId/tasks/boards/$boardId'
    | '/$locale/$wsId/users/groups/$groupId'
    | '/$locale/$wsId/users/reports/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/qr-generator'
    | '/~offline'
    | '/$locale/about'
    | '/$locale/acceptable-use'
    | '/$locale/blog'
    | '/$locale/branding'
    | '/$locale/careers'
    | '/$locale/community-guidelines'
    | '/$locale/contact'
    | '/$locale/contributors'
    | '/$locale/docs'
    | '/$locale/facebook-mockup'
    | '/$locale/meet-together'
    | '/$locale/partners'
    | '/$locale/pricing'
    | '/$locale/privacy'
    | '/$locale/qr-generator'
    | '/$locale/security'
    | '/$locale/terms'
    | '/$locale/verify-token'
    | '/$locale/women-in-tech'
    | '/products/meet-together'
    | '/$locale'
    | '/$locale/$wsId/diet'
    | '/$locale/$wsId/epm'
    | '/$locale/$wsId/external-projects'
    | '/$locale/$wsId/integrations'
    | '/$locale/$wsId/meet'
    | '/$locale/$wsId/metrics'
    | '/$locale/$wsId/polls'
    | '/$locale/$wsId/progress'
    | '/$locale/$wsId/qr-generator'
    | '/$locale/$wsId/readings'
    | '/$locale/$wsId/roles'
    | '/$locale/$wsId/workforce'
    | '/$locale/$wsId/workouts'
    | '/$locale/calendar/meet-together'
    | '/$locale/products/ai'
    | '/$locale/products/calendar'
    | '/$locale/products/crm'
    | '/$locale/products/documents'
    | '/$locale/products/drive'
    | '/$locale/products/finance'
    | '/$locale/products/inventory'
    | '/$locale/products/lms'
    | '/$locale/products/mail'
    | '/$locale/products/meet-together'
    | '/$locale/products/tasks'
    | '/$locale/products/workflows'
    | '/$locale/security/bug-bounty'
    | '/$locale/security/policy'
    | '/$locale/solutions/construction'
    | '/$locale/solutions/education'
    | '/$locale/solutions/healthcare'
    | '/$locale/solutions/hospitality'
    | '/$locale/solutions/manufacturing'
    | '/$locale/solutions/pharmacies'
    | '/$locale/solutions/realestate'
    | '/$locale/solutions/restaurants'
    | '/$locale/solutions/retail'
    | '/$locale/ui/contributing'
    | '/$locale/ui/setup'
    | '/$locale/visualizations/horse-racing'
    | '/$locale/ui'
    | '/$locale/$wsId/ai-chat/new'
    | '/$locale/$wsId/education/flashcards'
    | '/$locale/$wsId/education/library'
    | '/$locale/$wsId/education/quiz-sets'
    | '/$locale/$wsId/education/quizzes'
    | '/$locale/$wsId/mail/sent'
    | '/$locale/$wsId/platform/external-projects'
    | '/$locale/$wsId/tasks/habits'
    | '/$locale/$wsId/users/topic-announcements'
    | '/$locale/calendar/meet-together/$'
    | '/$locale/ui/components/$componentId'
    | '/$locale/$wsId/mail'
    | '/$locale/ui/components'
    | '/$locale/$wsId/ai-chat/my-chatbots/new'
    | '/$locale/$wsId/education/courses/$courseId'
    | '/$locale/$wsId/epm/collections/$collectionId'
    | '/$locale/$wsId/epm/entries/$entryId'
    | '/$locale/$wsId/finance/transactions/categories'
    | '/$locale/$wsId/settings/infrastructure/app-coordination'
    | '/$locale/$wsId/tasks/boards/$boardId'
    | '/$locale/$wsId/users/groups/$groupId'
    | '/$locale/$wsId/users/reports/$reportId'
  id:
    | '__root__'
    | '/'
    | '/pricing'
    | '/qr-generator'
    | '/~offline'
    | '/$locale/about'
    | '/$locale/acceptable-use'
    | '/$locale/blog'
    | '/$locale/branding'
    | '/$locale/careers'
    | '/$locale/community-guidelines'
    | '/$locale/contact'
    | '/$locale/contributors'
    | '/$locale/docs'
    | '/$locale/facebook-mockup'
    | '/$locale/meet-together'
    | '/$locale/partners'
    | '/$locale/pricing'
    | '/$locale/privacy'
    | '/$locale/qr-generator'
    | '/$locale/security'
    | '/$locale/terms'
    | '/$locale/verify-token'
    | '/$locale/women-in-tech'
    | '/products/meet-together'
    | '/$locale/'
    | '/$locale/$wsId/diet'
    | '/$locale/$wsId/epm'
    | '/$locale/$wsId/external-projects'
    | '/$locale/$wsId/integrations'
    | '/$locale/$wsId/meet'
    | '/$locale/$wsId/metrics'
    | '/$locale/$wsId/polls'
    | '/$locale/$wsId/progress'
    | '/$locale/$wsId/qr-generator'
    | '/$locale/$wsId/readings'
    | '/$locale/$wsId/roles'
    | '/$locale/$wsId/workforce'
    | '/$locale/$wsId/workouts'
    | '/$locale/calendar/meet-together'
    | '/$locale/products/ai'
    | '/$locale/products/calendar'
    | '/$locale/products/crm'
    | '/$locale/products/documents'
    | '/$locale/products/drive'
    | '/$locale/products/finance'
    | '/$locale/products/inventory'
    | '/$locale/products/lms'
    | '/$locale/products/mail'
    | '/$locale/products/meet-together'
    | '/$locale/products/tasks'
    | '/$locale/products/workflows'
    | '/$locale/security/bug-bounty'
    | '/$locale/security/policy'
    | '/$locale/solutions/construction'
    | '/$locale/solutions/education'
    | '/$locale/solutions/healthcare'
    | '/$locale/solutions/hospitality'
    | '/$locale/solutions/manufacturing'
    | '/$locale/solutions/pharmacies'
    | '/$locale/solutions/realestate'
    | '/$locale/solutions/restaurants'
    | '/$locale/solutions/retail'
    | '/$locale/ui/contributing'
    | '/$locale/ui/setup'
    | '/$locale/visualizations/horse-racing'
    | '/$locale/ui/'
    | '/$locale/$wsId/ai-chat/new'
    | '/$locale/$wsId/education/flashcards'
    | '/$locale/$wsId/education/library'
    | '/$locale/$wsId/education/quiz-sets'
    | '/$locale/$wsId/education/quizzes'
    | '/$locale/$wsId/mail/sent'
    | '/$locale/$wsId/platform/external-projects'
    | '/$locale/$wsId/tasks/habits'
    | '/$locale/$wsId/users/topic-announcements'
    | '/$locale/calendar/meet-together/$'
    | '/$locale/ui/components/$componentId'
    | '/$locale/$wsId/mail/'
    | '/$locale/ui/components/'
    | '/$locale/$wsId/ai-chat/my-chatbots/new'
    | '/$locale/$wsId/education/courses/$courseId'
    | '/$locale/$wsId/epm/collections/$collectionId'
    | '/$locale/$wsId/epm/entries/$entryId'
    | '/$locale/$wsId/finance/transactions/categories'
    | '/$locale/$wsId/settings/infrastructure/app-coordination'
    | '/$locale/$wsId/tasks/boards/$boardId'
    | '/$locale/$wsId/users/groups/$groupId'
    | '/$locale/$wsId/users/reports/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricingRoute: typeof PricingRoute
  QrGeneratorRoute: typeof QrGeneratorRoute
  Char126offlineRoute: typeof Char126offlineRoute
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleAcceptableUseRoute: typeof LocaleAcceptableUseRoute
  LocaleBlogRoute: typeof LocaleBlogRoute
  LocaleBrandingRoute: typeof LocaleBrandingRoute
  LocaleCareersRoute: typeof LocaleCareersRoute
  LocaleCommunityGuidelinesRoute: typeof LocaleCommunityGuidelinesRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleContributorsRoute: typeof LocaleContributorsRoute
  LocaleDocsRoute: typeof LocaleDocsRoute
  LocaleFacebookMockupRoute: typeof LocaleFacebookMockupRoute
  LocaleMeetTogetherRoute: typeof LocaleMeetTogetherRoute
  LocalePartnersRoute: typeof LocalePartnersRoute
  LocalePricingRoute: typeof LocalePricingRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleQrGeneratorRoute: typeof LocaleQrGeneratorRoute
  LocaleSecurityRoute: typeof LocaleSecurityRouteWithChildren
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleVerifyTokenRoute: typeof LocaleVerifyTokenRoute
  LocaleWomenInTechRoute: typeof LocaleWomenInTechRoute
  ProductsMeetTogetherRoute: typeof ProductsMeetTogetherRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleWsIdDietRoute: typeof LocaleWsIdDietRoute
  LocaleWsIdEpmRoute: typeof LocaleWsIdEpmRouteWithChildren
  LocaleWsIdExternalProjectsRoute: typeof LocaleWsIdExternalProjectsRoute
  LocaleWsIdIntegrationsRoute: typeof LocaleWsIdIntegrationsRoute
  LocaleWsIdMeetRoute: typeof LocaleWsIdMeetRoute
  LocaleWsIdMetricsRoute: typeof LocaleWsIdMetricsRoute
  LocaleWsIdPollsRoute: typeof LocaleWsIdPollsRoute
  LocaleWsIdProgressRoute: typeof LocaleWsIdProgressRoute
  LocaleWsIdQrGeneratorRoute: typeof LocaleWsIdQrGeneratorRoute
  LocaleWsIdReadingsRoute: typeof LocaleWsIdReadingsRoute
  LocaleWsIdRolesRoute: typeof LocaleWsIdRolesRoute
  LocaleWsIdWorkforceRoute: typeof LocaleWsIdWorkforceRoute
  LocaleWsIdWorkoutsRoute: typeof LocaleWsIdWorkoutsRoute
  LocaleCalendarMeetTogetherRoute: typeof LocaleCalendarMeetTogetherRouteWithChildren
  LocaleProductsAiRoute: typeof LocaleProductsAiRoute
  LocaleProductsCalendarRoute: typeof LocaleProductsCalendarRoute
  LocaleProductsCrmRoute: typeof LocaleProductsCrmRoute
  LocaleProductsDocumentsRoute: typeof LocaleProductsDocumentsRoute
  LocaleProductsDriveRoute: typeof LocaleProductsDriveRoute
  LocaleProductsFinanceRoute: typeof LocaleProductsFinanceRoute
  LocaleProductsInventoryRoute: typeof LocaleProductsInventoryRoute
  LocaleProductsLmsRoute: typeof LocaleProductsLmsRoute
  LocaleProductsMailRoute: typeof LocaleProductsMailRoute
  LocaleProductsMeetTogetherRoute: typeof LocaleProductsMeetTogetherRoute
  LocaleProductsTasksRoute: typeof LocaleProductsTasksRoute
  LocaleProductsWorkflowsRoute: typeof LocaleProductsWorkflowsRoute
  LocaleSolutionsConstructionRoute: typeof LocaleSolutionsConstructionRoute
  LocaleSolutionsEducationRoute: typeof LocaleSolutionsEducationRoute
  LocaleSolutionsHealthcareRoute: typeof LocaleSolutionsHealthcareRoute
  LocaleSolutionsHospitalityRoute: typeof LocaleSolutionsHospitalityRoute
  LocaleSolutionsManufacturingRoute: typeof LocaleSolutionsManufacturingRoute
  LocaleSolutionsPharmaciesRoute: typeof LocaleSolutionsPharmaciesRoute
  LocaleSolutionsRealestateRoute: typeof LocaleSolutionsRealestateRoute
  LocaleSolutionsRestaurantsRoute: typeof LocaleSolutionsRestaurantsRoute
  LocaleSolutionsRetailRoute: typeof LocaleSolutionsRetailRoute
  LocaleUiContributingRoute: typeof LocaleUiContributingRoute
  LocaleUiSetupRoute: typeof LocaleUiSetupRoute
  LocaleVisualizationsHorseRacingRoute: typeof LocaleVisualizationsHorseRacingRoute
  LocaleUiIndexRoute: typeof LocaleUiIndexRoute
  LocaleWsIdAiChatNewRoute: typeof LocaleWsIdAiChatNewRoute
  LocaleWsIdEducationFlashcardsRoute: typeof LocaleWsIdEducationFlashcardsRoute
  LocaleWsIdEducationLibraryRoute: typeof LocaleWsIdEducationLibraryRoute
  LocaleWsIdEducationQuizSetsRoute: typeof LocaleWsIdEducationQuizSetsRoute
  LocaleWsIdEducationQuizzesRoute: typeof LocaleWsIdEducationQuizzesRoute
  LocaleWsIdMailSentRoute: typeof LocaleWsIdMailSentRoute
  LocaleWsIdPlatformExternalProjectsRoute: typeof LocaleWsIdPlatformExternalProjectsRoute
  LocaleWsIdTasksHabitsRoute: typeof LocaleWsIdTasksHabitsRoute
  LocaleWsIdUsersTopicAnnouncementsRoute: typeof LocaleWsIdUsersTopicAnnouncementsRoute
  LocaleUiComponentsComponentIdRoute: typeof LocaleUiComponentsComponentIdRoute
  LocaleWsIdMailIndexRoute: typeof LocaleWsIdMailIndexRoute
  LocaleUiComponentsIndexRoute: typeof LocaleUiComponentsIndexRoute
  LocaleWsIdAiChatMyChatbotsNewRoute: typeof LocaleWsIdAiChatMyChatbotsNewRoute
  LocaleWsIdEducationCoursesCourseIdRoute: typeof LocaleWsIdEducationCoursesCourseIdRoute
  LocaleWsIdFinanceTransactionsCategoriesRoute: typeof LocaleWsIdFinanceTransactionsCategoriesRoute
  LocaleWsIdSettingsInfrastructureAppCoordinationRoute: typeof LocaleWsIdSettingsInfrastructureAppCoordinationRoute
  LocaleWsIdTasksBoardsBoardIdRoute: typeof LocaleWsIdTasksBoardsBoardIdRoute
  LocaleWsIdUsersGroupsGroupIdRoute: typeof LocaleWsIdUsersGroupsGroupIdRoute
  LocaleWsIdUsersReportsReportIdRoute: typeof LocaleWsIdUsersReportsReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/~offline': {
      id: '/~offline'
      path: '/~offline'
      fullPath: '/~offline'
      preLoaderRoute: typeof Char126offlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-generator': {
      id: '/qr-generator'
      path: '/qr-generator'
      fullPath: '/qr-generator'
      preLoaderRoute: typeof QrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/meet-together': {
      id: '/products/meet-together'
      path: '/products/meet-together'
      fullPath: '/products/meet-together'
      preLoaderRoute: typeof ProductsMeetTogetherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/women-in-tech': {
      id: '/$locale/women-in-tech'
      path: '/$locale/women-in-tech'
      fullPath: '/$locale/women-in-tech'
      preLoaderRoute: typeof LocaleWomenInTechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/verify-token': {
      id: '/$locale/verify-token'
      path: '/$locale/verify-token'
      fullPath: '/$locale/verify-token'
      preLoaderRoute: typeof LocaleVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/$locale/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/security': {
      id: '/$locale/security'
      path: '/$locale/security'
      fullPath: '/$locale/security'
      preLoaderRoute: typeof LocaleSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/qr-generator': {
      id: '/$locale/qr-generator'
      path: '/$locale/qr-generator'
      fullPath: '/$locale/qr-generator'
      preLoaderRoute: typeof LocaleQrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/$locale/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/pricing': {
      id: '/$locale/pricing'
      path: '/$locale/pricing'
      fullPath: '/$locale/pricing'
      preLoaderRoute: typeof LocalePricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/partners': {
      id: '/$locale/partners'
      path: '/$locale/partners'
      fullPath: '/$locale/partners'
      preLoaderRoute: typeof LocalePartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/meet-together': {
      id: '/$locale/meet-together'
      path: '/$locale/meet-together'
      fullPath: '/$locale/meet-together'
      preLoaderRoute: typeof LocaleMeetTogetherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/facebook-mockup': {
      id: '/$locale/facebook-mockup'
      path: '/$locale/facebook-mockup'
      fullPath: '/$locale/facebook-mockup'
      preLoaderRoute: typeof LocaleFacebookMockupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/docs': {
      id: '/$locale/docs'
      path: '/$locale/docs'
      fullPath: '/$locale/docs'
      preLoaderRoute: typeof LocaleDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/contributors': {
      id: '/$locale/contributors'
      path: '/$locale/contributors'
      fullPath: '/$locale/contributors'
      preLoaderRoute: typeof LocaleContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/$locale/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/community-guidelines': {
      id: '/$locale/community-guidelines'
      path: '/$locale/community-guidelines'
      fullPath: '/$locale/community-guidelines'
      preLoaderRoute: typeof LocaleCommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/careers': {
      id: '/$locale/careers'
      path: '/$locale/careers'
      fullPath: '/$locale/careers'
      preLoaderRoute: typeof LocaleCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/branding': {
      id: '/$locale/branding'
      path: '/$locale/branding'
      fullPath: '/$locale/branding'
      preLoaderRoute: typeof LocaleBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog': {
      id: '/$locale/blog'
      path: '/$locale/blog'
      fullPath: '/$locale/blog'
      preLoaderRoute: typeof LocaleBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/acceptable-use': {
      id: '/$locale/acceptable-use'
      path: '/$locale/acceptable-use'
      fullPath: '/$locale/acceptable-use'
      preLoaderRoute: typeof LocaleAcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/$locale/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/ui/': {
      id: '/$locale/ui/'
      path: '/$locale/ui'
      fullPath: '/$locale/ui/'
      preLoaderRoute: typeof LocaleUiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/visualizations/horse-racing': {
      id: '/$locale/visualizations/horse-racing'
      path: '/$locale/visualizations/horse-racing'
      fullPath: '/$locale/visualizations/horse-racing'
      preLoaderRoute: typeof LocaleVisualizationsHorseRacingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/ui/setup': {
      id: '/$locale/ui/setup'
      path: '/$locale/ui/setup'
      fullPath: '/$locale/ui/setup'
      preLoaderRoute: typeof LocaleUiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/ui/contributing': {
      id: '/$locale/ui/contributing'
      path: '/$locale/ui/contributing'
      fullPath: '/$locale/ui/contributing'
      preLoaderRoute: typeof LocaleUiContributingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/solutions/retail': {
      id: '/$locale/solutions/retail'
      path: '/$locale/solutions/retail'
      fullPath: '/$locale/solutions/retail'
      preLoaderRoute: typeof LocaleSolutionsRetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/solutions/restaurants': {
      id: '/$locale/solutions/restaurants'
      path: '/$locale/solutions/restaurants'
      fullPath: '/$locale/solutions/restaurants'
      preLoaderRoute: typeof LocaleSolutionsRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/solutions/realestate': {
      id: '/$locale/solutions/realestate'
      path: '/$locale/solutions/realestate'
      fullPath: '/$locale/solutions/realestate'
      preLoaderRoute: typeof LocaleSolutionsRealestateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/solutions/pharmacies': {
      id: '/$locale/solutions/pharmacies'
      path: '/$locale/solutions/pharmacies'
      fullPath: '/$locale/solutions/pharmacies'
      preLoaderRoute: typeof LocaleSolutionsPharmaciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/solutions/manufacturing': {
      id: '/$locale/solutions/manufacturing'
      path: '/$locale/solutions/manufacturing'
      fullPath: '/$locale/solutions/manufacturing'
      preLoaderRoute: typeof LocaleSolutionsManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/solutions/hospitality': {
      id: '/$locale/solutions/hospitality'
      path: '/$locale/solutions/hospitality'
      fullPath: '/$locale/solutions/hospitality'
      preLoaderRoute: typeof LocaleSolutionsHospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/solutions/healthcare': {
      id: '/$locale/solutions/healthcare'
      path: '/$locale/solutions/healthcare'
      fullPath: '/$locale/solutions/healthcare'
      preLoaderRoute: typeof LocaleSolutionsHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/solutions/education': {
      id: '/$locale/solutions/education'
      path: '/$locale/solutions/education'
      fullPath: '/$locale/solutions/education'
      preLoaderRoute: typeof LocaleSolutionsEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/solutions/construction': {
      id: '/$locale/solutions/construction'
      path: '/$locale/solutions/construction'
      fullPath: '/$locale/solutions/construction'
      preLoaderRoute: typeof LocaleSolutionsConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/security/policy': {
      id: '/$locale/security/policy'
      path: '/policy'
      fullPath: '/$locale/security/policy'
      preLoaderRoute: typeof LocaleSecurityPolicyRouteImport
      parentRoute: typeof LocaleSecurityRoute
    }
    '/$locale/security/bug-bounty': {
      id: '/$locale/security/bug-bounty'
      path: '/bug-bounty'
      fullPath: '/$locale/security/bug-bounty'
      preLoaderRoute: typeof LocaleSecurityBugBountyRouteImport
      parentRoute: typeof LocaleSecurityRoute
    }
    '/$locale/products/workflows': {
      id: '/$locale/products/workflows'
      path: '/$locale/products/workflows'
      fullPath: '/$locale/products/workflows'
      preLoaderRoute: typeof LocaleProductsWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/products/tasks': {
      id: '/$locale/products/tasks'
      path: '/$locale/products/tasks'
      fullPath: '/$locale/products/tasks'
      preLoaderRoute: typeof LocaleProductsTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/products/meet-together': {
      id: '/$locale/products/meet-together'
      path: '/$locale/products/meet-together'
      fullPath: '/$locale/products/meet-together'
      preLoaderRoute: typeof LocaleProductsMeetTogetherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/products/mail': {
      id: '/$locale/products/mail'
      path: '/$locale/products/mail'
      fullPath: '/$locale/products/mail'
      preLoaderRoute: typeof LocaleProductsMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/products/lms': {
      id: '/$locale/products/lms'
      path: '/$locale/products/lms'
      fullPath: '/$locale/products/lms'
      preLoaderRoute: typeof LocaleProductsLmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/products/inventory': {
      id: '/$locale/products/inventory'
      path: '/$locale/products/inventory'
      fullPath: '/$locale/products/inventory'
      preLoaderRoute: typeof LocaleProductsInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/products/finance': {
      id: '/$locale/products/finance'
      path: '/$locale/products/finance'
      fullPath: '/$locale/products/finance'
      preLoaderRoute: typeof LocaleProductsFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/products/drive': {
      id: '/$locale/products/drive'
      path: '/$locale/products/drive'
      fullPath: '/$locale/products/drive'
      preLoaderRoute: typeof LocaleProductsDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/products/documents': {
      id: '/$locale/products/documents'
      path: '/$locale/products/documents'
      fullPath: '/$locale/products/documents'
      preLoaderRoute: typeof LocaleProductsDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/products/crm': {
      id: '/$locale/products/crm'
      path: '/$locale/products/crm'
      fullPath: '/$locale/products/crm'
      preLoaderRoute: typeof LocaleProductsCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/products/calendar': {
      id: '/$locale/products/calendar'
      path: '/$locale/products/calendar'
      fullPath: '/$locale/products/calendar'
      preLoaderRoute: typeof LocaleProductsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/products/ai': {
      id: '/$locale/products/ai'
      path: '/$locale/products/ai'
      fullPath: '/$locale/products/ai'
      preLoaderRoute: typeof LocaleProductsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/calendar/meet-together': {
      id: '/$locale/calendar/meet-together'
      path: '/$locale/calendar/meet-together'
      fullPath: '/$locale/calendar/meet-together'
      preLoaderRoute: typeof LocaleCalendarMeetTogetherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/workouts': {
      id: '/$locale/$wsId/workouts'
      path: '/$locale/$wsId/workouts'
      fullPath: '/$locale/$wsId/workouts'
      preLoaderRoute: typeof LocaleWsIdWorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/workforce': {
      id: '/$locale/$wsId/workforce'
      path: '/$locale/$wsId/workforce'
      fullPath: '/$locale/$wsId/workforce'
      preLoaderRoute: typeof LocaleWsIdWorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/roles': {
      id: '/$locale/$wsId/roles'
      path: '/$locale/$wsId/roles'
      fullPath: '/$locale/$wsId/roles'
      preLoaderRoute: typeof LocaleWsIdRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/readings': {
      id: '/$locale/$wsId/readings'
      path: '/$locale/$wsId/readings'
      fullPath: '/$locale/$wsId/readings'
      preLoaderRoute: typeof LocaleWsIdReadingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/qr-generator': {
      id: '/$locale/$wsId/qr-generator'
      path: '/$locale/$wsId/qr-generator'
      fullPath: '/$locale/$wsId/qr-generator'
      preLoaderRoute: typeof LocaleWsIdQrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/progress': {
      id: '/$locale/$wsId/progress'
      path: '/$locale/$wsId/progress'
      fullPath: '/$locale/$wsId/progress'
      preLoaderRoute: typeof LocaleWsIdProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/polls': {
      id: '/$locale/$wsId/polls'
      path: '/$locale/$wsId/polls'
      fullPath: '/$locale/$wsId/polls'
      preLoaderRoute: typeof LocaleWsIdPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/metrics': {
      id: '/$locale/$wsId/metrics'
      path: '/$locale/$wsId/metrics'
      fullPath: '/$locale/$wsId/metrics'
      preLoaderRoute: typeof LocaleWsIdMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/meet': {
      id: '/$locale/$wsId/meet'
      path: '/$locale/$wsId/meet'
      fullPath: '/$locale/$wsId/meet'
      preLoaderRoute: typeof LocaleWsIdMeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/integrations': {
      id: '/$locale/$wsId/integrations'
      path: '/$locale/$wsId/integrations'
      fullPath: '/$locale/$wsId/integrations'
      preLoaderRoute: typeof LocaleWsIdIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/external-projects': {
      id: '/$locale/$wsId/external-projects'
      path: '/$locale/$wsId/external-projects'
      fullPath: '/$locale/$wsId/external-projects'
      preLoaderRoute: typeof LocaleWsIdExternalProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/epm': {
      id: '/$locale/$wsId/epm'
      path: '/$locale/$wsId/epm'
      fullPath: '/$locale/$wsId/epm'
      preLoaderRoute: typeof LocaleWsIdEpmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/diet': {
      id: '/$locale/$wsId/diet'
      path: '/$locale/$wsId/diet'
      fullPath: '/$locale/$wsId/diet'
      preLoaderRoute: typeof LocaleWsIdDietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/ui/components/': {
      id: '/$locale/ui/components/'
      path: '/$locale/ui/components'
      fullPath: '/$locale/ui/components/'
      preLoaderRoute: typeof LocaleUiComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/mail/': {
      id: '/$locale/$wsId/mail/'
      path: '/$locale/$wsId/mail'
      fullPath: '/$locale/$wsId/mail/'
      preLoaderRoute: typeof LocaleWsIdMailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/ui/components/$componentId': {
      id: '/$locale/ui/components/$componentId'
      path: '/$locale/ui/components/$componentId'
      fullPath: '/$locale/ui/components/$componentId'
      preLoaderRoute: typeof LocaleUiComponentsComponentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/calendar/meet-together/$': {
      id: '/$locale/calendar/meet-together/$'
      path: '/$'
      fullPath: '/$locale/calendar/meet-together/$'
      preLoaderRoute: typeof LocaleCalendarMeetTogetherSplatRouteImport
      parentRoute: typeof LocaleCalendarMeetTogetherRoute
    }
    '/$locale/$wsId/users/topic-announcements': {
      id: '/$locale/$wsId/users/topic-announcements'
      path: '/$locale/$wsId/users/topic-announcements'
      fullPath: '/$locale/$wsId/users/topic-announcements'
      preLoaderRoute: typeof LocaleWsIdUsersTopicAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/tasks/habits': {
      id: '/$locale/$wsId/tasks/habits'
      path: '/$locale/$wsId/tasks/habits'
      fullPath: '/$locale/$wsId/tasks/habits'
      preLoaderRoute: typeof LocaleWsIdTasksHabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/platform/external-projects': {
      id: '/$locale/$wsId/platform/external-projects'
      path: '/$locale/$wsId/platform/external-projects'
      fullPath: '/$locale/$wsId/platform/external-projects'
      preLoaderRoute: typeof LocaleWsIdPlatformExternalProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/mail/sent': {
      id: '/$locale/$wsId/mail/sent'
      path: '/$locale/$wsId/mail/sent'
      fullPath: '/$locale/$wsId/mail/sent'
      preLoaderRoute: typeof LocaleWsIdMailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/education/quizzes': {
      id: '/$locale/$wsId/education/quizzes'
      path: '/$locale/$wsId/education/quizzes'
      fullPath: '/$locale/$wsId/education/quizzes'
      preLoaderRoute: typeof LocaleWsIdEducationQuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/education/quiz-sets': {
      id: '/$locale/$wsId/education/quiz-sets'
      path: '/$locale/$wsId/education/quiz-sets'
      fullPath: '/$locale/$wsId/education/quiz-sets'
      preLoaderRoute: typeof LocaleWsIdEducationQuizSetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/education/library': {
      id: '/$locale/$wsId/education/library'
      path: '/$locale/$wsId/education/library'
      fullPath: '/$locale/$wsId/education/library'
      preLoaderRoute: typeof LocaleWsIdEducationLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/education/flashcards': {
      id: '/$locale/$wsId/education/flashcards'
      path: '/$locale/$wsId/education/flashcards'
      fullPath: '/$locale/$wsId/education/flashcards'
      preLoaderRoute: typeof LocaleWsIdEducationFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/ai-chat/new': {
      id: '/$locale/$wsId/ai-chat/new'
      path: '/$locale/$wsId/ai-chat/new'
      fullPath: '/$locale/$wsId/ai-chat/new'
      preLoaderRoute: typeof LocaleWsIdAiChatNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/users/reports/$reportId': {
      id: '/$locale/$wsId/users/reports/$reportId'
      path: '/$locale/$wsId/users/reports/$reportId'
      fullPath: '/$locale/$wsId/users/reports/$reportId'
      preLoaderRoute: typeof LocaleWsIdUsersReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/users/groups/$groupId': {
      id: '/$locale/$wsId/users/groups/$groupId'
      path: '/$locale/$wsId/users/groups/$groupId'
      fullPath: '/$locale/$wsId/users/groups/$groupId'
      preLoaderRoute: typeof LocaleWsIdUsersGroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/tasks/boards/$boardId': {
      id: '/$locale/$wsId/tasks/boards/$boardId'
      path: '/$locale/$wsId/tasks/boards/$boardId'
      fullPath: '/$locale/$wsId/tasks/boards/$boardId'
      preLoaderRoute: typeof LocaleWsIdTasksBoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/settings/infrastructure/app-coordination': {
      id: '/$locale/$wsId/settings/infrastructure/app-coordination'
      path: '/$locale/$wsId/settings/infrastructure/app-coordination'
      fullPath: '/$locale/$wsId/settings/infrastructure/app-coordination'
      preLoaderRoute: typeof LocaleWsIdSettingsInfrastructureAppCoordinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/finance/transactions/categories': {
      id: '/$locale/$wsId/finance/transactions/categories'
      path: '/$locale/$wsId/finance/transactions/categories'
      fullPath: '/$locale/$wsId/finance/transactions/categories'
      preLoaderRoute: typeof LocaleWsIdFinanceTransactionsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/epm/entries/$entryId': {
      id: '/$locale/$wsId/epm/entries/$entryId'
      path: '/entries/$entryId'
      fullPath: '/$locale/$wsId/epm/entries/$entryId'
      preLoaderRoute: typeof LocaleWsIdEpmEntriesEntryIdRouteImport
      parentRoute: typeof LocaleWsIdEpmRoute
    }
    '/$locale/$wsId/epm/collections/$collectionId': {
      id: '/$locale/$wsId/epm/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/$locale/$wsId/epm/collections/$collectionId'
      preLoaderRoute: typeof LocaleWsIdEpmCollectionsCollectionIdRouteImport
      parentRoute: typeof LocaleWsIdEpmRoute
    }
    '/$locale/$wsId/education/courses/$courseId': {
      id: '/$locale/$wsId/education/courses/$courseId'
      path: '/$locale/$wsId/education/courses/$courseId'
      fullPath: '/$locale/$wsId/education/courses/$courseId'
      preLoaderRoute: typeof LocaleWsIdEducationCoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$wsId/ai-chat/my-chatbots/new': {
      id: '/$locale/$wsId/ai-chat/my-chatbots/new'
      path: '/$locale/$wsId/ai-chat/my-chatbots/new'
      fullPath: '/$locale/$wsId/ai-chat/my-chatbots/new'
      preLoaderRoute: typeof LocaleWsIdAiChatMyChatbotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleSecurityRouteChildren {
  LocaleSecurityBugBountyRoute: typeof LocaleSecurityBugBountyRoute
  LocaleSecurityPolicyRoute: typeof LocaleSecurityPolicyRoute
}

const LocaleSecurityRouteChildren: LocaleSecurityRouteChildren = {
  LocaleSecurityBugBountyRoute: LocaleSecurityBugBountyRoute,
  LocaleSecurityPolicyRoute: LocaleSecurityPolicyRoute,
}

const LocaleSecurityRouteWithChildren = LocaleSecurityRoute._addFileChildren(
  LocaleSecurityRouteChildren,
)

interface LocaleWsIdEpmRouteChildren {
  LocaleWsIdEpmCollectionsCollectionIdRoute: typeof LocaleWsIdEpmCollectionsCollectionIdRoute
  LocaleWsIdEpmEntriesEntryIdRoute: typeof LocaleWsIdEpmEntriesEntryIdRoute
}

const LocaleWsIdEpmRouteChildren: LocaleWsIdEpmRouteChildren = {
  LocaleWsIdEpmCollectionsCollectionIdRoute:
    LocaleWsIdEpmCollectionsCollectionIdRoute,
  LocaleWsIdEpmEntriesEntryIdRoute: LocaleWsIdEpmEntriesEntryIdRoute,
}

const LocaleWsIdEpmRouteWithChildren = LocaleWsIdEpmRoute._addFileChildren(
  LocaleWsIdEpmRouteChildren,
)

interface LocaleCalendarMeetTogetherRouteChildren {
  LocaleCalendarMeetTogetherSplatRoute: typeof LocaleCalendarMeetTogetherSplatRoute
}

const LocaleCalendarMeetTogetherRouteChildren: LocaleCalendarMeetTogetherRouteChildren =
  {
    LocaleCalendarMeetTogetherSplatRoute: LocaleCalendarMeetTogetherSplatRoute,
  }

const LocaleCalendarMeetTogetherRouteWithChildren =
  LocaleCalendarMeetTogetherRoute._addFileChildren(
    LocaleCalendarMeetTogetherRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingRoute: PricingRoute,
  QrGeneratorRoute: QrGeneratorRoute,
  Char126offlineRoute: Char126offlineRoute,
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleAcceptableUseRoute: LocaleAcceptableUseRoute,
  LocaleBlogRoute: LocaleBlogRoute,
  LocaleBrandingRoute: LocaleBrandingRoute,
  LocaleCareersRoute: LocaleCareersRoute,
  LocaleCommunityGuidelinesRoute: LocaleCommunityGuidelinesRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleContributorsRoute: LocaleContributorsRoute,
  LocaleDocsRoute: LocaleDocsRoute,
  LocaleFacebookMockupRoute: LocaleFacebookMockupRoute,
  LocaleMeetTogetherRoute: LocaleMeetTogetherRoute,
  LocalePartnersRoute: LocalePartnersRoute,
  LocalePricingRoute: LocalePricingRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleQrGeneratorRoute: LocaleQrGeneratorRoute,
  LocaleSecurityRoute: LocaleSecurityRouteWithChildren,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleVerifyTokenRoute: LocaleVerifyTokenRoute,
  LocaleWomenInTechRoute: LocaleWomenInTechRoute,
  ProductsMeetTogetherRoute: ProductsMeetTogetherRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleWsIdDietRoute: LocaleWsIdDietRoute,
  LocaleWsIdEpmRoute: LocaleWsIdEpmRouteWithChildren,
  LocaleWsIdExternalProjectsRoute: LocaleWsIdExternalProjectsRoute,
  LocaleWsIdIntegrationsRoute: LocaleWsIdIntegrationsRoute,
  LocaleWsIdMeetRoute: LocaleWsIdMeetRoute,
  LocaleWsIdMetricsRoute: LocaleWsIdMetricsRoute,
  LocaleWsIdPollsRoute: LocaleWsIdPollsRoute,
  LocaleWsIdProgressRoute: LocaleWsIdProgressRoute,
  LocaleWsIdQrGeneratorRoute: LocaleWsIdQrGeneratorRoute,
  LocaleWsIdReadingsRoute: LocaleWsIdReadingsRoute,
  LocaleWsIdRolesRoute: LocaleWsIdRolesRoute,
  LocaleWsIdWorkforceRoute: LocaleWsIdWorkforceRoute,
  LocaleWsIdWorkoutsRoute: LocaleWsIdWorkoutsRoute,
  LocaleCalendarMeetTogetherRoute: LocaleCalendarMeetTogetherRouteWithChildren,
  LocaleProductsAiRoute: LocaleProductsAiRoute,
  LocaleProductsCalendarRoute: LocaleProductsCalendarRoute,
  LocaleProductsCrmRoute: LocaleProductsCrmRoute,
  LocaleProductsDocumentsRoute: LocaleProductsDocumentsRoute,
  LocaleProductsDriveRoute: LocaleProductsDriveRoute,
  LocaleProductsFinanceRoute: LocaleProductsFinanceRoute,
  LocaleProductsInventoryRoute: LocaleProductsInventoryRoute,
  LocaleProductsLmsRoute: LocaleProductsLmsRoute,
  LocaleProductsMailRoute: LocaleProductsMailRoute,
  LocaleProductsMeetTogetherRoute: LocaleProductsMeetTogetherRoute,
  LocaleProductsTasksRoute: LocaleProductsTasksRoute,
  LocaleProductsWorkflowsRoute: LocaleProductsWorkflowsRoute,
  LocaleSolutionsConstructionRoute: LocaleSolutionsConstructionRoute,
  LocaleSolutionsEducationRoute: LocaleSolutionsEducationRoute,
  LocaleSolutionsHealthcareRoute: LocaleSolutionsHealthcareRoute,
  LocaleSolutionsHospitalityRoute: LocaleSolutionsHospitalityRoute,
  LocaleSolutionsManufacturingRoute: LocaleSolutionsManufacturingRoute,
  LocaleSolutionsPharmaciesRoute: LocaleSolutionsPharmaciesRoute,
  LocaleSolutionsRealestateRoute: LocaleSolutionsRealestateRoute,
  LocaleSolutionsRestaurantsRoute: LocaleSolutionsRestaurantsRoute,
  LocaleSolutionsRetailRoute: LocaleSolutionsRetailRoute,
  LocaleUiContributingRoute: LocaleUiContributingRoute,
  LocaleUiSetupRoute: LocaleUiSetupRoute,
  LocaleVisualizationsHorseRacingRoute: LocaleVisualizationsHorseRacingRoute,
  LocaleUiIndexRoute: LocaleUiIndexRoute,
  LocaleWsIdAiChatNewRoute: LocaleWsIdAiChatNewRoute,
  LocaleWsIdEducationFlashcardsRoute: LocaleWsIdEducationFlashcardsRoute,
  LocaleWsIdEducationLibraryRoute: LocaleWsIdEducationLibraryRoute,
  LocaleWsIdEducationQuizSetsRoute: LocaleWsIdEducationQuizSetsRoute,
  LocaleWsIdEducationQuizzesRoute: LocaleWsIdEducationQuizzesRoute,
  LocaleWsIdMailSentRoute: LocaleWsIdMailSentRoute,
  LocaleWsIdPlatformExternalProjectsRoute:
    LocaleWsIdPlatformExternalProjectsRoute,
  LocaleWsIdTasksHabitsRoute: LocaleWsIdTasksHabitsRoute,
  LocaleWsIdUsersTopicAnnouncementsRoute:
    LocaleWsIdUsersTopicAnnouncementsRoute,
  LocaleUiComponentsComponentIdRoute: LocaleUiComponentsComponentIdRoute,
  LocaleWsIdMailIndexRoute: LocaleWsIdMailIndexRoute,
  LocaleUiComponentsIndexRoute: LocaleUiComponentsIndexRoute,
  LocaleWsIdAiChatMyChatbotsNewRoute: LocaleWsIdAiChatMyChatbotsNewRoute,
  LocaleWsIdEducationCoursesCourseIdRoute:
    LocaleWsIdEducationCoursesCourseIdRoute,
  LocaleWsIdFinanceTransactionsCategoriesRoute:
    LocaleWsIdFinanceTransactionsCategoriesRoute,
  LocaleWsIdSettingsInfrastructureAppCoordinationRoute:
    LocaleWsIdSettingsInfrastructureAppCoordinationRoute,
  LocaleWsIdTasksBoardsBoardIdRoute: LocaleWsIdTasksBoardsBoardIdRoute,
  LocaleWsIdUsersGroupsGroupIdRoute: LocaleWsIdUsersGroupsGroupIdRoute,
  LocaleWsIdUsersReportsReportIdRoute: LocaleWsIdUsersReportsReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
