// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/external-projects/members/roles/[roleId]/members/[userId]/route';

export const DELETE = legacyRoute.DELETE;
