import {
  executeCheckE2EEStatus,
  executeCreateEvent,
  executeDeleteEvent,
  executeEnableE2EE,
  executeGetUpcomingEvents,
  executeUpdateEvent,
} from '../tools/executors/calendar';
import {
  executeCreateTransactionCategory,
  executeCreateTransactionTag,
  executeCreateWallet,
  executeDeleteTransaction,
  executeDeleteTransactionCategory,
  executeDeleteTransactionTag,
  executeDeleteWallet,
  executeGetSpendingSummary,
  executeGetTransaction,
  executeListTransactionCategories,
  executeListTransactions,
  executeListTransactionTags,
  executeListWallets,
  executeLogTransaction,
  executeSetDefaultCurrency,
  executeUpdateTransaction,
  executeUpdateTransactionCategory,
  executeUpdateTransactionTag,
  executeUpdateWallet,
} from '../tools/executors/finance';
import {
  executeAddTaskAssignee,
  executeAddTaskLabels,
  executeAddTaskToProject,
  executeCompleteTask,
  executeCreateBoard,
  executeCreateProject,
  executeCreateTask,
  executeCreateTaskLabel,
  executeCreateTaskList,
  executeDeleteBoard,
  executeDeleteProject,
  executeDeleteTask,
  executeDeleteTaskLabel,
  executeDeleteTaskList,
  executeGetMyTasks,
  executeListBoards,
  executeListProjects,
  executeListTaskLabels,
  executeListTaskLists,
  executeRemoveTaskAssignee,
  executeRemoveTaskFromProject,
  executeRemoveTaskLabels,
  executeUpdateBoard,
  executeUpdateProject,
  executeUpdateTask,
  executeUpdateTaskLabel,
  executeUpdateTaskList,
} from '../tools/executors/tasks';
import {
  executeCreateTimeTrackerGoal,
  executeCreateTimeTrackingCategory,
  executeCreateTimeTrackingEntry,
  executeDeleteTimeTrackerGoal,
  executeDeleteTimeTrackingCategory,
  executeDeleteTimeTrackingSession,
  executeGetTimeTrackerGoals,
  executeGetTimeTrackerStats,
  executeGetTimeTrackingSession,
  executeListTimeTrackingCategories,
  executeListTimeTrackingSessions,
  executeMoveTimeTrackingSession,
  executeStartTimer,
  executeStopTimer,
  executeUpdateTimeTrackerGoal,
  executeUpdateTimeTrackingCategory,
  executeUpdateTimeTrackingSession,
} from '../tools/executors/timer';
import type { MiraToolContext } from '../tools/mira-tool-types';

const handlers = {
  get_my_tasks: executeGetMyTasks,
  create_task: executeCreateTask,
  complete_task: executeCompleteTask,
  update_task: executeUpdateTask,
  delete_task: executeDeleteTask,
  list_boards: executeListBoards,
  create_board: executeCreateBoard,
  update_board: executeUpdateBoard,
  delete_board: executeDeleteBoard,
  list_task_lists: executeListTaskLists,
  create_task_list: executeCreateTaskList,
  update_task_list: executeUpdateTaskList,
  delete_task_list: executeDeleteTaskList,
  list_task_labels: executeListTaskLabels,
  create_task_label: executeCreateTaskLabel,
  update_task_label: executeUpdateTaskLabel,
  delete_task_label: executeDeleteTaskLabel,
  add_task_labels: executeAddTaskLabels,
  remove_task_labels: executeRemoveTaskLabels,
  list_projects: executeListProjects,
  create_project: executeCreateProject,
  update_project: executeUpdateProject,
  delete_project: executeDeleteProject,
  add_task_to_project: executeAddTaskToProject,
  remove_task_from_project: executeRemoveTaskFromProject,
  add_task_assignee: executeAddTaskAssignee,
  remove_task_assignee: executeRemoveTaskAssignee,
  get_upcoming_events: executeGetUpcomingEvents,
  create_event: executeCreateEvent,
  update_event: executeUpdateEvent,
  delete_event: executeDeleteEvent,
  check_e2ee_status: executeCheckE2EEStatus,
  enable_e2ee: executeEnableE2EE,
  log_transaction: executeLogTransaction,
  get_spending_summary: executeGetSpendingSummary,
  list_wallets: executeListWallets,
  create_wallet: executeCreateWallet,
  update_wallet: executeUpdateWallet,
  delete_wallet: executeDeleteWallet,
  list_transactions: executeListTransactions,
  get_transaction: executeGetTransaction,
  update_transaction: executeUpdateTransaction,
  delete_transaction: executeDeleteTransaction,
  list_transaction_categories: executeListTransactionCategories,
  create_transaction_category: executeCreateTransactionCategory,
  update_transaction_category: executeUpdateTransactionCategory,
  delete_transaction_category: executeDeleteTransactionCategory,
  list_transaction_tags: executeListTransactionTags,
  create_transaction_tag: executeCreateTransactionTag,
  update_transaction_tag: executeUpdateTransactionTag,
  delete_transaction_tag: executeDeleteTransactionTag,
  start_timer: executeStartTimer,
  stop_timer: executeStopTimer,
  list_time_tracking_sessions: executeListTimeTrackingSessions,
  list_time_tracking_categories: executeListTimeTrackingCategories,
  create_time_tracking_category: executeCreateTimeTrackingCategory,
  update_time_tracking_category: executeUpdateTimeTrackingCategory,
  delete_time_tracking_category: executeDeleteTimeTrackingCategory,
  get_time_tracking_session: executeGetTimeTrackingSession,
  get_time_tracker_stats: executeGetTimeTrackerStats,
  get_time_tracker_goals: executeGetTimeTrackerGoals,
  create_time_tracker_goal: executeCreateTimeTrackerGoal,
  update_time_tracker_goal: executeUpdateTimeTrackerGoal,
  delete_time_tracker_goal: executeDeleteTimeTrackerGoal,
  create_time_tracking_entry: executeCreateTimeTrackingEntry,
  update_time_tracking_session: executeUpdateTimeTrackingSession,
  delete_time_tracking_session: executeDeleteTimeTrackingSession,
  move_time_tracking_session: executeMoveTimeTrackingSession,
  set_default_currency: executeSetDefaultCurrency,
};
export async function executeMeetWorkspaceTool(
  name: string,
  args: Record<string, unknown>,
  context: MiraToolContext
) {
  const handler = handlers[name as keyof typeof handlers];
  if (!handler) return { error: 'Tool unavailable in Meet' };
  return handler(args, context);
}
