// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/payment/migrations/subscriptions/unexisted-workspaces/route';

export const DELETE = legacyRoute.DELETE;
