// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/external-projects/webgl-packages/upload/route';

export const PUT = legacyRoute.PUT;
export const OPTIONS = legacyRoute.OPTIONS;
