// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/inventory/storefronts/[slug]/analytics/events/route';

export const POST = legacyRoute.POST;
