// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/admin/external-projects/[canonicalId]/route';

export const PATCH = legacyRoute.PATCH;
