export function getGlobalHelp() {
  return `${[
    'Tuturuuu CLI',
    '',
    'Usage: ttr <command> [options]',
    '',
    'Commands:',
    '  login [--copy] [--token <token>] [--base-url <url>]',
    '  logout',
    '  upgrade',
    '  resources <setup|status|monitor|run|enable|disable|uninstall>  bound local validation load',
    '  whoami',
    '  host [current|list|use]',
    '  config set-base-url <url>',
    '  box <run|lease|release|preview|agent|shutdown|cache|doctor|setup|repair>',
    '  external <apps|templates|binding|projects>  configure and manage external sites',
    '  calendar <events|schedule|sources|calendars|categories|accounts|auth|provider-calendars|connections>',
    '  finance <wallets|checkpoints|transactions|transfers|categories|tags|budgets|recurring>',
    '  workspaces [list]|use [id]',
    '  boards [list]|use|create|update|delete',
    '  lists [list]|use|create|update --board <id>',
    '  tasks [list]|search|use|get|create|update|done|close|delete|move|bulk',
    '  task-templates [list]|show|create|update|delete|use|import|export',
    '  tiptap [parse|encode|decode|validate]',
    '  labels [list]|use|create',
    '  projects [list]|use|create|get|tasks',
    '  relationships [list]|create|delete <task-id>',
    '',
    'Selection:',
    '  Omit an id on use/get/update/delete/move to pick with up/down/space/enter.',
    '  The personal workspace is selected by default.',
    '',
    'Task list filters:',
    '  tasks                       open personal tasks plus assigned external tasks',
    '  tasks --all                 include done and closed tasks',
    '  tasks --done                completed tasks',
    '  tasks --closed              closed tasks',
    '  tasks --page 2 --page-size 50',
    '  tasks --compact             title, list, and per-task workspace only',
    '',
    'Scoped help:',
    '  ttr resources help',
    '  ttr finance --help',
    '  ttr external --help',
    '  ttr external projects --help',
    '  ttr calendar --help',
    '  ttr calendar events --help',
    '  ttr finance transactions --help',
    '  ttr host --help',
    '  ttr tasks --help',
    '  ttr task-templates --help',
    '  ttr tiptap --help',
    '  ttr box --help',
    '  ttr tasks create --help',
    '  ttr tasks description --help',
    '  ttr help workspaces',
    '',
    'Global options:',
    '  -h, --help                  print help',
    '  -v, --version               print the CLI version',
  ].join('\n')}\n`;
}
