'use client';

export type { LucideIcon, LucideProps } from 'lucide-react';
export {
  ActivitySquare,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Blocks,
  BookOpen,
  BookText,
  Bot,
  Boxes,
  Brain,
  Building,
  Building2,
  Calendar,
  CalendarClock,
  Check,
  Check as CheckIcon,
  CheckCircle2,
  ChevronDown as ChevronDownIcon,
  ChevronLeft,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight,
  ChevronRight as ChevronRightIcon,
  ChevronUp as ChevronUpIcon,
  Circle as CircleIcon,
  Code2,
  Copy,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  Factory,
  FileCode2,
  FileText,
  FingerprintPattern as Fingerprint,
  Folder,
  GitBranch,
  Globe,
  GraduationCap,
  HardHat,
  Heart,
  HeartHandshake,
  History,
  Hotel,
  Layers,
  Lightbulb,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu,
  Menu as MenuIcon,
  MessageSquare,
  Minus as MinusIcon,
  Moon,
  MoreHorizontal,
  MoreHorizontal as MoreHorizontalIcon,
  Package,
  Paintbrush,
  Palette,
  PanelLeft,
  PanelLeft as PanelLeftIcon,
  PanelLeftClose,
  PanelLeftOpen,
  Pill,
  Plus,
  QrCode,
  RefreshCcw,
  RefreshCw,
  Rocket,
  Search,
  Search as SearchIcon,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Smartphone,
  Sparkles,
  SquareMousePointer,
  SquareTerminal,
  Store,
  Sun,
  Target,
  Terminal,
  Text as TextIcon,
  Trash2,
  TrendingUp,
  Trophy,
  User,
  UserPlus,
  Users,
  Utensils,
  Wallet,
  X,
  X as XIcon,
  Zap,
} from 'lucide-react';
