'use client';

export type { LucideIcon, LucideProps } from 'lucide-react';
export {
  ActivitySquare,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BookText,
  Building,
  Calendar,
  CalendarClock,
  Check,
  Check as CheckIcon,
  CheckCircle2,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  Circle as CircleIcon,
  Copy,
  Database,
  Eye,
  EyeOff,
  Factory,
  FileText,
  FingerprintPattern as Fingerprint,
  Globe,
  GraduationCap,
  HardHat,
  HeartHandshake,
  History,
  Hotel,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu as MenuIcon,
  MessageSquare,
  Minus as MinusIcon,
  Moon,
  Paintbrush,
  Palette,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  Pill,
  Plus,
  QrCode,
  RefreshCcw,
  RefreshCw,
  Settings,
  Shield,
  ShieldCheck,
  Smartphone,
  Sparkles,
  SquareMousePointer,
  Store,
  Sun,
  Terminal,
  Trash2,
  User,
  UserPlus,
  Users,
  Utensils,
  Wallet,
  X as XIcon,
} from 'lucide-react';
