// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/workspaces/[wsId]/decline-invite/route';

export const POST = legacyRoute.POST;
