// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/ai/objects/year-plan/route';

export const POST = legacyRoute.POST;
