// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/cron/process-topic-announcement-queue/route';
import { createLegacyHeadHandler } from '@/legacy-api-routes/head';

export const GET = legacyRoute.GET;
export const HEAD = createLegacyHeadHandler(legacyRoute.GET);
export const POST = legacyRoute.POST;
