// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/payment/migrations/subscriptions/cross-check/phase-2/route';

export const POST = legacyRoute.POST;
