// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/workspaces/[wsId]/wallets/[walletId]/checkpoints/[checkpointId]/reconcile/route';

export const POST = legacyRoute.POST;
