// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/auth/accounts/current/route';

export const POST = legacyRoute.POST;
export const PATCH = legacyRoute.PATCH;
export const OPTIONS = legacyRoute.OPTIONS;
