// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/notifications/[id]/route';

export const PATCH = legacyRoute.PATCH;
export const DELETE = legacyRoute.DELETE;
