/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: d1ccd02f8641148a2f077c4425007b83)
interface __BaseEnv_CloudflareEnv {
  LETTIN_MEDIA: R2Bucket;
  NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
  LETTIN_DB: D1Database;
  CF_VERSION_METADATA: WorkerVersionMetadata;
  ASSETS: Fetcher;
  NEXT_PUBLIC_APP_URL: 'https://lettin.tuturuuu.com';
  NEXT_PUBLIC_WEB_APP_URL: 'https://tuturuuu.com';
  NEXT_PUBLIC_SUPABASE_URL: string;
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
  SUPABASE_SECRET_KEY: string;
  WORKER_SELF_REFERENCE: Service<typeof import('./.open-next/worker').default>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./.open-next/worker');
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | 'NEXT_PUBLIC_APP_URL'
        | 'NEXT_PUBLIC_WEB_APP_URL'
        | 'NEXT_PUBLIC_SUPABASE_URL'
        | 'NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY'
        | 'SUPABASE_SECRET_KEY'
      >
    > {}
}
