create table public.demo_table (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

drop table if exists public.demo_table;