alter type "public"."workspace_role_permission" add value if not exists 'view_inventory_dashboard';
alter type "public"."workspace_role_permission" add value if not exists 'view_inventory_catalog';
alter type "public"."workspace_role_permission" add value if not exists 'manage_inventory_catalog';
alter type "public"."workspace_role_permission" add value if not exists 'view_inventory_stock';
alter type "public"."workspace_role_permission" add value if not exists 'adjust_inventory_stock';
alter type "public"."workspace_role_permission" add value if not exists 'manage_inventory_setup';
alter type "public"."workspace_role_permission" add value if not exists 'view_inventory_sales';
alter type "public"."workspace_role_permission" add value if not exists 'create_inventory_sales';
alter type "public"."workspace_role_permission" add value if not exists 'view_inventory_analytics';
alter type "public"."workspace_role_permission" add value if not exists 'view_inventory_audit_logs';

create table if not exists "public"."inventory_owners" (
  "id" uuid primary key default gen_random_uuid(),
  "ws_id" uuid not null references public.workspaces(id) on delete cascade,
  "name" text not null,
  "linked_workspace_user_id" uuid references public.workspace_users(id) on delete set null,
  "avatar_url" text,
  "archived" boolean not null default false,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now()
);

create unique index if not exists "inventory_owners_ws_id_name_key"
on "public"."inventory_owners" using btree ("ws_id", "name");

create index if not exists "inventory_owners_ws_id_archived_created_at_idx"
on "public"."inventory_owners" using btree ("ws_id", "archived", "created_at" desc);

alter table "public"."workspace_products"
add column if not exists "owner_id" uuid;

alter table "public"."workspace_products"
add column if not exists "finance_category_id" uuid references public.transaction_categories(id) on delete set null;

insert into "public"."inventory_owners" ("ws_id", "name")
select w.id, 'Unassigned'
from public.workspaces w
where not exists (
  select 1
  from public.inventory_owners io
  where io.ws_id = w.id
    and io.name = 'Unassigned'
);

update "public"."workspace_products" wp
set "owner_id" = io.id
from public.inventory_owners io
where io.ws_id = wp.ws_id
  and io.name = 'Unassigned'
  and wp.owner_id is null;

alter table "public"."workspace_products"
alter column "owner_id" set not null;

alter table "public"."workspace_products"
drop constraint if exists "workspace_products_owner_id_fkey";

alter table "public"."workspace_products"
add constraint "workspace_products_owner_id_fkey"
foreign key ("owner_id") references public.inventory_owners(id) on delete restrict;

create index if not exists "workspace_products_owner_id_idx"
on "public"."workspace_products" using btree ("owner_id");

create index if not exists "workspace_products_finance_category_id_idx"
on "public"."workspace_products" using btree ("finance_category_id");

alter table "public"."finance_invoice_products"
add column if not exists "owner_id" uuid;

alter table "public"."finance_invoice_products"
add column if not exists "owner_name" text not null default '';

create index if not exists "finance_invoice_products_owner_id_idx"
on "public"."finance_invoice_products" using btree ("owner_id");

create table if not exists "public"."inventory_audit_logs" (
  "id" bigint generated by default as identity primary key,
  "ws_id" uuid not null references public.workspaces(id) on delete cascade,
  "event_kind" text not null,
  "entity_kind" text not null,
  "entity_id" uuid,
  "entity_label" text,
  "summary" text not null,
  "changed_fields" text[] not null default '{}',
  "before" jsonb,
  "after" jsonb,
  "actor_auth_uid" uuid references auth.users(id) on delete set null,
  "actor_workspace_user_id" uuid references public.workspace_users(id) on delete set null,
  "occurred_at" timestamp with time zone not null default now(),
  "source" text not null default 'live'
);

create index if not exists "inventory_audit_logs_ws_id_occurred_at_idx"
on "public"."inventory_audit_logs" using btree ("ws_id", "occurred_at" desc);

create index if not exists "inventory_audit_logs_ws_id_entity_kind_idx"
on "public"."inventory_audit_logs" using btree ("ws_id", "entity_kind", "occurred_at" desc);

alter table "public"."inventory_owners" enable row level security;
alter table "public"."inventory_audit_logs" enable row level security;

drop policy if exists "Allow members to view inventory owners" on "public"."inventory_owners";
create policy "Allow members to view inventory owners"
on "public"."inventory_owners"
as permissive
for select
to authenticated
using (
  public.has_workspace_permission(ws_id, auth.uid(), 'view_inventory_catalog')
  or public.has_workspace_permission(ws_id, auth.uid(), 'view_inventory_dashboard')
  or public.has_workspace_permission(ws_id, auth.uid(), 'manage_inventory_catalog')
  or public.has_workspace_permission(ws_id, auth.uid(), 'manage_inventory_setup')
  or public.has_workspace_permission(ws_id, auth.uid(), 'view_inventory')
);

drop policy if exists "Allow members to create inventory owners" on "public"."inventory_owners";
create policy "Allow members to create inventory owners"
on "public"."inventory_owners"
as permissive
for insert
to authenticated
with check (
  public.has_workspace_permission(ws_id, auth.uid(), 'manage_inventory_setup')
  or public.has_workspace_permission(ws_id, auth.uid(), 'create_inventory')
  or public.has_workspace_permission(ws_id, auth.uid(), 'update_inventory')
);

drop policy if exists "Allow members to update inventory owners" on "public"."inventory_owners";
create policy "Allow members to update inventory owners"
on "public"."inventory_owners"
as permissive
for update
to authenticated
using (
  public.has_workspace_permission(ws_id, auth.uid(), 'manage_inventory_setup')
  or public.has_workspace_permission(ws_id, auth.uid(), 'update_inventory')
)
with check (
  public.has_workspace_permission(ws_id, auth.uid(), 'manage_inventory_setup')
  or public.has_workspace_permission(ws_id, auth.uid(), 'update_inventory')
);

drop policy if exists "Allow members to delete inventory owners" on "public"."inventory_owners";
create policy "Allow members to delete inventory owners"
on "public"."inventory_owners"
as permissive
for delete
to authenticated
using (
  public.has_workspace_permission(ws_id, auth.uid(), 'manage_inventory_setup')
  or public.has_workspace_permission(ws_id, auth.uid(), 'delete_inventory')
);

drop policy if exists "Allow members to view inventory audit logs" on "public"."inventory_audit_logs";
create policy "Allow members to view inventory audit logs"
on "public"."inventory_audit_logs"
as permissive
for select
to authenticated
using (
  public.has_workspace_permission(ws_id, auth.uid(), 'view_inventory_audit_logs')
  or public.has_workspace_permission(ws_id, auth.uid(), 'manage_workspace_audit_logs')
);
