create table "public"."quiz_options" (
    "id" uuid not null default gen_random_uuid(),
    "quiz_id" uuid not null,
    "value" text not null,
    "points" real,
    "is_correct" boolean not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."quiz_options" enable row level security;

create table "public"."workspace_course_modules" (
    "id" bigint generated by default as identity not null,
    "name" text not null default ''::text,
    "is_published" boolean not null default false,
    "is_public" boolean not null default false,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."workspace_course_modules" enable row level security;

create table "public"."workspace_courses" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null default ''::text,
    "is_published" boolean not null default false,
    "is_public" boolean not null default false,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."workspace_courses" enable row level security;

create table "public"."workspace_flashcards" (
    "id" uuid not null default gen_random_uuid(),
    "front" text not null,
    "back" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."workspace_flashcards" enable row level security;

create table "public"."workspace_quizzes" (
    "id" uuid not null default gen_random_uuid(),
    "question" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."workspace_quizzes" enable row level security;

CREATE UNIQUE INDEX quiz_options_pkey ON public.quiz_options USING btree (id);

CREATE UNIQUE INDEX workspace_course_modules_pkey ON public.workspace_course_modules USING btree (id);

CREATE UNIQUE INDEX workspace_courses_pkey ON public.workspace_courses USING btree (id);

CREATE UNIQUE INDEX workspace_flashcards_pkey ON public.workspace_flashcards USING btree (id);

CREATE UNIQUE INDEX workspace_quizzes_pkey ON public.workspace_quizzes USING btree (id);

alter table "public"."quiz_options" add constraint "quiz_options_pkey" PRIMARY KEY using index "quiz_options_pkey";

alter table "public"."workspace_course_modules" add constraint "workspace_course_modules_pkey" PRIMARY KEY using index "workspace_course_modules_pkey";

alter table "public"."workspace_courses" add constraint "workspace_courses_pkey" PRIMARY KEY using index "workspace_courses_pkey";

alter table "public"."workspace_flashcards" add constraint "workspace_flashcards_pkey" PRIMARY KEY using index "workspace_flashcards_pkey";

alter table "public"."workspace_quizzes" add constraint "workspace_quizzes_pkey" PRIMARY KEY using index "workspace_quizzes_pkey";

alter table "public"."quiz_options" add constraint "quiz_options_quiz_id_fkey" FOREIGN KEY (quiz_id) REFERENCES workspace_quizzes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."quiz_options" validate constraint "quiz_options_quiz_id_fkey";

grant delete on table "public"."quiz_options" to "anon";

grant insert on table "public"."quiz_options" to "anon";

grant references on table "public"."quiz_options" to "anon";

grant select on table "public"."quiz_options" to "anon";

grant trigger on table "public"."quiz_options" to "anon";

grant truncate on table "public"."quiz_options" to "anon";

grant update on table "public"."quiz_options" to "anon";

grant delete on table "public"."quiz_options" to "authenticated";

grant insert on table "public"."quiz_options" to "authenticated";

grant references on table "public"."quiz_options" to "authenticated";

grant select on table "public"."quiz_options" to "authenticated";

grant trigger on table "public"."quiz_options" to "authenticated";

grant truncate on table "public"."quiz_options" to "authenticated";

grant update on table "public"."quiz_options" to "authenticated";

grant delete on table "public"."quiz_options" to "service_role";

grant insert on table "public"."quiz_options" to "service_role";

grant references on table "public"."quiz_options" to "service_role";

grant select on table "public"."quiz_options" to "service_role";

grant trigger on table "public"."quiz_options" to "service_role";

grant truncate on table "public"."quiz_options" to "service_role";

grant update on table "public"."quiz_options" to "service_role";

grant delete on table "public"."workspace_course_modules" to "anon";

grant insert on table "public"."workspace_course_modules" to "anon";

grant references on table "public"."workspace_course_modules" to "anon";

grant select on table "public"."workspace_course_modules" to "anon";

grant trigger on table "public"."workspace_course_modules" to "anon";

grant truncate on table "public"."workspace_course_modules" to "anon";

grant update on table "public"."workspace_course_modules" to "anon";

grant delete on table "public"."workspace_course_modules" to "authenticated";

grant insert on table "public"."workspace_course_modules" to "authenticated";

grant references on table "public"."workspace_course_modules" to "authenticated";

grant select on table "public"."workspace_course_modules" to "authenticated";

grant trigger on table "public"."workspace_course_modules" to "authenticated";

grant truncate on table "public"."workspace_course_modules" to "authenticated";

grant update on table "public"."workspace_course_modules" to "authenticated";

grant delete on table "public"."workspace_course_modules" to "service_role";

grant insert on table "public"."workspace_course_modules" to "service_role";

grant references on table "public"."workspace_course_modules" to "service_role";

grant select on table "public"."workspace_course_modules" to "service_role";

grant trigger on table "public"."workspace_course_modules" to "service_role";

grant truncate on table "public"."workspace_course_modules" to "service_role";

grant update on table "public"."workspace_course_modules" to "service_role";

grant delete on table "public"."workspace_courses" to "anon";

grant insert on table "public"."workspace_courses" to "anon";

grant references on table "public"."workspace_courses" to "anon";

grant select on table "public"."workspace_courses" to "anon";

grant trigger on table "public"."workspace_courses" to "anon";

grant truncate on table "public"."workspace_courses" to "anon";

grant update on table "public"."workspace_courses" to "anon";

grant delete on table "public"."workspace_courses" to "authenticated";

grant insert on table "public"."workspace_courses" to "authenticated";

grant references on table "public"."workspace_courses" to "authenticated";

grant select on table "public"."workspace_courses" to "authenticated";

grant trigger on table "public"."workspace_courses" to "authenticated";

grant truncate on table "public"."workspace_courses" to "authenticated";

grant update on table "public"."workspace_courses" to "authenticated";

grant delete on table "public"."workspace_courses" to "service_role";

grant insert on table "public"."workspace_courses" to "service_role";

grant references on table "public"."workspace_courses" to "service_role";

grant select on table "public"."workspace_courses" to "service_role";

grant trigger on table "public"."workspace_courses" to "service_role";

grant truncate on table "public"."workspace_courses" to "service_role";

grant update on table "public"."workspace_courses" to "service_role";

grant delete on table "public"."workspace_flashcards" to "anon";

grant insert on table "public"."workspace_flashcards" to "anon";

grant references on table "public"."workspace_flashcards" to "anon";

grant select on table "public"."workspace_flashcards" to "anon";

grant trigger on table "public"."workspace_flashcards" to "anon";

grant truncate on table "public"."workspace_flashcards" to "anon";

grant update on table "public"."workspace_flashcards" to "anon";

grant delete on table "public"."workspace_flashcards" to "authenticated";

grant insert on table "public"."workspace_flashcards" to "authenticated";

grant references on table "public"."workspace_flashcards" to "authenticated";

grant select on table "public"."workspace_flashcards" to "authenticated";

grant trigger on table "public"."workspace_flashcards" to "authenticated";

grant truncate on table "public"."workspace_flashcards" to "authenticated";

grant update on table "public"."workspace_flashcards" to "authenticated";

grant delete on table "public"."workspace_flashcards" to "service_role";

grant insert on table "public"."workspace_flashcards" to "service_role";

grant references on table "public"."workspace_flashcards" to "service_role";

grant select on table "public"."workspace_flashcards" to "service_role";

grant trigger on table "public"."workspace_flashcards" to "service_role";

grant truncate on table "public"."workspace_flashcards" to "service_role";

grant update on table "public"."workspace_flashcards" to "service_role";

grant delete on table "public"."workspace_quizzes" to "anon";

grant insert on table "public"."workspace_quizzes" to "anon";

grant references on table "public"."workspace_quizzes" to "anon";

grant select on table "public"."workspace_quizzes" to "anon";

grant trigger on table "public"."workspace_quizzes" to "anon";

grant truncate on table "public"."workspace_quizzes" to "anon";

grant update on table "public"."workspace_quizzes" to "anon";

grant delete on table "public"."workspace_quizzes" to "authenticated";

grant insert on table "public"."workspace_quizzes" to "authenticated";

grant references on table "public"."workspace_quizzes" to "authenticated";

grant select on table "public"."workspace_quizzes" to "authenticated";

grant trigger on table "public"."workspace_quizzes" to "authenticated";

grant truncate on table "public"."workspace_quizzes" to "authenticated";

grant update on table "public"."workspace_quizzes" to "authenticated";

grant delete on table "public"."workspace_quizzes" to "service_role";

grant insert on table "public"."workspace_quizzes" to "service_role";

grant references on table "public"."workspace_quizzes" to "service_role";

grant select on table "public"."workspace_quizzes" to "service_role";

grant trigger on table "public"."workspace_quizzes" to "service_role";

grant truncate on table "public"."workspace_quizzes" to "service_role";

grant update on table "public"."workspace_quizzes" to "service_role";


