// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/user-groups/sessions/occurrences/route';

export const POST = legacyRoute.POST;
