// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnzaAExi_UAfVE3Viv58eGwYzFebyhVBM',
    appId: '1:21140998358:web:a7d974d24b56e3e40de177',
    messagingSenderId: '21140998358',
    projectId: 'tuturuuu-mobile',
    authDomain: 'tuturuuu-mobile.firebaseapp.com',
    storageBucket: 'tuturuuu-mobile.firebasestorage.app',
    measurementId: 'G-CC7ZQL2TM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_STZHQ6BNgMdVtJ0bMuyk31x9xAVw65c',
    appId: '1:21140998358:android:acb63cb6b5e3e6ec0de177',
    messagingSenderId: '21140998358',
    projectId: 'tuturuuu-mobile',
    storageBucket: 'tuturuuu-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmL2LveXmjwuwWkJDFMNtLglVqd2mT0zw',
    appId: '1:21140998358:ios:b943cf725f57d5500de177',
    messagingSenderId: '21140998358',
    projectId: 'tuturuuu-mobile',
    storageBucket: 'tuturuuu-mobile.firebasestorage.app',
    iosClientId:
        '21140998358-slkc76eli9ggd8d75osab1bq6rdqlnni.apps.googleusercontent.com',
    iosBundleId: 'com.tuturuuu.app.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmL2LveXmjwuwWkJDFMNtLglVqd2mT0zw',
    appId: '1:21140998358:ios:b943cf725f57d5500de177',
    messagingSenderId: '21140998358',
    projectId: 'tuturuuu-mobile',
    storageBucket: 'tuturuuu-mobile.firebasestorage.app',
    iosClientId:
        '21140998358-slkc76eli9ggd8d75osab1bq6rdqlnni.apps.googleusercontent.com',
    iosBundleId: 'com.tuturuuu.app.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnzaAExi_UAfVE3Viv58eGwYzFebyhVBM',
    appId: '1:21140998358:web:a8f5ab9478c52e6e0de177',
    messagingSenderId: '21140998358',
    projectId: 'tuturuuu-mobile',
    authDomain: 'tuturuuu-mobile.firebaseapp.com',
    storageBucket: 'tuturuuu-mobile.firebasestorage.app',
    measurementId: 'G-JBJ7CWE6HL',
  );
}
