// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/workspaces/[wsId]/transfers/route';

export const POST = legacyRoute.POST;
export const PUT = legacyRoute.PUT;
export const PATCH = legacyRoute.PATCH;
