// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import { createLegacyHeadHandler } from '@/legacy-api-routes/head';
import * as legacyRoute from '@/legacy-api-routes/workspaces/[wsId]/members/enhanced/route';

export const GET = legacyRoute.GET;
export const HEAD = createLegacyHeadHandler(legacyRoute.GET);
