// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/personal/route';

export const POST = legacyRoute.POST;
export const PATCH = legacyRoute.PATCH;
