import type { PermissionId } from '@tuturuuu/types';
import type { MiraToolName } from './mira-tool-names';

export const MIRA_TOOL_DIRECTORY: Record<MiraToolName, string> = {
  select_tools: 'Present user with tool selection options',
  get_my_tasks: 'Get your tasks by status (overdue, today, upcoming)',
  create_task: 'Create a new task',
  complete_task: 'Mark a task as completed',
  update_task: 'Update task fields (name, priority, dates, etc.)',
  delete_task: 'Soft-delete a task',
  list_boards: 'List all task boards in the workspace',
  create_board: 'Create a new task board',
  update_board: 'Update a task board name',
  delete_board: 'Delete a task board',
  list_task_lists: 'List columns/lists within a board',
  create_task_list: 'Create a new list in a board',
  update_task_list: 'Update a task list',
  delete_task_list: 'Delete a task list',
  list_task_labels: 'List workspace task labels',
  create_task_label: 'Create a task label',
  update_task_label: 'Update a task label',
  delete_task_label: 'Delete a task label',
  add_task_labels: 'Assign labels to a task',
  remove_task_labels: 'Remove labels from a task',
  list_projects: 'List workspace projects',
  create_project: 'Create a project',
  update_project: 'Update a project',
  delete_project: 'Delete a project',
  add_task_to_project: 'Link a task to a project',
  remove_task_from_project: 'Unlink a task from a project',
  add_task_assignee: 'Assign a user to a task',
  remove_task_assignee: 'Remove a user from a task',
  get_upcoming_events: 'Get calendar events for the next N days',
  create_event: 'Create a calendar event',
  update_event: 'Update a calendar event',
  delete_event: 'Delete a calendar event',
  check_e2ee_status: 'Check E2EE encryption status for calendar',
  enable_e2ee: 'Enable end-to-end encryption for calendar events',
  log_transaction: 'Log an income or expense transaction',
  get_spending_summary: 'Get spending/income summary for N days',
  list_wallets: 'List workspace wallets',
  create_wallet: 'Create a new wallet',
  update_wallet: 'Update wallet details',
  delete_wallet: 'Delete a wallet',
  list_transactions: 'List recent transactions (with filters)',
  get_transaction: 'Get a single transaction by ID',
  update_transaction: 'Update a transaction',
  delete_transaction: 'Delete a transaction',
  list_transaction_categories: 'List transaction categories',
  create_transaction_category: 'Create a transaction category',
  update_transaction_category: 'Update a transaction category',
  delete_transaction_category: 'Delete a transaction category',
  list_transaction_tags: 'List transaction tags',
  create_transaction_tag: 'Create a transaction tag',
  update_transaction_tag: 'Update a transaction tag',
  delete_transaction_tag: 'Delete a transaction tag',
  set_default_currency: 'Set the default currency for the workspace',
  start_timer: 'Start a time tracking session',
  stop_timer: 'Stop the running time tracking session',
  list_time_tracking_sessions:
    'List your time tracking history with pagination and filters',
  get_time_tracking_session: 'Get one time tracking session by ID',
  create_time_tracking_entry:
    'Create a stopped/manual time tracking history entry. If approval is required, it returns requiresApproval with next-step guidance for the user/UI to handle approval.',
  update_time_tracking_session: 'Update a time tracking history session',
  delete_time_tracking_session: 'Delete a time tracking history session',
  move_time_tracking_session:
    'Move a session to another workspace if you are a member of both',
  remember: 'Save a fact/preference about the user',
  recall: 'Search saved memories',
  list_memories: 'List saved memories with filters/pagination',
  delete_memory: 'Delete a saved memory',
  merge_memories: 'Merge multiple memories into one',
  create_image: 'Generate an image from a text description',
  google_search:
    'Search the web for real-time info (news, prices, weather, facts).',
  convert_file_to_markdown:
    'Convert attached files (Excel, Word, PowerPoint, PDF, etc.) into markdown via MarkItDown. Costs 100 credits per request.',
  list_accessible_workspaces:
    'List every workspace you can access, with member counts',
  get_workspace_context:
    'Show the current workspace context used for tasks, calendar, and finance queries',
  set_workspace_context:
    'Switch the current workspace context for task, calendar, and finance tools',
  update_my_settings: "Update the assistant's personality settings",
  set_theme: 'Switch dark mode, light mode, or system theme',
  render_ui:
    'Generate an interactive, actionable UI component or widget instead of plain text when it significantly improves user experience (e.g. for forms, dashboards, blog-like insight layouts, or data visualization).',
  list_workspace_members: 'List all members of the workspace',
  update_user_name: "Update the user's display name or full name",
  set_immersive_mode: 'Enter or exit immersive fullscreen mode for the chat',
  no_action_needed: 'Conversational message — no tool action required',
};

export const MIRA_TOOL_PERMISSIONS: Partial<
  Record<MiraToolName, PermissionId | PermissionId[]>
> = {
  create_task: 'manage_projects',
  complete_task: 'manage_projects',
  update_task: 'manage_projects',
  delete_task: 'manage_projects',
  create_board: 'manage_projects',
  update_board: 'manage_projects',
  delete_board: 'manage_projects',
  create_task_list: 'manage_projects',
  update_task_list: 'manage_projects',
  delete_task_list: 'manage_projects',
  create_task_label: 'manage_projects',
  update_task_label: 'manage_projects',
  delete_task_label: 'manage_projects',
  add_task_labels: 'manage_projects',
  remove_task_labels: 'manage_projects',
  create_project: 'manage_projects',
  update_project: 'manage_projects',
  delete_project: 'manage_projects',
  add_task_to_project: 'manage_projects',
  remove_task_from_project: 'manage_projects',
  add_task_assignee: 'manage_projects',
  remove_task_assignee: 'manage_projects',
  get_upcoming_events: 'manage_calendar',
  create_event: 'manage_calendar',
  update_event: 'manage_calendar',
  delete_event: 'manage_calendar',
  check_e2ee_status: 'manage_calendar',
  enable_e2ee: 'manage_calendar',
  log_transaction: 'manage_finance',
  get_spending_summary: 'manage_finance',
  list_wallets: 'manage_finance',
  create_wallet: 'manage_finance',
  update_wallet: 'manage_finance',
  delete_wallet: 'manage_finance',
  list_transactions: 'manage_finance',
  get_transaction: 'manage_finance',
  update_transaction: 'manage_finance',
  delete_transaction: 'manage_finance',
  list_transaction_categories: 'manage_finance',
  create_transaction_category: 'manage_finance',
  update_transaction_category: 'manage_finance',
  delete_transaction_category: 'manage_finance',
  list_transaction_tags: 'manage_finance',
  create_transaction_tag: 'manage_finance',
  update_transaction_tag: 'manage_finance',
  delete_transaction_tag: 'manage_finance',
  set_default_currency: 'manage_finance',
};
