// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import {
  createLegacyGetHandler,
  createLegacyHeadHandler,
} from '@/legacy-api-routes/head';
import * as legacyRoute from '@/legacy-api-routes/v1/auth/qr-login/challenges/[challengeId]/route';

export const GET = createLegacyGetHandler(legacyRoute.GET);
export const HEAD = createLegacyHeadHandler(GET);
export const OPTIONS = legacyRoute.OPTIONS;
