/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 497014f4c3e4eb40478ad6fa65c01c46)
interface __BaseEnv_CloudflareEnv {
  NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
  IMAGES: ImagesBinding;
  ASSETS: Fetcher;
  NEXT_PUBLIC_MEETING_APP: 'parley';
  NEXT_PUBLIC_APP_URL: 'https://parley.tuturuuu.com';
  NEXT_PUBLIC_WEB_APP_URL: 'https://tuturuuu.com';
  MEET_REALTIME_URL: 'wss://meet-realtime.tuturuuu.com/realtime';
  MEET_REALTIME_TOKEN_SECRET: string;
  NEXT_PUBLIC_SUPABASE_URL: string;
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
  SUPABASE_SECRET_KEY: string;
  MEET_LIVE: DurableObjectNamespace /* MeetLiveDurableObject from tuturuuu-meet */;
  WORKER_SELF_REFERENCE: Service<typeof import('./cloudflare/worker').default>;
  MEETING_AI_PROVIDER: Service /* entrypoint MeetingAIProvider from tuturuuu-meet */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./cloudflare/worker');
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | 'NEXT_PUBLIC_MEETING_APP'
        | 'NEXT_PUBLIC_APP_URL'
        | 'NEXT_PUBLIC_WEB_APP_URL'
        | 'MEET_REALTIME_URL'
        | 'MEET_REALTIME_TOKEN_SECRET'
        | 'NEXT_PUBLIC_SUPABASE_URL'
        | 'NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY'
        | 'SUPABASE_SECRET_KEY'
      >
    > {}
}
