// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/ai/temp-auth/token/route';

export const POST = legacyRoute.POST;
