// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/notes/[noteId]/convert-to-project/route';

export const POST = legacyRoute.POST;
