export const FILE_DIGEST_MODEL = 'google/gemini-3.1-flash-lite-preview';
export const CHAT_FILE_DIGEST_VERSION = 1;
export const MAX_AUTO_INJECTED_ATTACHMENTS = 8;
export const MAX_AUTO_INJECTED_DIGEST_CHARACTERS = 12_000;
export const MAX_STORED_EXTRACTED_MARKDOWN_CHARACTERS = 80_000;
export const MAX_MARKITDOWN_DIGEST_CHARACTERS = 120_000;
export const DIGEST_CHUNK_TARGET_CHARACTERS = 12_000;
export const DIGEST_CHUNK_HARD_LIMIT_CHARACTERS = 24_000;
