export function getSettingsRoutePanelHrefs(
  wsId?: string
): Record<string, string> {
  if (!wsId) return {};

  return {
    api_keys: `/${wsId}/api-keys`,
    infrastructure_abuse_events: `/${wsId}/infrastructure/abuse-events`,
    infrastructure_abuse_intelligence: `/${wsId}/infrastructure/abuse-intelligence`,
    infrastructure_ai_agents: `/${wsId}/infrastructure/ai-agents`,
    infrastructure_ai_credits: `/${wsId}/infrastructure/ai-credits`,
    infrastructure_ai_whitelisted_domains: `/${wsId}/infrastructure/ai/whitelist/domains`,
    infrastructure_ai_whitelisted_emails: `/${wsId}/infrastructure/ai/whitelist/emails`,
    infrastructure_app_coordination: `/${wsId}/infrastructure/app-coordination`,
    infrastructure_blocked_ips: `/${wsId}/infrastructure/blocked-ips`,
    infrastructure_calendar_sync: `/${wsId}/infrastructure/calendar-sync`,
    infrastructure_changelog: `/${wsId}/infrastructure/changelog`,
    infrastructure_cron_whitelisted_domains: `/${wsId}/infrastructure/cron/whitelist/domains`,
    infrastructure_devboxes: `/${wsId}/infrastructure/devboxes`,
    infrastructure_email_audit: `/${wsId}/infrastructure/email-audit`,
    infrastructure_email_blacklist: `/${wsId}/infrastructure/email-blacklist`,
    infrastructure_email_templates: `/${wsId}/infrastructure/email-templates`,
    infrastructure_entity_creation_limits: `/${wsId}/infrastructure/entity-creation-limits`,
    infrastructure_external_apps: `/${wsId}/infrastructure/external-apps`,
    infrastructure_github_bot: `/${wsId}/infrastructure/github-bot`,
    infrastructure_mobile_deployment: `/${wsId}/infrastructure/mobile-deployment`,
    infrastructure_mobile_versions: `/${wsId}/infrastructure/mobile-versions`,
    infrastructure_monitoring: `/${wsId}/infrastructure/monitoring`,
    infrastructure_monitoring_analytics: `/${wsId}/infrastructure/monitoring/analytics`,
    infrastructure_monitoring_cron: `/${wsId}/infrastructure/monitoring/cron`,
    infrastructure_monitoring_logs: `/${wsId}/infrastructure/monitoring/logs`,
    infrastructure_monitoring_observability: `/${wsId}/infrastructure/monitoring/observability`,
    infrastructure_monitoring_projects: `/${wsId}/infrastructure/monitoring/projects`,
    infrastructure_monitoring_requests: `/${wsId}/infrastructure/monitoring/requests`,
    infrastructure_monitoring_resources: `/${wsId}/infrastructure/monitoring/resources`,
    infrastructure_monitoring_rollouts: `/${wsId}/infrastructure/monitoring/deployments`,
    infrastructure_monitoring_stress_tests: `/${wsId}/infrastructure/monitoring/stress-tests`,
    infrastructure_monitoring_watcher_logs: `/${wsId}/infrastructure/monitoring/watcher-logs`,
    infrastructure_otp_limits: `/${wsId}/infrastructure/otp-limits`,
    infrastructure_overview: `/${wsId}/infrastructure`,
    infrastructure_post_email_queue: `/${wsId}/infrastructure/post-email-queue`,
    infrastructure_push_notifications: `/${wsId}/infrastructure/push-notifications`,
    infrastructure_rate_limits: `/${wsId}/infrastructure/rate-limits`,
    infrastructure_realtime: `/${wsId}/infrastructure/realtime`,
    infrastructure_timezones: `/${wsId}/infrastructure/timezones`,
    infrastructure_translations: `/${wsId}/infrastructure/translations`,
    infrastructure_users: `/${wsId}/infrastructure/users`,
    infrastructure_workspaces: `/${wsId}/infrastructure/workspaces`,
    inquiries: `/${wsId}/inquiries`,
    integrations: `/${wsId}/integrations`,
    migrations: `/${wsId}/migrations`,
    platform_billing: `/${wsId}/platform/billing`,
    platform_roles: `/${wsId}/platform/roles`,
    secrets: `/${wsId}/secrets`,
    usage: `/${wsId}/usage`,
    workspace_reports: `/${wsId}/settings/reports`,
  };
}
