// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/users/me/full-name/route';

export const PATCH = legacyRoute.PATCH;
