// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/webhooks/ai-agents/[adapter]/[channelId]/route';

export const POST = legacyRoute.POST;
