drop policy "Enable all access for current user" on "public"."nova_user_problem_history";

revoke delete on table "public"."nova_user_problem_history" from "anon";

revoke insert on table "public"."nova_user_problem_history" from "anon";

revoke references on table "public"."nova_user_problem_history" from "anon";

revoke select on table "public"."nova_user_problem_history" from "anon";

revoke trigger on table "public"."nova_user_problem_history" from "anon";

revoke truncate on table "public"."nova_user_problem_history" from "anon";

revoke update on table "public"."nova_user_problem_history" from "anon";

revoke delete on table "public"."nova_user_problem_history" from "authenticated";

revoke insert on table "public"."nova_user_problem_history" from "authenticated";

revoke references on table "public"."nova_user_problem_history" from "authenticated";

revoke select on table "public"."nova_user_problem_history" from "authenticated";

revoke trigger on table "public"."nova_user_problem_history" from "authenticated";

revoke truncate on table "public"."nova_user_problem_history" from "authenticated";

revoke update on table "public"."nova_user_problem_history" from "authenticated";

revoke delete on table "public"."nova_user_problem_history" from "service_role";

revoke insert on table "public"."nova_user_problem_history" from "service_role";

revoke references on table "public"."nova_user_problem_history" from "service_role";

revoke select on table "public"."nova_user_problem_history" from "service_role";

revoke trigger on table "public"."nova_user_problem_history" from "service_role";

revoke truncate on table "public"."nova_user_problem_history" from "service_role";

revoke update on table "public"."nova_user_problem_history" from "service_role";

alter table "public"."nova_user_problem_history" drop constraint "nova_users_problem_history_problem_id_fkey";

alter table "public"."nova_user_problem_history" drop constraint "nova_users_problem_history_userId_fkey";

alter table "public"."nova_user_problem_history" drop constraint "nova_users_problem_history_pkey";

drop index if exists "public"."nova_users_problem_history_pkey";

drop table "public"."nova_user_problem_history";

create table "public"."nova_submissions" (
    "id" bigint generated by default as identity not null,
    "problem_id" uuid,
    "user_id" uuid,
    "score" real,
    "feedback" text,
    "user_prompt" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."nova_submissions" enable row level security;

CREATE UNIQUE INDEX nova_users_problem_history_pkey ON public.nova_submissions USING btree (id);

alter table "public"."nova_submissions" add constraint "nova_users_problem_history_pkey" PRIMARY KEY using index "nova_users_problem_history_pkey";

alter table "public"."nova_submissions" add constraint "nova_users_problem_history_problem_id_fkey" FOREIGN KEY (problem_id) REFERENCES nova_problems(id) not valid;

alter table "public"."nova_submissions" validate constraint "nova_users_problem_history_problem_id_fkey";

alter table "public"."nova_submissions" add constraint "nova_users_problem_history_userId_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."nova_submissions" validate constraint "nova_users_problem_history_userId_fkey";

grant delete on table "public"."nova_submissions" to "anon";

grant insert on table "public"."nova_submissions" to "anon";

grant references on table "public"."nova_submissions" to "anon";

grant select on table "public"."nova_submissions" to "anon";

grant trigger on table "public"."nova_submissions" to "anon";

grant truncate on table "public"."nova_submissions" to "anon";

grant update on table "public"."nova_submissions" to "anon";

grant delete on table "public"."nova_submissions" to "authenticated";

grant insert on table "public"."nova_submissions" to "authenticated";

grant references on table "public"."nova_submissions" to "authenticated";

grant select on table "public"."nova_submissions" to "authenticated";

grant trigger on table "public"."nova_submissions" to "authenticated";

grant truncate on table "public"."nova_submissions" to "authenticated";

grant update on table "public"."nova_submissions" to "authenticated";

grant delete on table "public"."nova_submissions" to "service_role";

grant insert on table "public"."nova_submissions" to "service_role";

grant references on table "public"."nova_submissions" to "service_role";

grant select on table "public"."nova_submissions" to "service_role";

grant trigger on table "public"."nova_submissions" to "service_role";

grant truncate on table "public"."nova_submissions" to "service_role";

grant update on table "public"."nova_submissions" to "service_role";

create policy "Enable all access for current user"
on "public"."nova_submissions"
as permissive
for all
to public
using ((user_id = auth.uid()))
with check ((user_id = auth.uid()));



