revoke delete on table "public"."nova_challenge_criterias" from "anon";

revoke insert on table "public"."nova_challenge_criterias" from "anon";

revoke references on table "public"."nova_challenge_criterias" from "anon";

revoke select on table "public"."nova_challenge_criterias" from "anon";

revoke trigger on table "public"."nova_challenge_criterias" from "anon";

revoke truncate on table "public"."nova_challenge_criterias" from "anon";

revoke update on table "public"."nova_challenge_criterias" from "anon";

revoke delete on table "public"."nova_challenge_criterias" from "authenticated";

revoke insert on table "public"."nova_challenge_criterias" from "authenticated";

revoke references on table "public"."nova_challenge_criterias" from "authenticated";

revoke select on table "public"."nova_challenge_criterias" from "authenticated";

revoke trigger on table "public"."nova_challenge_criterias" from "authenticated";

revoke truncate on table "public"."nova_challenge_criterias" from "authenticated";

revoke update on table "public"."nova_challenge_criterias" from "authenticated";

revoke delete on table "public"."nova_challenge_criterias" from "service_role";

revoke insert on table "public"."nova_challenge_criterias" from "service_role";

revoke references on table "public"."nova_challenge_criterias" from "service_role";

revoke select on table "public"."nova_challenge_criterias" from "service_role";

revoke trigger on table "public"."nova_challenge_criterias" from "service_role";

revoke truncate on table "public"."nova_challenge_criterias" from "service_role";

revoke update on table "public"."nova_challenge_criterias" from "service_role";

alter table "public"."nova_challenge_criterias" drop constraint "nova_challenge_criterias_challenge_id_fkey";

alter table "public"."nova_problem_criteria_scores" drop constraint "nova_problem_criteria_scores_criteria_id_fkey";

alter table "public"."nova_challenge_criterias" drop constraint "nova_challenge_criterias_pkey";

drop index if exists "public"."nova_challenge_criterias_pkey";

drop table "public"."nova_challenge_criterias";

create table "public"."nova_challenge_criteria" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "description" text not null,
    "challenge_id" uuid not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."nova_challenge_criteria" enable row level security;

create table "public"."nova_submission_outputs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "output" text not null,
    "submission_id" bigint not null
);


alter table "public"."nova_submission_outputs" enable row level security;

alter table "public"."nova_submissions" drop column "input";

alter table "public"."nova_submissions" drop column "output";

alter table "public"."nova_submissions" add column "feedback" text not null;

alter table "public"."nova_submissions" add column "prompt" text not null;

CREATE UNIQUE INDEX nova_submission_outputs_pkey ON public.nova_submission_outputs USING btree (id);

CREATE UNIQUE INDEX nova_challenge_criterias_pkey ON public.nova_challenge_criteria USING btree (id);

alter table "public"."nova_challenge_criteria" add constraint "nova_challenge_criterias_pkey" PRIMARY KEY using index "nova_challenge_criterias_pkey";

alter table "public"."nova_submission_outputs" add constraint "nova_submission_outputs_pkey" PRIMARY KEY using index "nova_submission_outputs_pkey";

alter table "public"."nova_challenge_criteria" add constraint "nova_challenge_criteria_challenge_id_fkey" FOREIGN KEY (challenge_id) REFERENCES nova_challenges(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."nova_challenge_criteria" validate constraint "nova_challenge_criteria_challenge_id_fkey";

alter table "public"."nova_submission_outputs" add constraint "nova_submission_outputs_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES nova_submissions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."nova_submission_outputs" validate constraint "nova_submission_outputs_submission_id_fkey";

alter table "public"."nova_problem_criteria_scores" add constraint "nova_problem_criteria_scores_criteria_id_fkey" FOREIGN KEY (criteria_id) REFERENCES nova_challenge_criteria(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."nova_problem_criteria_scores" validate constraint "nova_problem_criteria_scores_criteria_id_fkey";

grant delete on table "public"."nova_challenge_criteria" to "anon";

grant insert on table "public"."nova_challenge_criteria" to "anon";

grant references on table "public"."nova_challenge_criteria" to "anon";

grant select on table "public"."nova_challenge_criteria" to "anon";

grant trigger on table "public"."nova_challenge_criteria" to "anon";

grant truncate on table "public"."nova_challenge_criteria" to "anon";

grant update on table "public"."nova_challenge_criteria" to "anon";

grant delete on table "public"."nova_challenge_criteria" to "authenticated";

grant insert on table "public"."nova_challenge_criteria" to "authenticated";

grant references on table "public"."nova_challenge_criteria" to "authenticated";

grant select on table "public"."nova_challenge_criteria" to "authenticated";

grant trigger on table "public"."nova_challenge_criteria" to "authenticated";

grant truncate on table "public"."nova_challenge_criteria" to "authenticated";

grant update on table "public"."nova_challenge_criteria" to "authenticated";

grant delete on table "public"."nova_challenge_criteria" to "service_role";

grant insert on table "public"."nova_challenge_criteria" to "service_role";

grant references on table "public"."nova_challenge_criteria" to "service_role";

grant select on table "public"."nova_challenge_criteria" to "service_role";

grant trigger on table "public"."nova_challenge_criteria" to "service_role";

grant truncate on table "public"."nova_challenge_criteria" to "service_role";

grant update on table "public"."nova_challenge_criteria" to "service_role";

grant delete on table "public"."nova_submission_outputs" to "anon";

grant insert on table "public"."nova_submission_outputs" to "anon";

grant references on table "public"."nova_submission_outputs" to "anon";

grant select on table "public"."nova_submission_outputs" to "anon";

grant trigger on table "public"."nova_submission_outputs" to "anon";

grant truncate on table "public"."nova_submission_outputs" to "anon";

grant update on table "public"."nova_submission_outputs" to "anon";

grant delete on table "public"."nova_submission_outputs" to "authenticated";

grant insert on table "public"."nova_submission_outputs" to "authenticated";

grant references on table "public"."nova_submission_outputs" to "authenticated";

grant select on table "public"."nova_submission_outputs" to "authenticated";

grant trigger on table "public"."nova_submission_outputs" to "authenticated";

grant truncate on table "public"."nova_submission_outputs" to "authenticated";

grant update on table "public"."nova_submission_outputs" to "authenticated";

grant delete on table "public"."nova_submission_outputs" to "service_role";

grant insert on table "public"."nova_submission_outputs" to "service_role";

grant references on table "public"."nova_submission_outputs" to "service_role";

grant select on table "public"."nova_submission_outputs" to "service_role";

grant trigger on table "public"."nova_submission_outputs" to "service_role";

grant truncate on table "public"."nova_submission_outputs" to "service_role";

grant update on table "public"."nova_submission_outputs" to "service_role";


