// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/user-groups/[groupId]/members/[userId]/route';

export const DELETE = legacyRoute.DELETE;
