// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/workspaces/[wsId]/wallets/[walletId]/interest/config/route';

export const PUT = legacyRoute.PUT;
export const DELETE = legacyRoute.DELETE;
