// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/rate-limit-appeals/route';

export const POST = legacyRoute.POST;
