// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/courses/[courseId]/module-order/route';

export const PATCH = legacyRoute.PATCH;
