// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/workspaces/[wsId]/wallets/[walletId]/checkpoints/[checkpointId]/route';

export const PATCH = legacyRoute.PATCH;
export const DELETE = legacyRoute.DELETE;
