#!/usr/bin/env bun
/**
 * Generates Mintlify reference pages for every component in the live `/ui`
 * explorer, mirroring the same registry that drives
 * `apps/web/src/app/[locale]/ui`. Run with:
 *
 *   bun docs:gen-ui            # write pages + patch docs.json
 *   bun docs:gen-ui --check    # fail (exit 1) if anything is out of date
 *
 * Source of truth: the component registry. Do not hand-edit the generated
 * `apps/docs/platform/components/ui/*.mdx` files — re-run this script instead.
 */

import { execFileSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildComponentDoc } from '../apps/web/src/app/[locale]/ui/component-docs-core.ts';
import {
  categoryIds,
  componentEntries,
} from '../apps/web/src/app/[locale]/ui/component-registry.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');
const docsRoot = join(repoRoot, 'apps/docs');
const outDir = join(docsRoot, 'platform/components/ui');
const docsJsonPath = join(docsRoot, 'docs.json');
const enMessagesPath = join(repoRoot, 'apps/web/messages/en.json');

const LIVE_BASE = 'https://tuturuuu.com/ui/components';
const DOCS_PAGE_PREFIX = 'platform/components/ui';
const UI_GROUP = 'UI Components';
const checkMode = process.argv.includes('--check');

const messages = JSON.parse(readFileSync(enMessagesPath, 'utf8'));
const ui = messages['ui-showcase'];
const detail = ui.docs.detail;
const categoryLabels: Record<string, string> = ui.categories;
const statusLabels: Record<string, string> = ui.docs.status;
const customizationLabels: Record<string, string> = ui.customizations;
const exampleCopy: Record<string, { title: string; description: string }> =
  detail.examples;

const fill = (template: string, values: Record<string, string>) =>
  template.replace(/\{(\w+)\}/g, (_, key) => values[key] ?? `{${key}}`);

const nameById = new Map(
  componentEntries.map((entry) => [entry.id, entry.name])
);

const fence = (lang: string, code: string) => `\`\`\`${lang}\n${code}\n\`\`\``;

function buildMdx(entry: (typeof componentEntries)[number]): string {
  const doc = buildComponentDoc(entry);
  const liveUrl = `${LIVE_BASE}/${doc.slug}`;
  const description = fill(detail.description, {
    name: doc.name,
    importPath: doc.importPath,
  });

  const lines: string[] = [];
  lines.push('---');
  lines.push(`title: ${JSON.stringify(doc.name)}`);
  lines.push(`description: ${JSON.stringify(description)}`);
  lines.push('---');
  lines.push('');
  lines.push(
    '{/* AUTO-GENERATED by scripts/generate-ui-component-docs.ts — do not edit by hand. */}'
  );
  lines.push('');
  lines.push('<Info>');
  lines.push(
    `  Explore the live, interactive preview at [${liveUrl.replace('https://', '')}](${liveUrl}).`
  );
  lines.push('</Info>');
  lines.push('');
  lines.push(
    `**Category:** ${categoryLabels[doc.category]} · **Import:** \`${doc.importPath}\` · **Status:** ${statusLabels[doc.status]}`
  );
  lines.push('');

  // Installation
  lines.push(`## ${detail.installationTitle}`);
  lines.push('');
  lines.push(detail.installationDescription);
  lines.push('');
  lines.push(fence('bash', doc.installation.command));
  lines.push('');
  if (doc.installation.manualSteps.length) {
    lines.push(fence('tsx', doc.installation.manualSteps.join('\n')));
    lines.push('');
  }

  // Usage
  lines.push(`## ${detail.usageTitle}`);
  lines.push('');
  lines.push(detail.usageDescription);
  lines.push('');
  lines.push(fence('tsx', doc.usage));
  lines.push('');

  // Examples
  lines.push(`## ${detail.examplesTitle}`);
  lines.push('');
  lines.push(detail.examplesDescription);
  lines.push('');
  for (const example of doc.examples) {
    const copy = exampleCopy[example.titleKey];
    lines.push(`### ${copy.title}`);
    lines.push('');
    lines.push(exampleCopy[example.descriptionKey].description);
    lines.push('');
    lines.push(fence('tsx', example.code));
    lines.push('');
  }

  // API reference
  lines.push(`## ${detail.apiTitle}`);
  lines.push('');
  lines.push(detail.apiDescription);
  lines.push('');
  lines.push('| Export | Kind |');
  lines.push('| ------ | ---- |');
  for (const row of doc.apiReference.rows) {
    lines.push(`| \`${row.name}\` | ${row.kind} |`);
  }
  lines.push('');

  // Customization
  if (doc.customizationKeys.length) {
    lines.push(`## ${detail.customizationTitle}`);
    lines.push('');
    lines.push(detail.customizationDescription);
    lines.push('');
    for (const key of doc.customizationKeys) {
      lines.push(`- ${customizationLabels[key] ?? key}`);
    }
    lines.push('');
  }

  // Related
  if (doc.related.length) {
    lines.push(`## ${detail.relatedTitle}`);
    lines.push('');
    for (const relatedId of doc.related) {
      const relatedName = nameById.get(relatedId) ?? relatedId;
      lines.push(`- [${relatedName}](./${relatedId})`);
    }
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function buildOverviewMdx(): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push('title: "UI Components"');
  lines.push(
    'description: "Reference for every component in the @tuturuuu/ui registry, mirrored from the live UI explorer."'
  );
  lines.push('---');
  lines.push('');
  lines.push(
    '{/* AUTO-GENERATED by scripts/generate-ui-component-docs.ts — do not edit by hand. */}'
  );
  lines.push('');
  lines.push('<Info>');
  lines.push(
    '  Browse the live, interactive explorer at [tuturuuu.com/ui](https://tuturuuu.com/ui).'
  );
  lines.push('</Info>');
  lines.push('');

  for (const category of categoryIds) {
    const entries = componentEntries.filter(
      (entry) => entry.category === category
    );
    if (!entries.length) continue;
    lines.push(`## ${categoryLabels[category]}`);
    lines.push('');
    for (const entry of entries) {
      lines.push(`- [${entry.name}](./${entry.id})`);
    }
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

type NavNode = string | { group: string; pages: NavNode[] };

function buildUiNavGroup(): NavNode {
  const categoryGroups: NavNode[] = [];
  for (const category of categoryIds) {
    const entries = componentEntries.filter(
      (entry) => entry.category === category
    );
    if (!entries.length) continue;
    categoryGroups.push({
      group: categoryLabels[category],
      pages: entries.map((entry) => `${DOCS_PAGE_PREFIX}/${entry.id}`),
    });
  }
  return {
    group: UI_GROUP,
    pages: [`${DOCS_PAGE_PREFIX}/overview`, ...categoryGroups],
  };
}

type ComponentsGroup = { group: string; pages: NavNode[] };

/** Recursively find the "Components" nav group that owns the components overview. */
function findComponentsGroup(node: unknown): ComponentsGroup | null {
  if (Array.isArray(node)) {
    for (const child of node) {
      const found = findComponentsGroup(child);
      if (found) return found;
    }
    return null;
  }
  if (node && typeof node === 'object') {
    const obj = node as Record<string, unknown>;
    if (
      obj.group === 'Components' &&
      Array.isArray(obj.pages) &&
      obj.pages.includes('platform/components/overview')
    ) {
      return obj as unknown as ComponentsGroup;
    }
    for (const value of Object.values(obj)) {
      const found = findComponentsGroup(value);
      if (found) return found;
    }
  }
  return null;
}

function buildDocsJson(current: string): string {
  const json = JSON.parse(current);
  const componentsGroup = findComponentsGroup(json);
  if (!componentsGroup) {
    throw new Error(
      'Could not locate the "Components" nav group in docs.json — aborting to avoid corrupting navigation.'
    );
  }
  // Drop any previously generated UI Components group, then append the fresh one.
  componentsGroup.pages = componentsGroup.pages.filter(
    (page: NavNode) =>
      !(typeof page === 'object' && page !== null && page.group === UI_GROUP)
  );
  componentsGroup.pages.push(buildUiNavGroup());
  // Round-trip through Biome so the output matches the repo's canonical JSON
  // formatting (and stays idempotent under `--check`).
  return execFileSync(
    'bunx',
    ['biome', 'format', '--stdin-file-path=docs.json'],
    {
      input: `${JSON.stringify(json, null, 2)}\n`,
      encoding: 'utf8',
      cwd: repoRoot,
    }
  );
}

// --- Run -------------------------------------------------------------------

const generated = new Map<string, string>();
generated.set(join(outDir, 'overview.mdx'), buildOverviewMdx());
for (const entry of componentEntries) {
  generated.set(join(outDir, `${entry.id}.mdx`), buildMdx(entry));
}
const nextDocsJson = buildDocsJson(readFileSync(docsJsonPath, 'utf8'));

// Stale generated pages that no longer correspond to a component.
const validBasenames = new Set([
  'overview.mdx',
  ...componentEntries.map((entry) => `${entry.id}.mdx`),
]);
const stale = existsSync(outDir)
  ? readdirSync(outDir).filter(
      (file) => file.endsWith('.mdx') && !validBasenames.has(file)
    )
  : [];

if (checkMode) {
  const drift: string[] = [];
  for (const [path, content] of generated) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) {
      drift.push(path);
    }
  }
  for (const file of stale) drift.push(join(outDir, `${file} (stale)`));
  if (readFileSync(docsJsonPath, 'utf8') !== nextDocsJson) {
    drift.push(docsJsonPath);
  }
  if (drift.length) {
    console.error(
      `UI component docs are out of date. Run \`bun docs:gen-ui\`. Affected:\n${drift
        .map((path) => `  - ${path.replace(`${repoRoot}/`, '')}`)
        .join('\n')}`
    );
    process.exit(1);
  }
  console.log('UI component docs are up to date.');
  process.exit(0);
}

mkdirSync(outDir, { recursive: true });
for (const file of stale) unlinkSync(join(outDir, file));
for (const [path, content] of generated) writeFileSync(path, content);
writeFileSync(docsJsonPath, nextDocsJson);

console.log(
  `Generated ${generated.size} UI component doc pages (${componentEntries.length} components) and patched docs.json.${
    stale.length ? ` Removed ${stale.length} stale page(s).` : ''
  }`
);
