// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/ai/chat/google/summary/route';

export const PATCH = legacyRoute.PATCH;
