// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import {
  createLegacyGetHandler,
  createLegacyHeadHandler,
} from '@/legacy-api-routes/head';
import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/chat/conversations/[conversationId]/attachments/[attachmentId]/route';

export const GET = createLegacyGetHandler(legacyRoute.GET);
export const HEAD = createLegacyHeadHandler(GET);
