// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import {
  createLegacyGetHandler,
  createLegacyHeadHandler,
} from '@/legacy-api-routes/head';
import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/meetings/[meetingId]/stream/route';

export const GET = createLegacyGetHandler(legacyRoute.GET);
export const HEAD = createLegacyHeadHandler(GET);
export const POST = legacyRoute.POST;
export const PATCH = legacyRoute.PATCH;
