// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/notifications/send-immediate/route';

export const POST = legacyRoute.POST;
