// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/payment/credit-packs/checkouts/route';

export const POST = legacyRoute.POST;
