export function getRichTextEditorClasses({
  className,
  readOnly,
}: {
  className?: string;
  readOnly: boolean;
}) {
  return [
    'border border-dynamic-border rounded-md bg-transparent',
    'max-w-none overflow-y-auto',
    readOnly ? 'pt-0' : 'pt-4',
    'text-foreground leading-relaxed',
    '[&_:first-child]:mt-0',
    '[&_h1]:text-4xl [&_h1]:font-bold [&_h1]:text-foreground [&_h1]:mt-6 [&_h1]:mb-4',
    '[&_h2]:text-3xl [&_h2]:font-semibold [&_h2]:text-foreground [&_h2]:mt-5 [&_h2]:mb-3',
    '[&_h3]:text-2xl [&_h3]:font-semibold [&_h3]:text-foreground [&_h3]:mt-4 [&_h3]:mb-2',
    '[&_h4]:text-xl [&_h4]:font-semibold [&_h4]:text-foreground [&_h4]:mt-3 [&_h4]:mb-2',
    '[&_h5]:text-lg [&_h5]:font-semibold [&_h5]:text-foreground [&_h5]:mt-3 [&_h5]:mb-2',
    '[&_h6]:text-base [&_h6]:font-semibold [&_h6]:text-foreground [&_h6]:mt-3 [&_h6]:mb-2',
    '[&_p]:my-3 [&_p]:leading-7',
    '[&_ul]:my-3 [&_ul]:ml-6 [&_ul]:px-0 [&_ul]:mr-0',
    '[&_ol]:my-3 [&_ol]:ml-6 [&_ol]:px-0 [&_ol]:mr-0',
    '[&_li]:my-1 [&_li]:leading-7',
    '[&_ul_li_p]:my-1',
    '[&_ol_li_p]:my-1',
    '[&_li_h1]:text-4xl [&_li_h2]:text-3xl [&_li_h3]:text-2xl',
    '[&_ul[data-type="taskList"]]:list-none [&_ul[data-type="taskList"]]:ml-6 [&_ul[data-type="taskList"]]:pl-0 [&_ul[data-type="taskList"]]:pr-0 [&_ul[data-type="taskList"]]:mr-0 [&_ul[data-type="taskList"]]:my-3',
    '[&_ul[data-type="taskList"]_li]:flex [&_ul[data-type="taskList"]_li]:items-start [&_ul[data-type="taskList"]_li]:my-1',
    '[&_ul[data-type="taskList"]_.task-list-checkbox-label]:flex-[0_0_auto]',
    '[&_ul[data-type="taskList"]_li>div:not(.task-list-checkbox-label)]:flex-1 [&_ul[data-type="taskList"]_li>div:not(.task-list-checkbox-label)]:min-w-0',
    '[&_ul[data-type="taskList"]_li_p]:my-1',
    '[&_ul[data-type="taskList"]_input[type="checkbox"]]:appearance-none [&_ul[data-type="taskList"]_input[type="checkbox"]]:h-[18px] [&_ul[data-type="taskList"]_input[type="checkbox"]]:w-[18px]',
    '[&_ul[data-type="taskList"]_input[type="checkbox"]]:cursor-pointer [&_ul[data-type="taskList"]_input[type="checkbox"]]:rounded-[4px] [&_ul[data-type="taskList"]_input[type="checkbox"]]:border-2 [&_ul[data-type="taskList"]_input[type="checkbox"]]:border-input',
    '[&_ul[data-type="taskList"]_input[type="checkbox"]]:bg-background [&_ul[data-type="taskList"]_input[type="checkbox"]]:transition-all [&_ul[data-type="taskList"]_input[type="checkbox"]]:duration-150',
    '[&_ul[data-type="taskList"]_input[type="checkbox"]]:shrink-0',
    '[&_ul[data-type="taskList"]_input[type="checkbox"]:hover]:border-dynamic-gray [&_ul[data-type="taskList"]_input[type="checkbox"]:hover]:bg-dynamic-gray/10 [&_ul[data-type="taskList"]_input[type="checkbox"]:hover]:scale-105',
    '[&_ul[data-type="taskList"]_input[type="checkbox"]:focus]:outline-none [&_ul[data-type="taskList"]_input[type="checkbox"]:focus]:ring-2 [&_ul[data-type="taskList"]_input[type="checkbox"]:focus]:ring-dynamic-gray/30 [&_ul[data-type="taskList"]_input[type="checkbox"]:focus]:ring-offset-2 [&_ul[data-type="taskList"]_input[type="checkbox"]:focus]:border-dynamic-gray',
    '[&_ul[data-type="taskList"]_input[type="checkbox"]:checked]:bg-dynamic-green/20 [&_ul[data-type="taskList"]_input[type="checkbox"]:checked]:border-dynamic-green',
    '[&_ul[data-type="taskList"]_input[type="checkbox"]:checked:hover]:bg-dynamic-green/10 [&_ul[data-type="taskList"]_input[type="checkbox"]:checked:hover]:border-dynamic-green',
    `[&_ul[data-type="taskList"]_input[type="checkbox"]:checked]:bg-[url('data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2016%2016%22%3E%3Cpath%20fill%3D%22none%22%20stroke%3D%22%2309090b%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%20stroke-width%3D%222%22%20d%3D%22M4%208l2.5%202.5L12%205%22%2F%3E%3C%2Fsvg%3E')]`,
    `dark:[&_ul[data-type="taskList"]_input[type="checkbox"]:checked]:bg-[url('data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2016%2016%22%3E%3Cpath%20fill%3D%22none%22%20stroke%3D%22white%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%20stroke-width%3D%222%22%20d%3D%22M4%208l2.5%202.5L12%205%22%2F%3E%3C%2Fsvg%3E')]`,
    '[&_ul[data-type="taskList"]_input[type="checkbox"]:checked:bg-[length:14px_14px]',
    '[&_ul[data-type="taskList"]_input[type="checkbox"]:indeterminate]:bg-dynamic-orange/20 [&_ul[data-type="taskList"]_input[type="checkbox"]:indeterminate]:border-dynamic-orange',
    '[&_li_ul]:my-1 [&_li_ul]:ml-6 [&_li_ol]:my-1 [&_li_ol]:ml-6',
    '[&_ul[data-type="taskList"]_ul[data-type="taskList"]]:my-1 [&_ul[data-type="taskList"]_ul[data-type="taskList"]]:ml-6',
    '[&_div[data-type="details"]]:relative [&_div[data-type="details"]]:my-3 [&_div[data-type="details"]]:pl-7',
    '[&_.toggle-details-button]:absolute [&_.toggle-details-button]:top-1 [&_.toggle-details-button]:left-0 [&_.toggle-details-button]:size-6 [&_.toggle-details-button]:rounded-md [&_.toggle-details-button]:text-muted-foreground [&_.toggle-details-button]:transition-transform [&_.toggle-details-button:hover]:bg-dynamic-surface [&_.toggle-details-button:hover]:text-foreground',
    '[&_.toggle-details-button]:before:content-["›"] [&_.toggle-details-button]:before:text-xl [&_.toggle-details-button]:before:leading-none',
    '[&_.toggle-details.is-open>.toggle-details-button]:rotate-90',
    '[&_summary]:cursor-text [&_summary]:list-none [&_summary::-webkit-details-marker]:hidden',
    '[&_summary[data-heading-level="1"]]:text-4xl [&_summary[data-heading-level="1"]]:font-bold',
    '[&_summary[data-heading-level="2"]]:text-3xl [&_summary[data-heading-level="2"]]:font-semibold',
    '[&_summary[data-heading-level="3"]]:text-2xl [&_summary[data-heading-level="3"]]:font-semibold',
    '[&_div[data-type="detailsContent"]]:mt-1 [&_div[data-type="detailsContent"]]:border-dynamic-border/60 [&_div[data-type="detailsContent"]]:border-l [&_div[data-type="detailsContent"]]:pl-4',
    '[&_blockquote]:border-l-4 [&_blockquote]:border-dynamic-border [&_blockquote]:pl-4 [&_blockquote]:my-4',
    '[&_blockquote]:text-muted-foreground [&_blockquote]:italic',
    '[&_code]:text-dynamic-pink [&_code]:bg-dynamic-pink/10 [&_code]:px-1.5 [&_code]:py-0.5',
    '[&_code]:rounded [&_code]:text-sm [&_code]:font-mono',
    '[&_pre]:bg-dynamic-border/50 [&_pre]:p-4 [&_pre]:rounded-md [&_pre]:my-4 [&_pre]:overflow-x-auto',
    '[&_pre_code]:bg-transparent [&_pre_code]:p-0 [&_pre_code]:text-foreground',
    '[&_strong]:font-bold [&_strong]:text-foreground',
    '[&_b]:font-bold [&_b]:text-foreground',
    '[&_em]:italic [&_em]:text-foreground',
    '[&_i]:italic [&_i]:text-foreground',
    '[&_a]:text-dynamic-cyan [&_a]:underline [&_a]:cursor-pointer',
    '[&_a:hover]:text-dynamic-cyan/80',
    '[&_a_strong]:text-dynamic-cyan [&_a_b]:text-dynamic-cyan',
    '[&_strong_a]:text-dynamic-cyan [&_b_a]:text-dynamic-cyan',
    '[&_hr]:border-dynamic-border [&_hr]:my-8',
    '[&_table]:my-6 [&_table]:w-full [&_table]:overflow-hidden [&_table]:rounded-lg [&_table]:border [&_table]:border-collapse [&_table]:border-dynamic-border',
    '[&_table]:shadow-sm',
    '[&_th]:relative [&_th]:border-r [&_th]:border-dynamic-border [&_th]:bg-dynamic-border/30',
    '[&_th]:px-4 [&_th]:py-3 [&_th]:text-left [&_th]:font-semibold [&_th]:text-foreground',
    '[&_th]:last:border-r-0 [&_th_p]:my-0',
    '[&_tr]:border-b [&_tr]:border-dynamic-border [&_tr]:last:border-0',
    '[&_tr]:transition-colors [&_tr:hover]:bg-dynamic-surface/30',
    '[&_td]:relative [&_td]:border-r [&_td]:border-dynamic-border [&_td]:px-4 [&_td]:py-3',
    '[&_td]:last:border-r-0 [&_td_p]:my-0',
    '[&_td]:transition-colors [&_td:hover]:bg-dynamic-surface/50',
    '[&_td:focus]:bg-dynamic-surface/70 [&_td:focus]:outline-none',
    '[&_td:focus]:ring-2 [&_td:focus]:ring-dynamic-blue/50 [&_td:focus]:ring-inset',
    '[&_.selectedCell]:bg-dynamic-blue/10 [&_.selectedCell]:ring-2 [&_.selectedCell]:ring-dynamic-blue/30',
    '[&_.column-resize-handle]:absolute [&_.column-resize-handle]:right-[-2px] [&_.column-resize-handle]:top-0',
    '[&_.column-resize-handle]:bottom-0 [&_.column-resize-handle]:w-1 [&_.column-resize-handle]:cursor-col-resize',
    '[&_.column-resize-handle]:bg-dynamic-blue/50 [&_.column-resize-handle]:opacity-0',
    '[&_.column-resize-handle:hover]:opacity-100 [&_.column-resize-handle]:transition-opacity',
    '[&_*:is(p,h1,h2,h3).is-empty::before]:content-[attr(data-placeholder)]',
    '[&_*:is(p,h1,h2,h3).is-empty::before]:text-muted-foreground',
    '[&_*:is(p,h1,h2,h3).is-empty::before]:float-left',
    '[&_*:is(p,h1,h2,h3).is-empty::before]:h-0',
    '[&_*:is(p,h1,h2,h3).is-empty::before]:pointer-events-none',
    readOnly
      ? '[&_ul[data-type="taskList"]_input[type="checkbox"]]:!pointer-events-none [&_ul[data-type="taskList"]_input[type="checkbox"]]:!opacity-70 [&_ul[data-type="taskList"]_li>label]:!pointer-events-none [&_input[type="checkbox"]]:!pointer-events-none [&_.task-list-checkbox]:!pointer-events-none [&_.task-list-checkbox-label]:!pointer-events-none [&_li_div[draggable="true"]]:hidden [&_ul[data-type="taskList"]_li]:![-webkit-user-drag:none] [&_ul[data-type="taskList"]_li]:!user-drag-none'
      : '',
    readOnly ? '[&_.drag-handle]:hidden' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');
}
