export const TASK_PROGRESS_AI_CATCHUPS_CONFIG_ID = 'TASK_PROGRESS_AI_CATCHUPS';
export const TASK_PROGRESS_CATCHUP_CADENCE_CONFIG_ID =
  'TASK_PROGRESS_CATCHUP_CADENCE';
export const TASK_PROGRESS_SHOW_DECISIONS_CONFIG_ID =
  'TASK_PROGRESS_SHOW_DECISIONS';
export const TASK_PROGRESS_GOAL_STYLE_CONFIG_ID = 'TASK_PROGRESS_GOAL_STYLE';
