// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/tutoring/sessions/[id]/route';

export const PUT = legacyRoute.PUT;
