// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/user-groups/sessions/[sessionId]/route';

export const PUT = legacyRoute.PUT;
