// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/users/me/avatar/route';

export const DELETE = legacyRoute.DELETE;
