// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/group-tags/[tagId]/user-groups/[groupId]/route';

export const DELETE = legacyRoute.DELETE;
