// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/admin/ai-credits/sync-models/route';

export const POST = legacyRoute.POST;
