// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/ai/chats/[chatId]/route';

export const PATCH = legacyRoute.PATCH;
