import dayjs from 'dayjs';
import type { TemplateScenario } from './types';

export const templateScenarios: TemplateScenario[] = [
  {
    name: 'Basic Work Day',
    description: 'Simple tasks that fit within normal work hours',
    tasks: [
      {
        id: 'basic-1',
        name: 'Morning standup',
        duration: 0.5,
        minDuration: 0.5,
        maxDuration: 1,
        category: 'meeting',
        priority: 'high',
        events: [],
        allowSplit: false,
      },
      {
        id: 'basic-2',
        name: 'Code review',
        duration: 2,
        minDuration: 1,
        maxDuration: 3,
        category: 'work',
        priority: 'normal',
        events: [],
        allowSplit: false,
      },
      {
        id: 'basic-3',
        name: 'Documentation',
        duration: 1.5,
        minDuration: 0.5,
        maxDuration: 2,
        category: 'work',
        priority: 'low',
        events: [],
        allowSplit: false,
      },
    ],
  },
  {
    name: 'Task Splitting Challenge',
    description: 'Large tasks that need to be split due to time constraints',
    tasks: [
      {
        id: 'split-1',
        name: 'Deep Work Session',
        duration: 6,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'high',
        events: [],
        allowSplit: true,
      },
      {
        id: 'split-2',
        name: 'Personal Learning',
        duration: 4,
        minDuration: 0.5,
        maxDuration: 1.5,
        category: 'personal',
        priority: 'normal',
        events: [],
        allowSplit: true,
      },
      {
        id: 'split-3',
        name: 'Project Planning',
        duration: 3,
        minDuration: 1,
        maxDuration: 1,
        category: 'work',
        priority: 'high',
        events: [],
        allowSplit: true,
      },
    ],
  },
  {
    name: 'Mixed Categories',
    description: 'Tasks across work, personal, and meeting categories',
    tasks: [
      {
        id: 'mixed-1',
        name: 'Team Meeting',
        duration: 1,
        minDuration: 1,
        maxDuration: 1.5,
        category: 'meeting',
        priority: 'high',
        events: [],
      },
      {
        id: 'mixed-2',
        name: 'Gym Workout',
        duration: 1.5,
        minDuration: 1,
        maxDuration: 2,
        category: 'personal',
        priority: 'normal',
        events: [],
      },
      {
        id: 'mixed-3',
        name: 'Feature Development',
        duration: 4,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'high',
        events: [],
      },
      {
        id: 'mixed-4',
        name: 'Client Call',
        duration: 0.5,
        minDuration: 0.5,
        maxDuration: 1,
        category: 'meeting',
        priority: 'critical',
        events: [],
      },
      {
        id: 'mixed-5',
        name: 'Meal Prep',
        duration: 2,
        minDuration: 1,
        maxDuration: 2,
        category: 'personal',
        priority: 'low',
        events: [],
      },
    ],
  },
  {
    name: 'Deadline Pressure',
    description: 'Tasks with tight deadlines to test prioritization',
    tasks: [
      {
        id: 'deadline-1',
        name: 'Urgent Bug Fix',
        duration: 2,
        minDuration: 1,
        maxDuration: 3,
        category: 'work',
        priority: 'critical',
        deadline: dayjs().add(4, 'hour'),
        events: [],
      },
      {
        id: 'deadline-2',
        name: 'Presentation Prep',
        duration: 3,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'high',
        deadline: dayjs().add(1, 'day'),
        events: [],
      },
      {
        id: 'deadline-3',
        name: 'Weekly Report',
        duration: 1,
        minDuration: 0.5,
        maxDuration: 1.5,
        category: 'work',
        priority: 'normal',
        deadline: dayjs().add(2, 'day'),
        events: [],
      },
      {
        id: 'deadline-4',
        name: 'Exercise',
        duration: 1,
        minDuration: 0.5,
        maxDuration: 1.5,
        category: 'personal',
        priority: 'low',
        events: [],
      },
    ],
  },
  {
    name: 'Overloaded Schedule',
    description: 'More tasks than available time to test conflict resolution',
    tasks: [
      {
        id: 'over-1',
        name: 'Major Feature A',
        duration: 8,
        minDuration: 2,
        maxDuration: 3,
        category: 'work',
        priority: 'critical',
        events: [],
      },
      {
        id: 'over-2',
        name: 'Major Feature B',
        duration: 6,
        minDuration: 1.5,
        maxDuration: 2.5,
        category: 'work',
        priority: 'high',
        events: [],
      },
      {
        id: 'over-3',
        name: 'All-day Workshop',
        duration: 6,
        minDuration: 2,
        maxDuration: 3,
        category: 'meeting',
        priority: 'normal',
        events: [],
      },
      {
        id: 'over-4',
        name: 'Personal Project',
        duration: 4,
        minDuration: 1,
        maxDuration: 2,
        category: 'personal',
        priority: 'low',
        events: [],
      },
      {
        id: 'over-5',
        name: 'Code Review',
        duration: 3,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'high',
        events: [],
      },
    ],
  },
  {
    name: 'Priority Management',
    description:
      'Tasks with different priority levels to test intelligent scheduling',
    tasks: [
      {
        id: 'priority-1',
        name: 'Critical System Fix',
        duration: 3,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'critical',
        deadline: dayjs().add(6, 'hour'),
        events: [],
      },
      {
        id: 'priority-2',
        name: 'High Priority Feature',
        duration: 4,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'high',
        deadline: dayjs().add(1, 'day'),
        events: [],
      },
      {
        id: 'priority-3',
        name: 'Regular Development',
        duration: 5,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'normal',
        events: [],
      },
      {
        id: 'priority-4',
        name: 'Code Cleanup',
        duration: 2,
        minDuration: 0.5,
        maxDuration: 1,
        category: 'work',
        priority: 'low',
        events: [],
      },
      {
        id: 'priority-5',
        name: 'Team Retrospective',
        duration: 1.5,
        minDuration: 1,
        maxDuration: 1.5,
        category: 'meeting',
        priority: 'high',
        events: [],
      },
    ],
  },
  {
    name: 'Emergency Response',
    description: 'Critical tasks that need immediate attention',
    tasks: [
      {
        id: 'emergency-1',
        name: 'Production Bug Fix',
        duration: 2,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'critical',
        deadline: dayjs().add(2, 'hour'),
        events: [],
      },
      {
        id: 'emergency-2',
        name: 'Security Incident Response',
        duration: 4,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'critical',
        deadline: dayjs().add(4, 'hour'),
        events: [],
      },
      {
        id: 'emergency-3',
        name: 'Client Emergency Call',
        duration: 1,
        minDuration: 0.5,
        maxDuration: 1,
        category: 'meeting',
        priority: 'critical',
        deadline: dayjs().add(1, 'hour'),
        events: [],
      },
      {
        id: 'emergency-4',
        name: 'Regular Tasks',
        duration: 3,
        minDuration: 1,
        maxDuration: 1.5,
        category: 'work',
        priority: 'normal',
        events: [],
      },
    ],
  },
  {
    name: 'Balanced Lifestyle',
    description: 'Mix of work and personal tasks with different priorities',
    tasks: [
      {
        id: 'lifestyle-1',
        name: 'Important Work Meeting',
        duration: 1,
        minDuration: 1,
        maxDuration: 1,
        category: 'meeting',
        priority: 'high',
        events: [],
      },
      {
        id: 'lifestyle-2',
        name: 'Exercise Routine',
        duration: 1.5,
        minDuration: 1,
        maxDuration: 1.5,
        category: 'personal',
        priority: 'normal',
        events: [],
      },
      {
        id: 'lifestyle-3',
        name: 'Project Development',
        duration: 4,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'high',
        events: [],
      },
      {
        id: 'lifestyle-4',
        name: 'Reading Time',
        duration: 1,
        minDuration: 0.5,
        maxDuration: 1,
        category: 'personal',
        priority: 'low',
        events: [],
      },
      {
        id: 'lifestyle-5',
        name: 'Team Sync',
        duration: 0.5,
        minDuration: 0.5,
        maxDuration: 0.5,
        category: 'meeting',
        priority: 'normal',
        events: [],
      },
    ],
  },
  {
    name: 'Flexible Tasks',
    description: 'Tasks with very flexible duration constraints',
    tasks: [
      {
        id: 'flex-1',
        name: 'Research & Learning',
        duration: 5,
        minDuration: 0.5,
        maxDuration: 3,
        category: 'work',
        priority: 'normal',
        events: [],
      },
      {
        id: 'flex-2',
        name: 'Creative Writing',
        duration: 3,
        minDuration: 0.5,
        maxDuration: 2,
        category: 'personal',
        priority: 'low',
        events: [],
      },
      {
        id: 'flex-3',
        name: 'Code Refactoring',
        duration: 4,
        minDuration: 1,
        maxDuration: 4,
        category: 'work',
        priority: 'normal',
        events: [],
      },
    ],
  },
  {
    name: 'Student Study Schedule',
    description: 'Academic tasks with study sessions and exam preparation',
    tasks: [
      {
        id: 'study-1',
        name: 'Math Homework',
        duration: 2,
        minDuration: 0.5,
        maxDuration: 1.5,
        category: 'work',
        priority: 'high',
        deadline: dayjs().add(1, 'day'),
        events: [],
      },
      {
        id: 'study-2',
        name: 'History Research Paper',
        duration: 6,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'high',
        deadline: dayjs().add(3, 'day'),
        events: [],
      },
      {
        id: 'study-3',
        name: 'Study Group Session',
        duration: 2,
        minDuration: 2,
        maxDuration: 2,
        category: 'meeting',
        priority: 'normal',
        deadline: dayjs().add(2, 'day'),
        events: [],
      },
      {
        id: 'study-4',
        name: 'Exam Preparation',
        duration: 4,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'critical',
        deadline: dayjs().add(4, 'day'),
        events: [],
      },
      {
        id: 'study-5',
        name: 'Break & Recreation',
        duration: 1.5,
        minDuration: 0.5,
        maxDuration: 1.5,
        category: 'personal',
        priority: 'low',
        events: [],
      },
    ],
  },
  {
    name: 'Freelancer Portfolio',
    description:
      'Multiple client projects with varying priorities and deadlines',
    tasks: [
      {
        id: 'freelance-1',
        name: 'Client A - Logo Design',
        duration: 4,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'high',
        deadline: dayjs().add(2, 'day'),
        events: [],
      },
      {
        id: 'freelance-2',
        name: 'Client B - Website Mockup',
        duration: 6,
        minDuration: 1.5,
        maxDuration: 3,
        category: 'work',
        priority: 'normal',
        deadline: dayjs().add(5, 'day'),
        events: [],
      },
      {
        id: 'freelance-3',
        name: 'Client C - Urgent Fix',
        duration: 1,
        minDuration: 1,
        maxDuration: 1,
        category: 'work',
        priority: 'critical',
        deadline: dayjs().add(6, 'hour'),
        events: [],
      },
      {
        id: 'freelance-4',
        name: 'Portfolio Update',
        duration: 3,
        minDuration: 0.5,
        maxDuration: 1.5,
        category: 'work',
        priority: 'low',
        events: [],
      },
      {
        id: 'freelance-5',
        name: 'Client Meetings',
        duration: 2,
        minDuration: 0.5,
        maxDuration: 1,
        category: 'meeting',
        priority: 'high',
        events: [],
      },
    ],
  },
  {
    name: 'Health & Fitness Focus',
    description: 'Wellness-focused schedule with exercise and self-care',
    tasks: [
      {
        id: 'health-1',
        name: 'Morning Workout',
        duration: 1.5,
        minDuration: 1,
        maxDuration: 2,
        category: 'personal',
        priority: 'normal',
        events: [],
      },
      {
        id: 'health-2',
        name: 'Meal Preparation',
        duration: 2,
        minDuration: 1,
        maxDuration: 2,
        category: 'personal',
        priority: 'normal',
        events: [],
      },
      {
        id: 'health-3',
        name: 'Meditation & Mindfulness',
        duration: 1,
        minDuration: 0.5,
        maxDuration: 1,
        category: 'personal',
        priority: 'low',
        events: [],
      },
      {
        id: 'health-4',
        name: 'Work Tasks',
        duration: 6,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'high',
        events: [],
      },
      {
        id: 'health-5',
        name: 'Doctor Appointment',
        duration: 1,
        minDuration: 1,
        maxDuration: 1,
        category: 'personal',
        priority: 'high',
        deadline: dayjs().add(1, 'day').hour(14),
        events: [],
      },
    ],
  },
  {
    name: 'Meeting-Heavy Day',
    description: 'Schedule dominated by meetings and collaborative work',
    tasks: [
      {
        id: 'meeting-1',
        name: 'Stand-up Meeting',
        duration: 0.5,
        minDuration: 0.5,
        maxDuration: 0.5,
        category: 'meeting',
        priority: 'high',
        events: [],
      },
      {
        id: 'meeting-2',
        name: 'Project Review',
        duration: 2,
        minDuration: 1.5,
        maxDuration: 2.5,
        category: 'meeting',
        priority: 'high',
        events: [],
      },
      {
        id: 'meeting-3',
        name: 'Client Presentation',
        duration: 1.5,
        minDuration: 1.5,
        maxDuration: 2,
        category: 'meeting',
        priority: 'critical',
        deadline: dayjs().add(1, 'day').hour(15),
        events: [],
      },
      {
        id: 'meeting-4',
        name: 'Team Brainstorm',
        duration: 1,
        minDuration: 1,
        maxDuration: 1.5,
        category: 'meeting',
        priority: 'normal',
        events: [],
      },
      {
        id: 'meeting-5',
        name: 'One-on-One Reviews',
        duration: 2,
        minDuration: 0.5,
        maxDuration: 1,
        category: 'meeting',
        priority: 'normal',
        events: [],
      },
      {
        id: 'meeting-6',
        name: 'Focus Work Time',
        duration: 3,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'high',
        events: [],
      },
    ],
  },
  {
    name: 'Creative Sprint',
    description: 'Creative work requiring deep focus and inspiration',
    tasks: [
      {
        id: 'creative-1',
        name: 'Concept Development',
        duration: 4,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'high',
        events: [],
      },
      {
        id: 'creative-2',
        name: 'Design Iterations',
        duration: 6,
        minDuration: 1.5,
        maxDuration: 3,
        category: 'work',
        priority: 'high',
        events: [],
      },
      {
        id: 'creative-3',
        name: 'Inspiration Research',
        duration: 2,
        minDuration: 0.5,
        maxDuration: 1,
        category: 'personal',
        priority: 'low',
        events: [],
      },
      {
        id: 'creative-4',
        name: 'Feedback Session',
        duration: 1,
        minDuration: 1,
        maxDuration: 1,
        category: 'meeting',
        priority: 'normal',
        events: [],
      },
      {
        id: 'creative-5',
        name: 'Final Refinements',
        duration: 3,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'critical',
        deadline: dayjs().add(2, 'day'),
        events: [],
      },
    ],
  },
  {
    name: 'Remote Work Balance',
    description: 'Balancing remote work with home responsibilities',
    tasks: [
      {
        id: 'remote-1',
        name: 'Core Development Work',
        duration: 5,
        minDuration: 1,
        maxDuration: 2.5,
        category: 'work',
        priority: 'high',
        events: [],
      },
      {
        id: 'remote-2',
        name: 'Household Chores',
        duration: 2,
        minDuration: 0.5,
        maxDuration: 1,
        category: 'personal',
        priority: 'low',
        events: [],
      },
      {
        id: 'remote-3',
        name: 'Video Conference',
        duration: 1.5,
        minDuration: 1.5,
        maxDuration: 1.5,
        category: 'meeting',
        priority: 'high',
        deadline: dayjs().add(1, 'day').hour(10),
        events: [],
      },
      {
        id: 'remote-4',
        name: 'Lunch Break & Walk',
        duration: 1,
        minDuration: 0.5,
        maxDuration: 1.5,
        category: 'personal',
        priority: 'normal',
        events: [],
      },
      {
        id: 'remote-5',
        name: 'Email & Admin',
        duration: 1.5,
        minDuration: 0.5,
        maxDuration: 1,
        category: 'work',
        priority: 'normal',
        events: [],
      },
    ],
  },
  {
    name: 'Startup Hustle',
    description: 'High-intensity startup environment with urgent priorities',
    tasks: [
      {
        id: 'startup-1',
        name: 'Product Development',
        duration: 8,
        minDuration: 2,
        maxDuration: 4,
        category: 'work',
        priority: 'critical',
        events: [],
      },
      {
        id: 'startup-2',
        name: 'Investor Pitch Prep',
        duration: 3,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'critical',
        deadline: dayjs().add(1, 'day'),
        events: [],
      },
      {
        id: 'startup-3',
        name: 'Team Check-ins',
        duration: 2,
        minDuration: 0.5,
        maxDuration: 1,
        category: 'meeting',
        priority: 'high',
        events: [],
      },
      {
        id: 'startup-4',
        name: 'Market Research',
        duration: 4,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'normal',
        events: [],
      },
      {
        id: 'startup-5',
        name: 'Networking Event',
        duration: 3,
        minDuration: 3,
        maxDuration: 3,
        category: 'meeting',
        priority: 'high',
        deadline: dayjs().add(2, 'day').hour(18),
        events: [],
      },
    ],
  },
  {
    name: 'Learning & Development',
    description: 'Professional development and skill building focus',
    tasks: [
      {
        id: 'learning-1',
        name: 'Online Course Progress',
        duration: 3,
        minDuration: 0.5,
        maxDuration: 1.5,
        category: 'personal',
        priority: 'normal',
        events: [],
      },
      {
        id: 'learning-2',
        name: 'Practice Projects',
        duration: 4,
        minDuration: 1,
        maxDuration: 2,
        category: 'personal',
        priority: 'normal',
        events: [],
      },
      {
        id: 'learning-3',
        name: 'Technical Reading',
        duration: 2,
        minDuration: 0.5,
        maxDuration: 1,
        category: 'personal',
        priority: 'low',
        events: [],
      },
      {
        id: 'learning-4',
        name: 'Regular Work Tasks',
        duration: 6,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'high',
        events: [],
      },
      {
        id: 'learning-5',
        name: 'Mentorship Session',
        duration: 1,
        minDuration: 1,
        maxDuration: 1,
        category: 'meeting',
        priority: 'high',
        deadline: dayjs().add(3, 'day').hour(16),
        events: [],
      },
    ],
  },
  {
    name: 'Parenting Professional',
    description: 'Balancing professional work with parenting responsibilities',
    tasks: [
      {
        id: 'parent-1',
        name: 'Morning Work Block',
        duration: 3,
        minDuration: 1,
        maxDuration: 2,
        category: 'work',
        priority: 'high',
        events: [],
      },
      {
        id: 'parent-2',
        name: 'School Pick-up',
        duration: 0.5,
        minDuration: 0.5,
        maxDuration: 0.5,
        category: 'personal',
        priority: 'critical',
        deadline: dayjs().add(1, 'day').hour(15).minute(30),
        events: [],
      },
      {
        id: 'parent-3',
        name: 'Evening Work Session',
        duration: 2,
        minDuration: 0.5,
        maxDuration: 1.5,
        category: 'work',
        priority: 'normal',
        events: [],
      },
      {
        id: 'parent-4',
        name: 'Family Activities',
        duration: 2,
        minDuration: 1,
        maxDuration: 2,
        category: 'personal',
        priority: 'normal',
        events: [],
      },
      {
        id: 'parent-5',
        name: 'Client Call',
        duration: 1,
        minDuration: 1,
        maxDuration: 1,
        category: 'meeting',
        priority: 'high',
        deadline: dayjs().add(1, 'day').hour(11),
        events: [],
      },
    ],
  },
];
