// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/auth/mfa/mobile/challenges/[challengeId]/approve/route';

export const POST = legacyRoute.POST;
export const OPTIONS = legacyRoute.OPTIONS;
