// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/email/unsubscribe/route';
import {
  createLegacyGetHandler,
  createLegacyHeadHandler,
} from '@/legacy-api-routes/head';

export const GET = createLegacyGetHandler(legacyRoute.GET);
export const HEAD = createLegacyHeadHandler(GET);
export const POST = legacyRoute.POST;
