// @generated by scripts/generate-web-api-route-wrappers.js. Do not edit manually.

import * as legacyRoute from '@/legacy-api-routes/v1/workspaces/[wsId]/courses/[courseId]/route';

export const PUT = legacyRoute.PUT;
export const DELETE = legacyRoute.DELETE;
