name: mobile

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - "apps/mobile/**"
      - ".github/workflows/mobile.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "apps/mobile/**"
      - ".github/workflows/mobile.yaml"

jobs:
  check-ci:
    uses: ./.github/workflows/ci-check.yml
    with:
      workflow_name: mobile.yaml

  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1
    needs: [check-ci]
    if: needs.check-ci.outputs.should_run == 'true'

  build:
    needs: [check-ci]
    if: needs.check-ci.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 120
    defaults:
      run:
        working-directory: apps/mobile
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v6

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.x"
          channel: stable
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: 📦 Install Dependencies
        run: |
          dart pub global activate very_good_cli 1.1.0
          very_good packages get --recursive --ignore="!*"

      - name: ✨ Check Formatting
        run: dart format --set-exit-if-changed lib test

      - name: 🕵️ Analyze
        run: flutter analyze lib test

      - name: ✅ Bloc Lint
        run: |
          flutter pub global activate bloc_tools
          bloc lint .

      - name: 🧪 Run Tests
        timeout-minutes: 90
        run: flutter test --concurrency=1 -r expanded
